### ISSUE TITLE
Can we drop `jean85/pretty-package-versions:1.2`?

### ISSUE THREAD

**Issue by OskarStark** [mongodb/mongo-php-library#1022]
Is there a reason, we support two major versions?
https://github.com/mongodb/mongo-php-library/blob/49f3e3dcadd8d8014f011d308116bdd3d96ad350/composer.json#L16

IMHO `1.2` can safely be dropped, as `2.0` still supports PHP 7.1:
https://github.com/Jean85/pretty-package-versions/blob/ea175e0a262389d59d35802d9e32319fa64449c0/composer.json#L5-L6

**Comment by jmikola** [comment]
PHPLIB 1.9.0 required PHP 7.1+ (see: [composer.json](https://github.com/mongodb/mongo-php-library/blob/1.9.0/composer.json#L12)), so I don't think there's any reason to have `^1.2 ||` in the version field. I expect @Jean85 was just being conservative when opening PRs to add `|| ^2.0` in various projects (e.g. https://github.com/mongodb/mongo-php-library/pull/805). Feel free to submit a PR to remove `^1.2 ||` if you like.

**Comment by Jean85** [comment]
Yes I was being conservative because 1.x supports Composer 1.

If you drop 1.x, you drop support for Composer 1; that wasn't doable then, while now is up to you.

**Comment by OskarStark** [comment]
From my POV it is ok to drop support for Composer 1, while were are at Composer 2.5.1 right now.

WDYT @alcaeus ?

**Comment by alcaeus** [comment]
Given how long composer 1 has been out of date, I think it should be safe dropping support for it in the next minor version of the library.
