### ISSUE TITLE
Decision about `mongo-orchestration` folder and `Makefile`

### ISSUE THREAD

**Issue by OskarStark** [mongodb/mongo-php-library#1025]
Raised by @jmikola in https://github.com/mongodb/mongo-php-library/pull/1020:

* [ ] Remove the `mongo-orchestration` folder?
* [x] Remove `Makefile`?

If we found a decision, I am open to create PRs 👍 

cc @alcaeus

**Comment by jmikola** [comment]
Cross-referencing with [PHPLIB-1058](https://jira.mongodb.org/browse/PHPLIB-1058).

**Comment by OskarStark** [comment]
Based on https://github.com/mongodb/mongo-php-library/pull/1021#issuecomment-1377094419 we can remove the `Makefile`

**Comment by alcaeus** [comment]
Fixed in #1028.
