### ISSUE TITLE
[Documentation] Syntax highlighting in the method reference is not ideal

### ISSUE THREAD

**Issue by OskarStark** [mongodb/mongo-php-library#1036]
I developed a tool called [DOCtor-RST](https://github.com/OskarStark/doctor-rst) to analyze reStructuredText files and ensure consistency. We are using it in the Symfony documentation.

I tried to get it running for the docs included in this library locally.

As I know from
* #1032 

the opening PHP tag (`<?php`) is needed for PHP syntax highlighting.

I spotted, that we are using `.. code-block:: php`, for example here:
https://github.com/mongodb/mongo-php-library/blob/f236312d4b4770ae4f5c81a270e9178f1ecb9b26/docs/reference/method/MongoDBClient__construct.txt#L18-L23

which renders like (no highlighting):
![CleanShot 2023-01-17 at 07 02 37@2x](https://user-images.githubusercontent.com/995707/212821774-50530eb6-6c5b-4164-8f7f-4637bfde7f96.png)

It is used this way accross the whole `method` reference.

Shall we
**A)** keep it
**B)** add `<?php` open tag to be consistent and get highlighting for better readability, but more noise because of the `<?php`?
**C)** use `.. code-block:: none` instead

I would propose to use option **C**

Let me know your decision and I propose a PR.

I can also provide a PR to enabled DOCtor-RST via GithubActions if sth. in the `/docs/` folder changes.

Cheers

**Comment by alcaeus** [comment]
We are currently in the process of moving our docs building from giza to snooty (see PHPLIB-681), which will no longer require opening PHP tags to properly highlight PHP code. In order to avoid having duplicate issues here and in JIRA, I'm closing this issue in the mean time.
