### ISSUE TITLE
Force arrays as arrays instead of bsonArray?

### ISSUE THREAD

**Issue by eparlier** [mongodb/mongo-php-library#106]
Hi!
I'm using array_merge to merge multiple arrays from a bunch of documents. Used to work but not anymore since by default, arrays are now bsonarrays. Is there a way, when using find or findOne to get the arrays inside a document treated as arrays? I'm trying to avoid using my_bson_array->bsonSerialize(); to convert it since this occurs at many places in my soft.
Thank you

**Comment by eparlier** [comment]
Never mind, figured it out 
['typeMap' => ['array' => 'array']]

**Comment by camohub** [comment]
Where should I write this typeMap?

**Comment by derickr** [comment]
@camohub It's an option to the [``find()`` method](https://docs.mongodb.com/php-library/master/reference/method/MongoDBCollection-find/).

**Comment by camohub** [comment]
Thanks, its little late for my project.

**Comment by AndeYashwanth** [comment]
If you would prefer to have the results returned as an associative array, after executing your query you could call 
$cursor->setTypeMap(['root' => 'array', 'document' => 'array', 'array' => 'array']);

When you execute find(), aggregate() you will get the cursor that you can iterate using a for each loop in php.

source: https://www.php.net/manual/en/mongodb-driver-cursor.settypemap.php
