### ISSUE TITLE
Deprecated: Return type of MongoDB\Model\BSONDocument::bsonSerialize()

### ISSUE THREAD

**Issue by zjw749985355** [mongodb/mongo-php-library#1060]
### Bug Report
This is a simple demo.

```
require_once 'vendor/autoload.php'; 

use MongoDB\Client;

try {
    $mongoClient = new Client("mongodb://localhost:27017");
    $database = $mongoClient->selectDatabase("test_compatibility");
    $collection = $database->selectCollection("test_collection");

    $document = ['name' => 'teacher', 'email' => 'abc@example.com'];
    $result = $collection->insertOne($document);
    $insertedId = (string) $result->getInsertedId();

    echo "Inserted document with ID: {$insertedId}\n";

    $retrievedDocument = $collection->findOne(['_id' => new \MongoDB\BSON\ObjectId($insertedId)]);
    echo "Retrieved document: " . json_encode($retrievedDocument) . "\n";

    $collection->drop();
    echo "Test collection dropped.\n";

    echo "Compatibility test passed!\n";
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
```

"I also tried to use #[\ReturnTypeWillChange] to solve it, but it didn't have the desired effect."

### Environment

name     : mongodb/mongodb
descrip. : MongoDB driver library
keywords : database, driver, mongodb, persistence
versions : * 1.13.1
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : https://jira.mongodb.org/browse/PHPLIB
source   : [git] https://github.com/mongodb/mongo-php-library.git 0b8555705d2f9c12ab2e5cebee6b594cdfe6b4e0
dist     : [zip] https://api.github.com/repos/mongodb/mongo-php-library/zipball/0b8555705d2f9c12ab2e5cebee6b594cdfe6b4e0 0b8555705d2f9c12ab2e5cebee6b594cdfe6b4e0
path     : /Users/zjw/work/design/vendor/mongodb/mongodb
names    : mongodb/mongodb

support
issues : https://github.com/mongodb/mongo-php-library/issues
source : https://github.com/mongodb/mongo-php-library/tree/1.13.1

autoload
files
psr-4
MongoDB\ => src/

requires
ext-hash *
ext-json *
ext-mongodb ^1.14.0
jean85/pretty-package-versions ^1.2 || ^2.0.1
php ^7.2 || ^8.0
symfony/polyfill-php80 ^1.19

requires (dev)
doctrine/coding-standard ^9.0
squizlabs/php_codesniffer ^3.6
symfony/phpunit-bridge ^5.2

PHP 8.1.17 (cli) (built: Mar 16 2023 13:20:31) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies

_edited to format code - alcaeus_

**Comment by alcaeus** [comment]
What version of `ext-mongodb` are you running? You can find out by running `php --ri mongodb`.

Tentative return types such as the one causing this deprecation notice have been added in 1.15.0, so that makes me think you're using the new extension version with an older library version (1.13.1 according to the output in your post). In that case, the deprecation notice is absolutely expected, as that library version was not aware of any upcoming type changes. Upgrading `mongodb/mongodb` to `^1.15` will fix this issue, as we've added the necessary `ReturnTypeWillChange` attributes to `BSONDocument` and `BSONArray`.

**Comment by zjw749985355** [comment]
Thank you for your answer. I would like to apologize as I didn't realize that my local composer mirror source wasn't syncing the version information in a timely manner, so I had been assuming that 1.13.1 was the latest version and hadn't attempted to use 1.15. Now the issue has been resolved. Thank you.
