### ISSUE TITLE
configure: error: Cannot find OpenSSL's 

### ISSUE THREAD

**Issue by buttfacemonkey** [mongodb/mongo-php-library#108]
```

[jose@localhost ~]$ sudo pecl install mongodb
[sudo] password for jose: 
downloading mongodb-1.1.2.tgz ...
Starting to download mongodb-1.1.2.tgz (642,582 bytes)
.....................done: 642,582 bytes
349 source files, building
running: phpize
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525
building in /var/tmp/pear-build-root6aljUg/mongodb-1.1.2
running: /var/tmp/mongodb/configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 50416
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to use system libbson... no
checking configuring libmongoc... ...
checking whether to use system libmongoc... no
checking for pkg-config... /usr/bin/pkg-config
configure: error: Cannot find OpenSSL's <evp.h>
ERROR: /var/tmp/mongodb/configure' failed
```

Hey guys i need help with installing the php libraries. when i ran the pecl comand the terminal brought out this:
> configure: error:  Cannot find OpenSSL's <evp.h>
> ERROR: /var/tmp/mongodb/configure' failed

when i opened /var/tmp/ i couldn't even find the mongodb folder. what should i do.
if the formationg is wrong sorry mate im new here.

**Comment by gphargreaves** [comment]
What Linux distro are you running?

It seems like you are missing the OpenSSL or OpenSSL-dev packages.

**Comment by buttfacemonkey** [comment]
I'm running CentOS 7 is there a yum package for it?

**Comment by gphargreaves** [comment]
You should be able to install it using:

```
yum install -y openssl-devel
```

However my usual distro is Debian based so I am used to apt :-) you may have to troubleshoot syntax of that command.

Try installing after that and it should hopefully find the required OpenSSL source

**Comment by buttfacemonkey** [comment]
Sweet it installed! just one last thing mate.
`Build process completed successfully
Installing '/usr/lib64/php/modules/mongodb.so'
install ok: channel://pecl.php.net/mongodb-1.1.2
configuration option "php_ini" is not set to php.ini location
You should add "extension=mongodb.so" to php.ini
`

i can't find the php.ini file and people say to create a `<?php phpinfo(); ?>` but i cant open php files on my browser.
lastly i get permision denied from:
 >[jose@localhost ~]$ sudo echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
bash: /etc/php.ini: Permission denied

sorry for all the trouble im giving you.

**Comment by gphargreaves** [comment]
What web server have you installed to serve your website/project? Apache, Nginx or something else?

**Comment by buttfacemonkey** [comment]
oh dam. uh i thought i could use mongodb as a web server. sorry im completely new to website building im trying to this project: https://github.com/vichan-devel/vichan/blob/master/README.md what webserver should i install.
