### ISSUE TITLE
fatal error when save ObjectID to php session

### ISSUE THREAD

**Issue by lanlin** [mongodb/mongo-php-library#109]
I save some user base info with the CI's session driver, like userid, company_id... in an array.
All of these named xxx_id in the array are MongoDB's ObjectID, but when i save these data to session i got this error.

### Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'MongoDB\BSON\ObjectID' is not allowed' in [no active file]:0 Stack trace: #0 [internal function]: session_write_close() #1 {main} thrown in [no active file] on line 0. 

But, when using mongodb legacy driver for php,  all things fine.
I don't know how to solve it.

**Comment by lanlin** [comment]
Sorry, I find that this error is come from php session when the data that saved to session include the MongoDB\BSON\ObjectID. 
But, it's worked fine in mongodb legacy driver for php. Anyone knows how to solve it?

**Comment by alex-cc** [comment]
I think your issue is likely related to this : https://jira.mongodb.org/browse/PHPC-460

I am also wanting to do the same thing, just need to wait for it to be implemented.

**Comment by jmikola** [comment]
Indeed, this should be resolved with the issue @alex-cc linked (slated for extension 1.2.0). I'm going to close this out, as it's not related to the library and has a tracking ticket in the extension.
