### ISSUE TITLE
Compatibility layer for old code

### ISSUE THREAD

**Issue by DerManoMann** [mongodb/mongo-php-library#112]
Hi there,

I had a quick look around but couldn't find a compat layer on top of the new API to simulate the old extension. If there is any I'd be keen to learn about that.

In the meantime I started my own :https://github.com/DerManoMann/mongodb-bc :)

I've got a large project with lots of other issues around upgrading to PHP7, so having something that makes the existing (legacy) MongoDB code work is a big help.

Cheers, mano

**Comment by shanghaiyangming** [comment]
https://packagist.org/packages/alcaeus/mongo-php-adapter

https://github.com/alcaeus/mongo-php-adapter

The project is worth looking forward to!

**Comment by DerManoMann** [comment]
Thanks, just what I was looking for.
