### ISSUE TITLE
How to use this drivers with gridfs？

### ISSUE THREAD

**Issue by shanghaiyangming** [mongodb/mongo-php-library#113]
How to use this drivers with gridfs？

**Comment by elsonwu** [comment]
Not completed yet, please check - https://github.com/mongodb/mongo-php-library/pull/57 from 
https://github.com/mongodb/mongo-php-library/pulls

**Comment by jmikola** [comment]
GridFS support will be included in the 1.1.0 release (also being tracked in [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114)).

**Comment by AlexGnatko** [comment]
Can you give me an idea about how long the wait for GridFS support will be?

**Comment by jmikola** [comment]
@AlexGnatko: https://github.com/mongodb/mongo-php-library/pull/57 has been merged to master, so the code is available for development testing. I don't have a specific timeline for when we'll be able to tag 1.1.0, though. Some work on outstanding bugs and tasks pertaining to the extension is taking priority right now.

**Comment by rbro** [comment]
Is there any update on when GridFS support will be in an official release?  Thanks for your help.

**Comment by jmikola** [comment]
@rbro: [1.0.0-alpha1](https://github.com/mongodb/mongo-php-library/releases/tag/1.1.0-alpha1) has finally been tagged and includes the GridFS classes.

**Comment by si2w** [comment]
@jmikola It seems that the class is integrated but there are no documentation. Do you know how to use it ?

**Comment by lindelius** [comment]
@si2w https://docs.mongodb.com/php-library/master/tutorial/gridfs/
