### ISSUE TITLE
How to iterate through the cursor from collection query?

### ISSUE THREAD

**Issue by litan1106** [mongodb/mongo-php-library#114]
How to iterate through the cursor from collection query?

I got 50 docs with the php library. However I got 144 docs from the mongo shell.

**Comment by jmikola** [comment]
Please share some code that populates the collection contents and iterates (the shell iteration shouldn't be necessary), so we can try reproducing this.

**Comment by litan1106** [comment]
//Example code
                    $groupArray = [ '$group' =>[
                        '_id' => ['AccountId' => '$AccountId'],
                        'Cost' => ['$sum' => '$Cost'],
                    ]];

                    // Filter by Account Id, Network
                    $combinedFilter = [
                        [ '$match' => [
                            'AccountId' => $aid]
                        ],
                        $groupArray
                    ];
  public function aggregateDocumentsByFilter($collection, $filter)
    {
        $cursor = $collection->aggregate($filter)->toArray();

        return $cursor;
    }

**Comment by jmikola** [comment]
@litan1106: Do you have any code for populating this collection with data? I'd like to have something that reproduces the entire problem on your end (from the beginning) so that we can compare and investigate.
