### ISSUE TITLE
Performance issue with PHP 8.2 

### ISSUE THREAD

**Issue by aanair08** [mongodb/mongo-php-library#1143]
Our project has been migrated from Symfony 3.4 to Symfony 5.4. We have found that it is slower than 3.4. We tried the base Symfony projects in 3.4 and 5.4 with just insertion and found the same performance issue.

Therefore, we created a PHP script that inserts a few data into the document using this library in order to identify the root cause. There is an issue there. Slowness is either caused by the library being connected to a DB server with a lot of concurrent operations.  There may be a problem with the configuration of our DB server.  

The issue can only be recreated on a DB Server that has a lot of data and a lot of concurrent operations. 

**In order to find the actual problem and resolve it, I am posting this here.**

**Comment by alcaeus** [comment]
Hi @aanair08,

unfortunately your report does not contain enough information for us to provide any help. You reported that you updated from Symfony 3.4 to Symfony 5.4 and experienced performance degradation, but there is no info as to whether any MongoDB components were updated. Furthermore, there is no information on what server version you are running on, where that server is hosted, what cluster structure (standalone, replicated, sharded) you are using, or any other relevant information. From the information you shared, it sounds more like this is not related to the PHP driver itself, but rather to the server configuration. For more general help regarding MongoDB, I would suggest checking and posting in the [MongoDB Community Forums](https://www.mongodb.com/community/), which may help you with configuration issues.

I'm closing this issue as there's nothing we can do here. If you manage to narrow down the issue to suspect a performance issue in the driver, please add more information here and we can reopen the issue if necessary.

**Comment by aanair08** [comment]
@alcaeus Thank you for the response we have sorted out the issue. Which was a configuration issue. We have used a replica server and we missed a configuration that was never used in Symfony 3.4 configuration. That caused the performance degrading.
