### ISSUE TITLE
php: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all

### ISSUE THREAD

**Issue by jonathanpmartins** [mongodb/mongo-php-library#115]
I dont know if this is the right place to put it but I have a problem. In my case Im using Lumen 5.2, PHP 7.0.2 - MongoDB 1.1.2 - Ubuntu 14.04... etc.

On my composer.json file
        
    "illuminate/redis":"5.2.*",
    "predis/predis": "^1.1@dev"

When i run my unit tests it results in this error:

```
.2016/02/03 15:35:03.0458: [ 1359]:    DEBUG:       client: Using custom stream initiator.
php: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all
```

The only reference on google whas this file: https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-uri.c

When I install everything in the server I use the ```ondrej/php```repository. You can look-up the setup installation script here: https://github.com/jonathanpmartins/ubuntusetup/blob/master/server/setup-php7-nginx-1.9.10-ubuntu-14.04.sh

Perhaps I should open a issue on another repository. Can someone help me out?

**Comment by jonathanpmartins** [comment]
after installing the last version of libmongoc the problem is gone!
http://api.mongodb.org/c/1.3.2/installing.html

**Comment by jmikola** [comment]
@jonathanpmartins: thanks for following up with your solution.

@oerdnj: I assume the extension package is using shared libmongoc and libbson libraries. Is it possible the extension package was missing a dependency bump on libmongoc? I'm just curious if `apt-get` should have been able to handle this.

**Comment by jonathanpmartins** [comment]
You can see my step by step explained here: https://github.com/mongodb/mongo-php-driver/issues/219#issuecomment-179858933

**Comment by oerdnj** [comment]
@jmikola correct packaging would handle this, but this seems to be result of mixing hand compiled stuff with packaged libraries. The packaged `php-mongodb` doesn't use any private symbols.

Anyway that's exactly what I warned about - relying on private symbols that often change is a really bad idea.

**Comment by jmikola** [comment]
@oerdnj: Thanks for the follow-up. We are actively sorting through all of the private symbol usage and will hopefully have public APIs added to libmongoc by 1.4.0 for use by our PHP and HHVM drivers (as discussed in https://github.com/mongodb/mongo-php-driver/issues/219#issuecomment-181666483).
