### ISSUE TITLE
MongoDB\BSON\Date unable to assign date in desired format

### ISSUE THREAD

**Issue by hoodlumer** [mongodb/mongo-php-library#118]
Objective is to assign a mongodb ISODate to a php variable. So this is a BSON date object and I am trying to get the date or rather milliseconds property, which I am unable to get. 

```
MongoDB\BSON\UTCDateTime Object ( [milliseconds] => 1455454800000 )
```

PHP MongoDB Environment:
mongodb version  1.1.0
mongodb stability  stable
ibmongoc version  1.1.2
libbson version  1.1.3

MongoDB Pecl Driver php_mongodb-1.1.0-5.6-nts-vc11-x86 
mongodb/mongo-php-library 1.0.0
(composer gave exception php_mongodb driver not installed when using the php_mongodb-1.1.0-5.6-nts-vc11-x64 but accepted the php_mongodb-1.1.0-5.6-nts-vc11-x86 ) 

2016-02-09T22:12:26.428+0000 I CONTROL  [initandlisten] db version v3.2.1
2016-02-09T22:12:26.428+0000 I CONTROL  [initandlisten] git version: a14d55980c2
cdc565d4704a7e3ad37e4e535c1b2
2016-02-09T22:12:26.429+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL
 1.0.1p-fips 9 Jul 2015
2016-02-09T22:12:26.429+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2016-02-09T22:12:26.429+0000 I CONTROL  [initandlisten] modules: none
2016-02-09T22:12:26.429+0000 I CONTROL  [initandlisten] build environment:
2016-02-09T22:12:26.430+0000 I CONTROL  [initandlisten]     distmod: 2008plus-ssl
2016-02-09T22:12:26.430+0000 I CONTROL  [initandlisten]     distarch: x86_64
2016-02-09T22:12:26.430+0000 I CONTROL  [initandlisten]     target_arch: x86_64

document:
```
{
        "_id" : ObjectId("56b91366bb782f1d925ef9df"),
        "playerLastName" : "Smith",
        "fixture" : [
                {
                        "opposition" : "Bisons",
                        "date" : ISODate("2016-02-14T13:00:00Z"),
                        "venue" : "Parklands",
                        "available" : 0
                }
        ],
        "playerFirstName" : "John"
} 
```
php
```
foreach ($document as $value) {
	$fixtureSel_firstName = $value["playerFirstName"];
	$fixtureSel_lastName = $value["playerLastName"];
	for($i = 0; $i < count($value['fixture']); $i++) {
		$fixtureSel_opposition = $value['fixture'][$i]['opposition'];
		$fixtureSel_date = $value['fixture'][$i]['date'];
		
		$utcdatetime = new MongoDB\BSON\UTCDateTime($fixtureSel_date);
		$datetime = $utcdatetime->toDateTime();
		var_dump($datetime);
```

Error
PHP Fatal error:  Uncaught exception 'MongoDB\Driver\Exception\InvalidArgumentException' with message 'MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be long, object given'

Obviously you can't use the Date object returned, but how do you get the milliseconds and pass that ? 

If I pass a string
```
$date = '1455454800000';

$utcdatetime = new MongoDB\BSON\UTCDateTime($date);
$datetime = $utcdatetime->toDateTime();
$mydate = $datetime->format('Y-m-d H:i:s');
print $mydate;
```
I get 2016-02-14 13:00:00 which is what I am looking for.

Appreciate any pointers on this.

**Comment by jacqueswaller** [comment]
You can cast to string to get the milliseconds as a string.
```
$fixtureSel_date = $value['fixture'][$i]['date'];
$millisecondsString = (string)$fixtureSel_date;
$utcdatetime = new MongoDB\BSON\UTCDateTime($millisecondsString);
```

Strictly speaking, the constructor for UTCDateTime takes an integer but a string will be converted if it is numeric.

**Comment by hoodlumer** [comment]
@jacqueswaller thanks, that works like a charm. 
btw prior to this I did try it with $date as an int passed to UTCDateTime,  it threw an exception but worked with a $date as string.

**Comment by jacqueswaller** [comment]
ah, yeah you're right in the x86 version of the driver I believe it's meant to take a string for the constructor since there's otherwise no way to supply a giant number like 1455454800000.

**Comment by hoodlumer** [comment]
@jacqueswaller thanks for explanation. I couldn't get x64 version of the 1.1.0 driver working as composer threw exception when attempting install the mongo-php-library - saying it couldn't find the php_mongodb.dll (even though it was installed & php.ini was correct). But I think I can live with the x86 version for now.
