### ISSUE TITLE
Upsert option not working

### ISSUE THREAD

**Issue by Henk8** [mongodb/mongo-php-library#120]
I have implemented this new library and the save function is deprecated. I wan't to use the insertOne with the upsert option, but it fails.

```
$this->_connection = new MongoDB\Client($host);
$this->_db = $this->_connection->{$this->_database};

$this->_collection = $this->_db->{$this->_table};
$this->_collection->createIndex(array("_id" => 1));

$result = $this->_collection->insertOne(array("_id" => $this->key($id, $group), "group" => $group, "data" => $data, "timeStamp" => time() + $this->options['lifetime']), ['upsert' => true]);
```

This will return a BulkWrite error with code 0 and no message.
What is wrong with the code?

**Comment by jacqueswaller** [comment]
I've only ever used upsert with the `update` function. Like my understanding is "update, but insert if not exists". So presumably the upsert option in this case will be ignored.

Also I think errors are handled as exceptions now (`UpdateResult` has no API for getting error messages). If you try/catch and check the exception's error message, I'd bet a nickel that your `insertOne` is failing because you already have a document with that ID. So yeah use `updateOne` :smile:

**Comment by Henk8** [comment]
I do use the try/catch construction. The error message is: BulkWrite error.
So I moved to the updateOne construction and now the message is:  First key in $update argument is not an update operator. 

The code is:

> $result = $this->_collection->updateOne(array("_id" => $this->key($id, $group)), 
> 								array("_id" => $this->key($id, $group), "group" => $group, "data" => $data, "timeStamp" => time() + $this->options['lifetime']), 
> 								['upsert' => true]);
> 

What am I doing wrong. Can you perhaps give me some example code that works, that would really help :wink:

**Comment by alcaeus** [comment]
If you're not using update operators, you're not updating a document but replacing it. Thus, use the `replaceOne` method instead of `updateOne`.

**Comment by Henk8** [comment]
That seems to do the trick.
The code is now:

```
> $result = $this->_collection->replaceOne(["_id" => $this->key($id, $group)],
> 								             ["_id" => $this->key($id, $group), "group" => $group, "data" => $data, "timeStamp" => time() + $this->options['lifetime']],
> 								             ['upsert' => true]);
```

Thanks!

**Comment by derickr** [comment]
@alcaeus provides the right answer. I'm marking this as closed.

The library's documentation at http://mongodb.github.io/mongo-php-library/classes/collection/#crud-operations says "CRUD is an acronym for Create, Read, Update, and Delete. The Collection class implements MongoDB’s cross-driverCRUD specification, which defines a common API for collection-level read and write methods." It links to https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#update-vs-replace-validation, which discusses the differences between update and replace.

I do think, that the library's documentation should be improved on this. It's in the repository at https://github.com/mongodb/mongo-php-library/blob/master/docs/classes/collection.md#crud-operations if you want to give this a shot yourself.

**Comment by jmikola** [comment]
Created [PHPLIB-178](https://jira.mongodb.org/browse/PHPLIB-178) to track this task.
