### ISSUE TITLE
Unable to use useCursor false in aggregate

### ISSUE THREAD

**Issue by nalscher** [mongodb/mongo-php-library#121]
I can't do this :

$collection->aggregate($pipeline, [
     'useCursor' => false,
]);

i have always the error : 
"typeMap" option should not be used if "useCursor" is false

even if i do this : 
$collection->aggregate($pipeline, [
     'useCursor' => false,
     'typeMap' => null
]);

or
$database->selectCollection('calls', [
      'typeMap' => null
]);

i think it's due to : 
Collection.php line 112 : $this->typeMap = isset($options['typeMap']) ? $options['typeMap'] : self::$defaultTypeMap;
and in the same file line 163 : 
if ( ! isset($options['typeMap'])) {
            $options['typeMap'] = $this->typeMap;
        }

we always have a value in typeMap, the default or the custom one but never null

**Comment by alcaeus** [comment]
See #107.

**Comment by nalscher** [comment]
Ok it's redundant with #107.
Maybe you can accept the pull request to have the correction ?
