### ISSUE TITLE
Is there any analog of MongoDate in new library?

### ISSUE THREAD

**Issue by p-golovin** [mongodb/mongo-php-library#122]
Didn't find it in documentation. But it is used in Monolog for example:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/MongoDBFormatter.php#L103

With old driver i've got:
```json
        "expires" : ISODate("2016-08-10T19:06:40.000Z"),
```

With new one:
```json
        "expires" : {
            "sec" : 1.47086e+009,
            "usec" : 0
        }
```

**Comment by alcaeus** [comment]
The corresponding class would be [MongoDB\BSON\UTCDateTime](https://secure.php.net/manual/de/class.mongodb-bson-utcdatetime.php).

**Comment by p-golovin** [comment]
@alcaeus Thanks
