### ISSUE TITLE
Documentation for .group

### ISSUE THREAD

**Issue by nilportugues** [mongodb/mongo-php-library#127]
Hello.

I managed to code a full library using this library (https://github.com/nilportugues/php-mongodb-repository)... but I haven't managed to do get this running: 

```js
db.book_facets.group({
    "key": {
        "facetName": true,
        "facetValue": true
    },
    "initial": {
        "total": 0
    },
    "reduce": function(obj, prev) {
        if (obj.facetValue != null) if (obj.facetValue instanceof Array) prev.total += obj.facetValue.length;
        else prev.total++;
    }
});
```

Any clues or better documentation on how to run this?
Thanks

**Comment by derickr** [comment]
I'm not sure whether you found the right github repository. Your code example is in javascript? This is the repository for the PHP library...

**Comment by nilportugues** [comment]
Hey @derickr thanks for the reply!

Thing is I'm trying to do this in PHP, and I wrote that repository, but I'm clueless on how to do this after examining this library's API.

**Comment by jmikola** [comment]
@nilportugues: The PHP library doesn't include a wrapper for the [`group`](https://docs.mongodb.org/manual/reference/command/group/) command, so at present you'll need to use the `Database::command()` method directly by executing a command document:

```
$database = (new MongoDB\Client)->selectDatabase('test');
$cursor = $database->command([
    'group' => [
        'ns' => 'book_facets',
        'key' => ['facetName' => true, 'facetValue' => true],
        'initial' => ['total' => 0],
        '$reduce' => new MongoDB\BSON\Javascript('...'),
    ]
]);

$resultDocument = $cursor->toArray()[0];
```

I've opened [PHPLIB-177](https://jira.mongodb.org/browse/PHPLIB-177) to track the request and linked it to a pre-existing ticket we have to also create a [`mapReduce`](https://docs.mongodb.org/manual/reference/command/mapReduce/) helper in 1.1.0. While we definitely plan to add `mapReduce`, we were on the fence with `group` as it's generally discouraged in favor of the aggregation pipeline and `mapReduce`. In any event, that should be the ticket to watch for any future API changes.

**Comment by nilportugues** [comment]
@jmikola @derickr thanks :+1:
