### ISSUE TITLE
how can I select DB and authenticate

### ISSUE THREAD

**Issue by oblank** [mongodb/mongo-php-library#128]
old mongo extension,  has functions selectDB and authenticate, but how can I do same thing with mongodb extension?

thx

**Comment by jacqueswaller** [comment]
Assuming you've constructed a Client object, you can get a database by executing `selectDatabase`

http://mongodb.github.io/mongo-php-library/api/class-MongoDB.Client.html

```
selectDatabase( string $databaseName, array $options = [] )
Select a database.
Parameters
$databaseName
Name of the database to select
$options
Database constructor options
Returns
MongoDB\Database
See
Database::__construct() for supported option
```

**Comment by jacqueswaller** [comment]
I'm not sure how to authenticate once already connected, but my assumption is that if you try to create a client (or a Manager, for that matter) and the credentials are wrong, then a `MongoDB\Driver\Exception\AuthenticationException` will be thrown.

http://php.net/manual/en/class.mongodb-driver-exception-authenticationexception.php

**Comment by TanaseButcaru** [comment]
I also wanted to know this. I'm creating a new client, select the database, but then how do I auth to it?
```php
     $MongoClient = new MongoDB\Client($this->db_host);
     $this->db = $MongoClient->selectDatabase($this->db_name);
     // no auth() method!
     $this->db->auth('user','pass');
   
```

From mongodb [docs](https://docs.mongodb.org/manual/reference/connection-string/), I found that you can login to a specific database upon connection. So my code becomes:
```php
        $mongodbConnectionURI = 'mongodb://'. $this->db_user .':'. $this->db_pass .'@'. $this->db_host .'/'. $this->db_name;
		$MongoClient = new MongoDB\Client($mongodbConnectionURI);

		$this->db = $MongoClient->selectDatabase($this->db_name);
		$this->db->createCollection('abc'); //THIS IS A SUCCESS NOW!!
```

**Comment by derickr** [comment]
@TanaseButcaru provides the right answer. You can only specify authentication credentials through the connection string. 

There is an example in the docs at http://docs.php.net/manual/en/mongodb-driver-manager.construct.php, but I will update the old driver's docs to link to the new example: http://news.php.net/php.doc.cvs/14034

**Comment by oblank** [comment]
thanks all :+1: @jacqueswaller  @TanaseButcaru @derickr

**Comment by Sammaye** [comment]
What is the point in having a manager dispatcher with the ability to select different databases if you can only auth to one database per time in the manager's connection string?

I mean I understand if you put all your users into the admin database and authed against that but not everyone does.

**Comment by Sammaye** [comment]
Actually I might see the point of this. Especially when you have the roles for one DB but you want to use multiple DBs in the app, i.e.:

- app (main db and auth db)
- reporting (used for reporting only)
- another_company app
- etc

So yeah, I think I see the point now

**Comment by oblank** [comment]
in my knowledge， you should auth DB separately

**Comment by jmikola** [comment]
Just to reiterate why this is designed as such. In the legacy driver, authenticating after a connection was established meant that we had to mark the socket as unavailable for re-use, thereby circumventing its persistence. If not, the socket might get re-used on a subsequent request and inherit more auth credentials than expected (essentially leaking access between requests and possibly apps on the same server). Knowing the auth credentials at connection time allows us to carefully persist the socket (identified by those credentials) to avoid such a leak.

Authentication and roles in MongoDB is also more versatile than granting a user access to a single database at a time, so it's entirely possible that an authenticated user could be allowed to select and operate with multiple databases.

**Comment by lhzw** [comment]
> I also wanted to know this. I'm creating a new client, select the database, but then how do I auth to it?
> 
> ```
>      $MongoClient = new MongoDB\Client($this->db_host);
>      $this->db = $MongoClient->selectDatabase($this->db_name);
>      // no auth() method!
>      $this->db->auth('user','pass');
> ```
> 
> From mongodb [docs](https://docs.mongodb.org/manual/reference/connection-string/), I found that you can login to a specific database upon connection. So my code becomes:
> 
> ```
>         $mongodbConnectionURI = 'mongodb://'. $this->db_user .':'. $this->db_pass .'@'. $this->db_host .'/'. $this->db_name;
>         $MongoClient = new MongoDB\Client($mongodbConnectionURI);
> 
>         $this->db = $MongoClient->selectDatabase($this->db_name);
>         $this->db->createCollection('abc'); //THIS IS A SUCCESS NOW!!
> ```

For me, I don't like to create on collection, this is better for me:
$db = $client->selectDatabase('nonedb');
$db->listCollections();
