### ISSUE TITLE
 Xampp can not start after include extension=mongodb.so in php.ini 

### ISSUE THREAD

**Issue by dongmai** [mongodb/mongo-php-library#129]
Hi everyone,

I installed this driver successfully and got the file mongodb.so but when I am trying to use it with Xampp - add the line extension=mongodb.so into php.ini file . But Xampp can not start, it can start fine without this line.

Can please someone look at this issue.
Many thanks.

**Comment by dongmai** [comment]
I checked error log file but didnt see anything.

**Comment by jmikola** [comment]
Closing this as a duplicate of https://github.com/mongodb/mongo-php-driver/issues/247.
