### ISSUE TITLE
¿how can i get the number of documents (count) from a cursor?

### ISSUE THREAD

**Issue by gustavomanolo** [mongodb/mongo-php-library#130]
https://docs.mongodb.org/manual/reference/method/cursor.count/
I was trying to use the $cursor->count(), but i get the error "Call to undefined method MongoDB\Driver\Cursor::count()".

**Comment by alcaeus** [comment]
The new driver no longer provides a `count` method in the cursor class. For an explanation as to why that change was made, @jmikola explained it in [this comment](https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194).

**Comment by jmikola** [comment]
Thanks for cross-referencing my previous comment, @alcaeus!

@gustavomanolo: Running `Collection::count()` with the same query filter is functionally equivalent to the legacy driver's [`MongoCursor::count()`](http://php.net/manual/en/mongocursor.count.php) method.

**Comment by AlexGnatko** [comment]
Should I call Collection:count() before or after Collection:find()? If I call 'count' before, will it execute the actual find query on the server twice?

**Comment by alcaeus** [comment]
It doesn't matter if you call it before or after `find`, the query will be executed twice. This is, by the way, the same thing the `MongoCursor` class in the legacy driver did, except that it wasn't quite advertised. So, there should not be any performance issues from this.
