### ISSUE TITLE
Help in aggregation

### ISSUE THREAD

**Issue by ajpyoung** [mongodb/mongo-php-library#132]
Hello,

I hope I'm not out of line asking this question here. We have an existing Node.js program and are converting it to PHP due to resource limitation (e.g. it's difficult finding good node devs). We have an aggregation process that I can't seem to find an equivalent using this library.

The code in node
```
    var query = [{"$match":{"product_pool":{"$in":product_pool}}}, 
	  {"$unwind":"$product_pool"}, 
	  {"$group": { 
	    _id:"$_id", 
	    matches:{
	      "$sum":sumGenerator(product_pool)
	      }, 
	    "unique_id":{"$first":"$unique_id"}, 
	    "product_pool":{"$push":"product_pool"}
	    }
	  },
	  {"$sort":{"matches":-1}},
	  {"$limit":20},  
	  {"$project":{"matches":1, "array":{"unique_id":"$unique_id", "product_ids":"$product_ids"}}}];

    db.foobar.aggregate(query,function(err,docs){
      if(err==null)
      {
        foobar_processor.start(unique_id,docs);
      }
    });
```
product_pool = array of ids inside the mongodb document

Can you please give us an idea about converting this process to PHP?

**Comment by jmikola** [comment]
[Collection::aggregate()](http://mongodb.github.io/mongo-php-library/api/class-MongoDB.Collection.html#_aggregate) should be what you're looking for. We haven't gotten a chance to add an example to the [tutorial-style documentation](http://mongodb.github.io/mongo-php-library/), so it's currently just listed in the API reference.

**Comment by ajpyoung** [comment]
Thanks, sent this to the team handling the conversion

**Comment by jmikola** [comment]
An aggregation example is now present in the [CRUD tutorial](http://mongodb.github.io/mongo-php-library/tutorial/crud/#aggregation) and we've improved the class-level documentation (see: [`Collection::aggregate()`](http://mongodb.github.io/mongo-php-library/classes/collection/#aggregate). I'm going to close this out.
