### ISSUE TITLE
Is there a way to generate new ObjectID?

### ISSUE THREAD

**Issue by serkin** [mongodb/mongo-php-library#133]
I need to generate ObjectID for embedded document.
Unfortunately I didn't find any examples in the tests

Thx in advance!

**Comment by jacqueswaller** [comment]
it should be as easy as
`new MongoDB\BSON\ObjectID()`

**Comment by serkin** [comment]
But constructor requires parameter _string $id_

**Comment by alcaeus** [comment]
> But constructor requires parameter string $id

Nope: https://secure.php.net/manual/de/mongodb-bson-objectid.construct.php.

**Comment by serkin** [comment]
Thank you!
You are right. I was following my IDE hint. In stub file it is not obvious

        /**
         * Class ObjectID
         * @link http://php.net/manual/en/class.mongodb-bson-objectid.php
         */
        class ObjectID implements Type
        {
            /**
             * ObjectID constructor.
             * @link http://php.net/manual/en/mongodb-bson-objectid.construct.php
             * @param string $id
             */
            public function __construct($id)
            {
            }

            /**
             * @link http://php.net/manual/en/mongodb-bson-objectid.tostring.php
             * @return string
             */
            public function __toString()
            {
            }
        }
