### ISSUE TITLE
How to set a timeout for new mongodb driver

### ISSUE THREAD

**Issue by clintcan** [mongodb/mongo-php-library#137]
Hi There,

On the old client, you can set a timeout:

```
$mongo = new MongoClient("mongodb://localhost:27017", 
    array(
        "socketTimeoutMS" => 100000
    )
);
```

and for timeouts for executing queries.

Is it similar to adding it to the option section for connecting to the new driver?

**Comment by jmikola** [comment]
This is still supported as a URI option for [`MongoDB\Driver\Manager::__construct()`](http://php.net/manual/en/mongodb-driver-manager.construct.php) (and `MongoDB\Client`, which passes its arguments along). You can specify it either in the URI string (as a query string parameter) or via the options array (as you've done above). Note that no longer have an API for customizing the socket timeout per operation (e.g. `MongoCursor::timeout()` in the legacy driver).
