### ISSUE TITLE
Support for legacy GridFS buckets

### ISSUE THREAD

**Issue by Fiskie** [mongodb/mongo-php-library#140]
I've been waiting for the GridFS spec to be implemented as I've been waiting to upgrade a project to PHP7. It was accepted a few days ago, so now that's done...

The new GridFS spec requires the use of an ObjectID for GridFS buckets. The Bucket class explicitly needs ObjectIDs in the methods, and the GridFSUpload class is hardwired to make documents with an ObjectID _id. This imposes a problem, as I am currently running a project that stores over 40 million documents using string _ids.

I've worked around the problem by [forking the repo and making the minimal changes needed](https://github.com/mongodb/mongo-php-library/compare/master...Fiskie:master) so files can be uploaded without the use of ObjectIDs. I don't think I should submit it as a pull request as it encourages overriding an internal class.

Is there a plan for supporting legacy buckets where an ObjectID _id was not enforced?

**Comment by jmikola** [comment]
> It was accepted a few days ago, so now that's done...

The GridFS PR was merged in response to numerous users requesting it (presumably to start testing with it). The author has also moved on another project, so there was no more immediate work to be done on the PR. We still have some work to do before locking in its API with a 1.1.0 release, so I would not consider it "done" by any means.

That said, thanks for the feedback. The [GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) does talk a bit about your concern:

> Note: if a file in a GridFS bucket was added by a legacy implementation, its id may be of a type other than ObjectId. Drivers that previously used id’s of a different type MAY implement a download() method that accepts that type, but MUST mark that method as deprecated.

The spec dictates that we create new files with ObjectIds for the `_id` field and that download methods take the same. I expect we will add separate methods (or perhaps a separate Bucket class) with the type-hint removed to allow querying for legacy files.

I've opened [PHPLIB-188](https://jira.mongodb.org/browse/PHPLIB-188) to track this.

**Comment by clem-compilatio** [comment]
The [GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) has [changed](https://github.com/mongodb/specifications/commit/9c4e13e9b7327a87b4b563d4be7c027a4f8a4dec) :

> Why have we changed our mind about requiring the file id to be an ObjectId?
> 	This spec originally required the file id for all new GridFS files to be an ObjectId and specified that the driver itself would be the one to generate the ObjectId when a new file was uploaded. While this sounded like a good idea, it has since become evident that there are valid use cases for an application to want to generate its own file id, and that an application wouldn't necessarily want to use ObjectId as the type of the file id. The most common case where an application would want to use a custom file id is when the chunks collection is to be sharded and the application wants to use a custom file id that is suitable for sharding. Accordingly, we have relaxed this spec to allow an application to supply a custom file id (of any type) when uploading a new file.

**Comment by jmikola** [comment]
@clem-compilatio: thanks for cross-referencing. This GitHub issue was one of several that was brought up and resulted in that change.

**Comment by jmikola** [comment]
This has been fixed in https://github.com/mongodb/mongo-php-library/pull/191.
