### ISSUE TITLE
findAll()

### ISSUE THREAD

**Issue by CihanAksoy** [mongodb/mongo-php-library#141]
How can i use findAll() ?

**Comment by jmikola** [comment]
No such method exists in this library, the [ext-mongodb](php.net/mongodb) driver, or the legacy [ext-mongo](php.net/mongo) driver. What are you attempting to do?

The library provides a [`Collection::find()`](http://mongodb.github.io/mongo-php-library/classes/collection/#finding-one-or-more-documents) method to issue queries, and the underlying driver has a [`MongoDB\Driver\Manager::executeQuery()`](http://php.net/manual/en/mongodb-driver-manager.executequery.php) method to do the same.

**Comment by lindelius** [comment]
As @jmikola pointed out, there is no `findAll()` function, however, you can use the `find()` function to retrieve all results by passing an empty array as filter (or nothing at all, since it defaults to an empty array). The following code is equal to using a `findAll()` function:

```
$client= new \MongoDB\Client();
$database = $client->selectDatabase('my_database');

$results = $database->selectCollection('my_collection')->find();
```

**Comment by jmikola** [comment]
Closing this, since we haven't heard back from the OP in some time.
