### ISSUE TITLE
Consider allowing updates with no update operators

### ISSUE THREAD

**Issue by Sammaye** [mongodb/mongo-php-library#142]
This is still supported in the database. Has this been stopped since it is deprecated in the DB now?

**Comment by alcaeus** [comment]
I assume you've been using the `updateOne` and `updateMany` methods. You are correct, these no longer support updates without update operators. This is considered a replace and accessible through the `replaceOne` method.

**Comment by Sammaye** [comment]
Ah, ok koool. Problem solved then thanks didn't see that
