### ISSUE TITLE
Unable to exclude a field

### ISSUE THREAD

**Issue by kschroeder** [mongodb/mongo-php-library#147]
I might just be missing this in the code but I'm having some difficulty figuring out how to exclude subdocuments from a result.  One of the collections I'm working with can have fairly extensive array of subdocuments and the unserialize() functionality takes a fair amount of resources.  I've moved the functionality into an aggregate() function (which is awesome BTW) but I would like to omit retrieving those subdocuments from my normal queries so I don't have to bear with the overhead of unserialization.

In the old MongoDB Collection I could specify 

```
db.inventory.find(
   { type: 'food', _id: 3 },
   { "classification.category": 0}
)
```

but I can't find how that can be accomplished with this library.

**Comment by jmikola** [comment]
The `Collection::find()` and `Collection::findOne()` methods take a `projection` option, which corresponds to the second argument in your example. This is equivalent to the `projection` option on the [MongoDB\Driver\Query](http://php.net/manual/en/mongodb-driver-query.construct.php) object in the underlying driver.

This will be properly documented in https://github.com/mongodb/mongo-php-library/pull/144. To copy/paste an example from that PR:

```
$document = $collection->findOne(
    ['_id' => '10011'],
    ['projection' => ['pop => 1']]
);
```

**Comment by kschroeder** [comment]
And there's 5 seconds off my elapsed execution time.  Thanks a bunch.
