### ISSUE TITLE
Question about versioning

### ISSUE THREAD

**Issue by fvelcker** [mongodb/mongo-php-library#1488]
Hello,

As 1.20 remove support for 3.6, shouldn't the version being bump to 2.0 as it is a breaking changes?

I am asking because we are using the Laravel package which required this package (from ^1.18), and our mongo (cosmos) is in 3.6 (I know we should update it). Because of this update, and being a MINOR change, our service is now broken. 

We'll find a workaround to make it work, but I guess I just wanted to highlight the versioning question.

**Comment by fvelcker** [comment]
Closing as duplicated: https://github.com/mongodb/mongo-php-library/issues/1489

**Comment by alcaeus** [comment]
I've explained this in https://github.com/mongodb/mongo-php-library/issues/1489#issuecomment-2419255685 - please refrain from opening multiple issues about the same topic.
