### ISSUE TITLE
Getting new mongo _id from insertOne()

### ISSUE THREAD

**Issue by Zelfapp** [mongodb/mongo-php-library#149]
In the legacy driver for [insert](http://us2.php.net/manual/en/mongocollection.insert.php), the array passed to insert is amended with an _id field. This appears to be a breaking change. What is the correct method to get the new mongo _id key on inserts? Is it the code below or is there an option to keep this behavior in new mongodb php library? I'd like to be able to keep the behavior if possible.

`
$result->getInsertedId()`

![screenshot_3](https://cloud.githubusercontent.com/assets/11559805/14148373/0c8c9aae-f654-11e5-86ff-7f23caeec8d3.png)

**Comment by jmikola** [comment]
> Is it the code below or is there an option to keep this behavior in new mongodb php library?

`InsertOneResult::getInsertedId()` and `InsertManyResult::getInsertedIds()` are the methods to use. The new driver and library no longer modify the input argument (i.e. the behavior you referred to in the legacy driver).

I've added this to the Upgrade Guide documentation page in https://github.com/mongodb/mongo-php-library/commit/f66f430a7625430f5dde7e57de1b7597ffa58018, which is now published [here](http://mongodb.github.io/mongo-php-library/upgrade-guide/#accessing-ids-of-inserted-documents).
