### ISSUE TITLE
'Serialization of 'MongoDB\BSON\ObjectID' is not allowed'

### ISSUE THREAD

**Issue by kschroeder** [mongodb/mongo-php-library#150]
This is an error that is being the bane of my existence over the past few days.  I believe that in the old library the MongoID object could be serialized.  Given that it is not an unusual use case (think storing an account document in the session) it would be really nice if this could be made to be serializable.  I can work around it, of course, but it feels like an unnecessary (from my end) extra step.

**Comment by jmikola** [comment]
Enabling PHP serialization of the BSON classes is being tracked in [PHPC-460](https://jira.mongodb.org/browse/PHPC-460).

**Comment by spirin** [comment]
Same problem. I'm looking forward the problem solution. Sessions, caching, saving intermediate computation results. There are many situations where we need a simple serialize() php-function.

**Comment by mbretter** [comment]
Same Problem here, I'm trying to switch from mongo to mongodb extension + php-library.

**Comment by mbretter** [comment]
I could workaround this problem by implementing the \MongoDB\BSON\Persistable interface for my data objects. 
I'm converting the mongodb objects to php datatypes and vice-versa.
\MongoDB\BSON\ObjectID is converted to a plain string, \MongoDB\BSON\UTCDatetime to native PHP DateTime objects. 
\MongoDB\Client() is created with a typemap of
['typeMap' => ['root' => 'MongoDB\Model\BSONDocument', 'document' => 'array', 'array' => 'array']]
This has the advantage of geting back PHP objects when fetching rows, because the driver stores the PHP classname in the __pclass attribute.

**Comment by vingrad** [comment]
Can you please fix this problem?

**Comment by lindelius** [comment]
@vingrad Please read the entire conversation. The are working on fixing this, and you can follow the progress via https://jira.mongodb.org/browse/PHPC-460.

**Comment by jmikola** [comment]
To quote my reply from https://github.com/mongodb/mongo-php-driver/issues/270#issuecomment-230503884

> In-progress PR is: https://github.com/mongodb/mongo-php-driver/pull/340
>
> I'll be working on this over the coming week and expect to review it with Derick during the week of July 11. While the functionality is slated for 1.2.0, we will consider an alpha release to get the functionality out there before waiting for other 1.2.0 features.

**Comment by jmikola** [comment]
Quoting my second reply in https://github.com/mongodb/mongo-php-driver/issues/270#issuecomment-233600238:

> mongodb/mongo-php-driver#340 was merged to master last week; however, some Windows build issues are holding up an alpha release. I wouldn't expect an alpha before the week of July 25th.
> 
> If you urgently need serialization support I would suggest building from master using [these instructions](http://php.net/manual/en/mongodb.installation.manual.php).

**Comment by jmikola** [comment]
[1.2.0alpha1](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha1) has been released.

**Comment by awatansa** [comment]
Hi, I got the Same problem, I formatted my PC and reinstalled everything but `php_mongodb.dll` file was older one.
**Possible Solution**
I Changed that driver to the latest one and the problem was solved, maybe this will help. Try it.
