### ISSUE TITLE
Using $not and $in in find together

### ISSUE THREAD

**Issue by clintcan** [mongodb/mongo-php-library#154]
Hi all,
I tried using this as my query (I'm new to querying in mongodb):
$query = array(
     "field1" => array('$in' => array(1,2,3)),
     "field2" => array('$not' => 'value')
);
The results returned still returns the document with field2 as that value (the first operation works as expected).  Is there anything that needs to be changed here?
Thanks

**Comment by alcaeus** [comment]
According to [the manual](https://docs.mongodb.org/manual/reference/operator/query/not/), the `$not` operator:
> only affects other operators and cannot check fields and documents independently. So, use the $not operator for logical disjunctions and the $ne operator to test the contents of fields directly.

I believe you're looking for the `$ne` operator:
```
$query = array(
    "field1" => array('$in' => array(1,2,3)),
    "field2" => array('$ne' => 'value')
);
```
