### ISSUE TITLE
BSONDocument doesn't accept an object in its constructor

### ISSUE THREAD

**Issue by garak** [mongodb/mongo-php-library#1549]
It should accept it, to be consistent with its parent

**Comment by GromNaN** [comment]
Indeed, you can cast your object into an array.
```php
$object = new stdClass;
$object->foo = 'bar';
$document = new BSONDocument((array) $object);
var_dump($document->foo); // "bar"
```

But we should accept objects, at least plain instances of `stdClass`. It that the type of object you want to pass?

**Comment by garak** [comment]
> But we should accept objects, at least plain instances of `stdClass`. It that the type of object you want to pass?

Exactly, I have an object coming from `json_decode` and can use it directly in an old version of this library. But I can't upgrade because of the type hint currently applied.

**Comment by garak** [comment]
Is there any chance to see this fix in a release soon?

**Comment by GromNaN** [comment]
Yes, it's iminent. There's a lot in this release.

**Comment by bisht2050** [comment]
1.21 with the required changes is released.
