### ISSUE TITLE
Can I use php driver mongo.so 1.6 to connect MongDB 3.2

### ISSUE THREAD

**Issue by haikuoyao** [mongodb/mongo-php-library#156]
Can I use php driver mongo.so 1.6 to connect MongDB 3.2 ?

It works well on my server but mongo docs say MongDB 3.2 doesn't support mongo.so 1.6.
It supports mongodb.so 1.1.

It just t doesn't support new features , right ?

**Comment by jmikola** [comment]
The [legacy `mongo` extension](https://github.com/mongodb/mongo-php-driver-legacy) should be usable with MongoDB 3.2; however, new features will not be supported (e.g. upcoming BSON types, the [`find` command](https://docs.mongodb.org/manual/reference/command/find/)).

Also, this GitHub repository is for the userland library, which runs the `mongodb` extension for PHP and HHVM. It is not the appropriate forum for questions about the legacy driver. In the future, please use one of the [community support](https://docs.mongodb.org/manual/support/#community-support) channels or open an issue in the [PHP](https://jira.mongodb.org/browse/PHP) project in JIRA.

Cross-referencing with an existing mailing list thread on the subject: https://groups.google.com/d/msg/mongodb-user/rnjirty9D_0/klS_8RRPEQAJ
