### ISSUE TITLE
cursor's explain() and statistics

### ISSUE THREAD

**Issue by thiagodp** [mongodb/mongo-php-library#162]
Is there a way to get some statistics about executed commands or queries? In the legacy driver, the MongoCursor class had an explain() method. In the new driver, I could not find such method in the new classes.

**Comment by jmikola** [comment]
This is an outstanding feature that we're tracking in [PHPLIB-156](https://jira.mongodb.org/browse/PHPLIB-156). We punted on implementing this in 1.0 as it the API was pulled from the [CRUD specification](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst) and we were hoping to wait until we had a cross-driver API specification before rolling our own. For the time being, you can use one of the two methods below.

If you are talking to a 3.0+ server, you'll want to use the [`explain` command](https://docs.mongodb.org/manual/reference/command/explain). The manual page should have examples on how to structure that command.

Older versions of the server should include the [`$explain` query modifier](https://docs.mongodb.org/v3.0/reference/operator/meta/explain/#metaOp._S_explain), which will cause the query to return a single document. In this case, it makes sense to use `Collection::findOne()` to access the explain result easily, unless you want to iterate once on the Cursor returned by `find()` and pull the document yourself. For example:

```
$collection = (new MongoDB\Client)->test->foo;
$explain = $collection->findOne(['x' => 1], ['modifiers' => ['$explain' => true]]);

var_dump($explain);
```

When [PHPLIB-156](https://jira.mongodb.org/browse/PHPLIB-156) is implemented, the helper method in the library will certainly provide a single API (e.g. `Collection::explain()`) and take care of version checking internally.

**Comment by thiagodp** [comment]
Thank you! I look forward to the issues 156 and 172 in the PHPLIB. In the meantime, I'll try to use the feature as explained. ;)

**Comment by escopecz** [comment]
Unfortunately, the method for 3.0+ server doesn't work. I have version 3.4.9. 

I tried this:
```
$this->database->command(
    [
        'explain' => [
            'count' => 'emails',
            'query' => $query,
        ],
        'verbosity' => 'queryPlanner',
    ]
)
```

This will return error message: `unknown operator: $explain`

This is an example from the docs linked above to compare with my syntax:
```
db.runCommand(
   {
     explain: { count: "products", query: { quantity: { $gt: 50 } } },
     verbosity: "queryPlanner"
   }
)
```

If you're wondering if all the variables above are correct, this return the right count, it just takes ages and that's why I'm searching for a way to see under the hood with explain:
```
$this->database->emails->count($query)
```

Any suggestions how to get explain info another way?
