### ISSUE TITLE
Using insertOne to create an auto-incremental field

### ISSUE THREAD

**Issue by dugajean** [mongodb/mongo-php-library#163]
I did not find any documentation of this library explaining how to create an auto-incrementing field via the `insertOne` method.

I have a method like this one:
```
public function create($collection, $data)
{
    $collection = $this->db->{$collection};
    return $collection->insertOne($data);
}
```

And I use it like this:
```
$mongodb = new MongoDB_Plugin('databaseName');

$mongodb->create($myCollection, [
    'field_value' => $fieldValue, 
    'offer_id' => $offerData['id'],
    'offer_field_id' => $fieldId,
    'session_id' => post('session_id', 'is_safe'),
    'created_at' => date(config('default_date_format'));
]);
```

What is the way to create an auto-incrementing field with this method?

Thanks!

**Comment by jmikola** [comment]
I would recommend reading [Create an Auto-Incrementing Sequence Field](https://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/) in the MongoDB manual for a tutorial on the subject. This requires tracking the sequence in a separate document (and preferably a separate collection as well).

A similar question was also asked in https://github.com/mongodb/mongo-php-library/issues/161#issuecomment-213465649. See my response there for additional context and a reference to how Doctrine MongoDB ODM implements the feature.

**Comment by lindelius** [comment]
This question can probably be closed now
