### ISSUE TITLE
query dbref filter

### ISSUE THREAD

**Issue by boonkerz** [mongodb/mongo-php-library#164]
is it possible to find documents based on dbref filter?

in mongo it self with:
db.getCollection('messages').find({'user.$id': ObjectId("56d4ba0880f59017008b4567")})

but how can i do this with php?

**Comment by jmikola** [comment]
The shell example you shared would translate to the following query in the PHP library:

```
$db->messages->find(['user.$id' => new MongoDB\BSON\ObjectId('56d4ba0880f59017008b4567')]);
```
