### ISSUE TITLE
InsertMany caused BulkWriteException with unique key index

### ISSUE THREAD

**Issue by litan1106** [mongodb/mongo-php-library#165]
InsertMany causes BulkWriteException with unique key index but InsertOne works fine.

           $collection->insertMany($bArray);
            // Create a unique index on the RowId field
            $collection->createIndex(['RowId' => 1], ['unique' => true]);

--------------------------------------------------------------------------------------------------

            $collection->insertOne($dArray);
            // Create a unique index on the AccountId field
            $collection->createIndex(['AccountId' => 1], ['unique' => true]);

**Comment by litan1106** [comment]
I guess I will try and catch the error for now.

I also customized the _id instead of using the unique index keys.

**Comment by jmikola** [comment]
@litan1106: Did you conclude that this was purely an application error or do you still suspect there is an issue with the library/driver? If the latter, I'd be interested in diagnosing it further.

Can you share the write and write concern errors from the BulkWriteException's WriteResult (obtained via [`BulkWriteException::getWriteResult()`](http://php.net/manual/en/mongodb-driver-writeexception.getwriteresult.php))? A `var_dump()` of return values from [`WriteResult::getWriteErrors()`](http://php.net/manual/en/mongodb-driver-writeresult.getwriteerrors.php) and [`WriteResult::getWriteConcernError()`](http://php.net/manual/en/mongodb-driver-writeresult.getwriteconcernerror.php) would suffice.

From your original post and reply, it wasn't clear to me if the unique key conflict was on `_id`, `RowId`, or `AccountId`. In the `insertMany()` example, it looks like you were creating the index after inserting documents, so I would expect an error for conflicting `RowId` values to be reported when you attempt to create the index.

Lastly, it would be helpful for you to share the contents of the collection and the arguments you were passing `insertMany()` and `insertOne()`.

**Comment by litan1106** [comment]
BulkWriteException {#618
  #message: "E11000 duplicate key error index: example.1234567890_ACCOUNT_2016-04-14_2016-04-27.$_id_ dup key: { : "1234567890_2" }"
  #code: 0
  #file: "/home/vagrant/Codes//vendor/mongodb/mongodb/src/Operation/InsertMany.php"
  #line: 116
  #writeResult: WriteResult {#617}
  -trace: {
    65. MongoDB\Driver\Server->executeBulkWrite() ==> new MongoDB\Driver\Exception\BulkWriteException(): {
      src: {
        /home/vagrant/Codes/vendor/mongodb/mongodb/src/Operation/InsertMany.php:116: """
                  $writeConcern = isset($this->options['writeConcern']) ? $this->options['writeConcern'] : null;\n
                  $writeResult = $server->executeBulkWrite($this->databaseName . '.' . $this->collectionName, $bulk, $writeConcern);\n
          \n
          """
      }
    }
    64. MongoDB\Operation\InsertMany->execute() ==> MongoDB\Driver\Server->executeBulkWrite(): {
      src: {
        /home/vagrant/Codes/vendor/mongodb/mongodb/src/Operation/InsertMany.php:116: """
                  $writeConcern = isset($this->options['writeConcern']) ? $this->options['writeConcern'] : null;\n
                  $writeResult = $server->executeBulkWrite($this->databaseName . '.' . $this->collectionName, $bulk, $writeConcern);\n
          \n
          """
      }
      args: array:3 [
        0 => "1234567890_ACCOUNT_2016-04-14_2016-04-27"
        1 => BulkWrite {#615}
        2 => WriteConcern {#466}
      ]
    }
    63. MongoDB\Collection->insertMany() ==> MongoDB\Operation\InsertMany->execute(): {
      src: {
        /home/vagrant/Codes/vendor/mongodb/mongodb/src/Collection.php:611: """
          \n
                  return $operation->execute($server);\n
              }\n
          """
      }

      args: array:1 [
        0 => array:84 [
          0 => array:15 [
            "_id" => "1234567890_2"
            "AccountId" => "1234567890"
            "Day" => "2016-04-15"
            "Network" => "Search Network"
            "Cost" => 13400000
            "Clicks" => 5
            "Impressions" => 38
            "CTR" => "13.16"
            "AvgCPC" => 2680000
            "AvgCPM" => 352631579
            "AvgPosition" => 2.2
            "ConvertedClicks" => 0
            "Device" => "Mobile devices with full browsers"
          ]
          1 => array:15 [
            "_id" => "1234567890_3"
            "AccountId" => "1234567890"
            "Day" => "2016-04-25"
            "Network" => "Display Network"
            "Cost" => 0
            "Clicks" => 0
            "Impressions" => 20
            "CTR" => "0.00"
            "AvgCPC" => 0
            "AvgCPM" => 0
            "AvgPosition" => 1.0
            "ConvertedClicks" => 0
            "Device" => "Tablets with full browsers"
          ]
          2 => array:15 [
            "_id" => "1234567890_4"
            "AccountId" => "1234567890"
            "Day" => "2016-04-23"
            "Network" => "Display Network"
            "Cost" => 0
            "Clicks" => 0
            "Impressions" => 7
            "CTR" => "0.00"
            "AvgCPC" => 0
            "AvgCPM" => 0
            "AvgPosition" => 1.0
            "ConvertedClicks" => 0
            "Device" => "Computers"
          ]
          3 => array:15 [
            "_id" => "1234567890_5"
            "AccountId" => "1234567890"
            "Day" => "2016-04-27"
            "Network" => "Search Network"
            "Cost" => 10580000
            "Clicks" => 4
            "Impressions" => 117
            "CTR" => "3.42"
            "AvgCPC" => 2645000
            "AvgCPM" => 90427350
            "AvgPosition" => 2.6
            "ConvertedClicks" => 0
            "Device" => "Computers"
          ]

**Comment by jmikola** [comment]
According to that last paste, there is already a document with `_id` "1234567890_2" in the 
`example.1234567890_ACCOUNT_2016-04-14_2016-04-27` collection at the time you're calling `insertMany()`.  Is that correct?

If so, the exception would be expected.

**Comment by litan1106** [comment]
Correct, I thought it would skip it since it's unique id.

**Comment by umntkid** [comment]
I have it with ` $this->_collection->insertMany($statuses, ['ordered' => false]);` but still throwning exception

**Comment by jmikola** [comment]
$m = new MongoDB\Driver\Manager;
$c = new MongoDB\Driver\Command(['dropDatabase' => '1']);
try { $m->executeCommand('test', $c); } catch (Exception $e) {}
@umntkid: `['ordered' => false]` does not mean that the driver will not still throw exceptions for unique key violations. It only determines whether the bulk write operation should continue after the first error is encountered. Consider:

```
<?php

$m = new MongoDB\Driver\Manager;
$c = new MongoDB\Driver\Command(['dropDatabase' => 1]);
$m->executeCommand('test', $c);

$b = new MongoDB\Driver\BulkWrite(['ordered' => false]);
$b->insert(['_id' => 1]);
$b->insert(['_id' => 1]);
$b->insert(['_id' => 1]);

try {
    $m->executeBulkWrite('test.foo', $b);
} catch (MongoDB\Driver\Exception\BulkWriteException $e) {
    var_dump($e->getWriteResult());
}
```

This should yield something similar to:

```
object(MongoDB\Driver\WriteResult)#4 (9) {
  ["nInserted"]=>
  int(1)
  ["nMatched"]=>
  int(0)
  ["nModified"]=>
  int(0)
  ["nRemoved"]=>
  int(0)
  ["nUpserted"]=>
  int(0)
  ["upsertedIds"]=>
  array(0) {
  }
  ["writeErrors"]=>
  array(2) {
    [0]=>
    object(MongoDB\Driver\WriteError)#6 (4) {
      ["message"]=>
      string(76) "E11000 duplicate key error collection: test.foo index: _id_ dup key: { : 1 }"
      ["code"]=>
      int(11000)
      ["index"]=>
      int(1)
      ["info"]=>
      NULL
    }
    [1]=>
    object(MongoDB\Driver\WriteError)#7 (4) {
      ["message"]=>
      string(76) "E11000 duplicate key error collection: test.foo index: _id_ dup key: { : 1 }"
      ["code"]=>
      int(11000)
      ["index"]=>
      int(2)
      ["info"]=>
      NULL
    }
  }
  ["writeConcernError"]=>
  NULL
  ["writeConcern"]=>
  object(MongoDB\Driver\WriteConcern)#8 (0) {
  }
}
```

If you still feel that you're experiencing a bug, please open a new ticket instead of following up in this closed thread.

**Comment by lindelius** [comment]
@jmikola The [`MongoDB\Collection::bulkWrite()` documentation](https://docs.mongodb.com/php-library/master/reference/method/MongoDBCollection-bulkWrite/) should make this clear. It should probably specifically say that a `BulkWriteException` will be thrown in either case.

**Comment by jmikola** [comment]
@lindelius: Just created [PHPLIB-246](https://jira.mongodb.org/browse/PHPLIB-246) to track that.
