### ISSUE TITLE
UTCDateTime not being stored properly?

### ISSUE THREAD

**Issue by zachrattner** [mongodb/mongo-php-library#169]
What is the proper way to save a field with the `Date` type in MongoDB? From the docs, it seems [MongoDB\BSON\UTCDateTime](http://php.net/manual/en/class.mongodb-bson-utcdatetime.php) should be used since [MongoDB\BSON\Timestamp](http://php.net/manual/en/class.mongodb-bson-timestamp.php) "is an internal MongoDB type not intended for general date storage"

However, when I try to save `UTCDateTime` objects, they don't seem to be recorded properly in the database. 

```
// Create a new date object
$time = new MongoDB\BSON\UTCDateTime(date('U'));

// Dump it to make sure the timestamp is correct
var_dump($time);
object(MongoDB\BSON\UTCDateTime)#26 (1) {
  ["milliseconds"]=>
  int(1462464292)
}

// Bundle the value into a document
$doc = 
[
    'somefield' => 'some value',
    'sometime'  => $time
];

// Save the document
$w = new MongoDB\Driver\BulkWrite();
$w->insert($doc);
$mgr->executeBulkWrite('namespace', $w);
```

Now, when I view the timestamp in MongoDB, it's garbage:
`ISODate("1970-01-17T22:14:24.219Z")`

**Comment by zachrattner** [comment]
Nevermind, was storing seconds as milliseconds. Move along, nothing to see here :D

**Comment by moderndeveloperllc** [comment]
`date(U)` just gives you seconds, and `UTCDateTime` is milliseconds. It just sees the integer you passed in Jan 17th is that number of milliseconds since the epoch beginning. Here is the current way to do it properly:
```
$msec = floor(microtime(true) * 1000);
$time = new MongoDB\BSON\UTCDateTime($msec);
```

**Comment by jmikola** [comment]
On a related note, UTCDateTime's constructor will start defaulting to the current time in 1.2.0 (see: [PHPC-536](https://jira.mongodb.org/browse/PHPC-536)).
