### ISSUE TITLE
compile error with php7.0

### ISSUE THREAD

**Issue by eelco2k** [mongodb/mongo-php-library#170]
I'm having some compile errors when trying to compile mongodb php driver for php-7.0 in Debian GNU/Linux stretch/sid.

I cannot use: "pecl install mongodb" because phpize is using my php5 config settings.

I downloaded mongodb-1.1.6. like so:

```
wget http://pecl.php.net/get/mongodb-1.1.6.tgz
tar -zxvf mongodb-1.1.6.tgz
cd mongodb-1.1.6
/usr/local/php7/bin/phpize
./configure --with-php-config=/usr/local/php7/bin/php-config --prefix=/usr/lib/php/
make && make install
```

after a while i'm getting these errors... (error's below I used version 1.1.1 but 1.1.6 gives me same errors)

```
mkdir .libs
 cc -I. -I/tmp/mongodb-1.1.6 -DPHP_ATOM_INC -I/tmp/mongodb-1.1.1/include -I/tmp/mongodb-1.1.1/main -I/tmp/mongodb-1.1.1 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -I/usr -I/tmp/mongodb-1.1.1/src/BSON/ -I/tmp/mongodb-1.1.1/src/MongoDB/ -I/tmp/mongodb-1.1.1/src/MongoDB/Exception/ -I/tmp/mongodb-1.1.1/src/contrib/ -I/tmp/mongodb-1.1.1/src/libmongoc/src/mongoc/ -I/tmp/mongodb-1.1.1/src/libbson/src/ -I/tmp/mongodb-1.1.1/src/libbson/src/yajl/ -I/tmp/mongodb-1.1.1/src/libbson/src/bson/ -DBSON_COMPILATION -DMONGOC_COMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H -g -O2 -pthread -c /tmp/mongodb-1.1.1/php_phongo.c  -fPIC -DPIC -o .libs/php_phongo.o
In file included from /tmp/mongodb-1.1.1/php_phongo.c:68:0:
/tmp/mongodb-1.1.1/php_phongo.c: In function ‘php_phongo_log’:
/tmp/mongodb-1.1.1/php_phongo.h:58:25: warning: implicit declaration of function ‘ZEND_MODULE_GLOBALS_ACCESSOR’ [-Wimplicit-function-declaration]
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                         ^
/tmp/mongodb-1.1.1/php_phongo.c:216:12: note: in expansion of macro ‘MONGODB_G’
    fprintf(MONGODB_G(debug_fd), "[%s] %10s: %-8s> %s\n", phongo_str(dt), log_domain, m
            ^
/tmp/mongodb-1.1.1/php_phongo.h:58:54: error: ‘mongodb’ undeclared (first use in this function)
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                      ^
/tmp/mongodb-1.1.1/php_phongo.c:216:12: note: in expansion of macro ‘MONGODB_G’
    fprintf(MONGODB_G(debug_fd), "[%s] %10s: %-8s> %s\n", phongo_str(dt), log_domain, m
            ^
/tmp/mongodb-1.1.1/php_phongo.h:58:54: note: each undeclared identifier is reported only once for each function it appears in
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                      ^
/tmp/mongodb-1.1.1/php_phongo.c:216:12: note: in expansion of macro ‘MONGODB_G’
    fprintf(MONGODB_G(debug_fd), "[%s] %10s: %-8s> %s\n", phongo_str(dt), log_domain, m
            ^
/tmp/mongodb-1.1.1/php_phongo.c:216:22: error: ‘debug_fd’ undeclared (first use in this function)
    fprintf(MONGODB_G(debug_fd), "[%s] %10s: %-8s> %s\n", phongo_str(dt), log_domain, m
                      ^
/tmp/mongodb-1.1.1/php_phongo.h:58:63: note: in definition of macro ‘MONGODB_G’
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                               ^
/tmp/mongodb-1.1.1/php_phongo.c: In function ‘OnUpdateDebug’:
/tmp/mongodb-1.1.1/php_phongo.h:58:54: error: ‘mongodb’ undeclared (first use in this function)
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                      ^
/tmp/mongodb-1.1.1/php_phongo.c:2279:6: note: in expansion of macro ‘MONGODB_G’
  if (MONGODB_G(debug_fd)) {
      ^
/tmp/mongodb-1.1.1/php_phongo.c:2279:16: error: ‘debug_fd’ undeclared (first use in this function)
  if (MONGODB_G(debug_fd)) {
                ^
/tmp/mongodb-1.1.1/php_phongo.h:58:63: note: in definition of macro ‘MONGODB_G’
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                               ^
/tmp/mongodb-1.1.1/php_phongo.c: In function ‘zm_startup_mongodb’:
/tmp/mongodb-1.1.1/php_phongo.h:58:54: error: ‘mongodb’ undeclared (first use in this function)
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                      ^
/tmp/mongodb-1.1.1/php_phongo.c:2390:23: note: in expansion of macro ‘MONGODB_G’
  bson_mem_set_vtable(&MONGODB_G(bsonMemVTable));
                       ^
/tmp/mongodb-1.1.1/php_phongo.c:2390:33: error: ‘bsonMemVTable’ undeclared (first use in this function)
  bson_mem_set_vtable(&MONGODB_G(bsonMemVTable));
                                 ^
/tmp/mongodb-1.1.1/php_phongo.h:58:63: note: in definition of macro ‘MONGODB_G’
 #   define MONGODB_G(v) ZEND_MODULE_GLOBALS_ACCESSOR(mongodb, v)
                                                               ^
Makefile:599: recipe for target 'php_phongo.lo' failed
```

**Comment by jmikola** [comment]
> ```
> ./configure --with-php-config=/usr/local/php7/bin/php-config --prefix=/usr/lib/php/
> ```

Are those argument necessary? I would think that PHP 7's `phpize` would set the appropriate path defaults. The lack of `ZEND_MODULE_GLOBALS_ACCESSOR()` tells me that you're building with PHP 5 includes, despite `PHP_VERSION_ID` indicating 7.0+ when compiling the extension.

As a side note: This repository is specific to the userland library. In the future, please open extension-related issues on either the [mongo-php-driver](https://github.com/mongodb/mongo-php-driver) repository or [PHPC](https://jira.mongodb.org/browse/PHPC) project in JIRA.

**Comment by eelco2k** [comment]
hi Jmikola, 
when i don't use the --with-php-config and --prefix variables it uses /usr/bin/phpize which should be correct but then it detects php5 instead of php7 . so it installs the libraries in:
 Installing shared extensions:     /usr/lib/php5/20131226/  which is not correct.

/usr/bin/phpize:
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226

/usr/local/php7/bin/phpize
Configuring for:
PHP Api Version:         20131218
Zend Module Api No:      20141001
Zend Extension Api No:   320140815

how can i configure the compile as such that it uses php7?

**Comment by eelco2k** [comment]
I will create an issue in the mongo-php-driver repo as well.

**Comment by jmikola** [comment]
On my local machine, I have multiple versions of PHP available within my `~/bin` directory, which I switch between via a shell script that puts a particular version first in my shell `$PATH` (this is documented in a [blog post](http://jmikola.net/blog/php-build-script/)). I attempted to reproduce your issue by activating 5.6 and then building for PHP 7.0:

```
/home/jmikola/bin/php-bin/php-7.0/bin/phpize
./configure --with-php-config=/home/jmikola/bin/php-bin/php-7.0/bin/php-config
```

The configure script includes the following in its output:

> checking PHP version... 70005

From there, `make all && make install` works just fine and yields the following:

> Installing shared extensions:     /home/jmikola/bin/php-bin/php-7.0/lib/php/extensions/debug-non-zts-20151012/

If I had to guess, your issue is due to `--prefix=/usr/lib/php/`. Try removing that and see if the configuration and build succeeds.

**Comment by eelco2k** [comment]
hi jmikola,

unfortunately without the `--prefix=/usr/lib/php/` I still get the build errors. 
in my build output php version is: `checking PHP version... 70000`

for now i guess this is working for me:
`apt-get install php-mongodb`
which uses version: (1.1.6-3)

When checking `php -m | grep mongo` it shows: `mongodb` so i guess the extension is working.
