### ISSUE TITLE
exception 'MongoDB\Driver\Exception\AuthenticationException' with message 'Authentication failed.'

### ISSUE THREAD

**Issue by liujingyu** [mongodb/mongo-php-library#171]
$client = new MongoDB\Client("mongodb://localhost:27017/database", ['username' => 'user', 'password' => 'passwd', 'db' => 'admin']);

manual: http://mongodb.github.io/mongo-php-library/api/source-class-MongoDB.Client.html#15-167

**Comment by jmikola** [comment]
If you are expecting to authenticate against the "admin" database, I would suggest removing both `"/database"` from the URI string and the `db` key from the options. The driver already defaults to authenticate against the "admin" database. If you do wish to specify a different database, you can either do so via the URI string (where you're currently indicating that you want to auth against the database named "database") or the `authSource` option (specified as either a query string parameter in the URI string or via the options array).

I realize this does differ from the legacy driver's [MongoClient](http://php.net/manual/en/mongoclient.construct.php) constructor options, where we previously accepted a `"db"` option. The driver and library documentation for [MongoDB\Driver\Manager](http://php.net/manual/en/mongodb-driver-manager.construct.php) and [MongoDB\Client](http://mongodb.github.io/mongo-php-library/classes/client/#__construct), respectively, now refer to the [Connection string documentation](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format), which I cite below.

----

> **/database**: Optional. The name of the database to authenticate if the connection string includes authentication credentials in the form of `username:password@`. If `/database` is not specified and the connection string includes credentials, the driver will authenticate to the admin database.

Source: [Standard Connection String Format](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format).

> **authSource**: Specify the database name associated with the user’s credentials, if the users collection do not exist in the database where the client is connecting. authSource defaults to the database specified in the connection string.
>
> MongoDB will ignore authSource values if the connection string specifies no user name.

Source: [Authentication Options](https://docs.mongodb.com/manual/reference/connection-string/#authentication-options).

In your case, you are specifying a username via the array options, so you need not worry about the last line of the `authSource` docs (if you decide to use that option).

**Comment by lindelius** [comment]
I actually did the same thing at first when I was going from the legacy driver to the new one. However, with the relatively new changes to the documentation (and the link to the MongoDB docs) it's pretty clear what options are available. So, I'm pretty sure this issue can be closed now.

**Comment by kahovn** [comment]
I have the problem with mongo verion 3.4.9
No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '{IP:27017']

Please me give advanace

**Comment by jmikola** [comment]
@kahovn: Please keep the conversation to [PHPC-1025](https://jira.mongodb.org/browse/PHPC-1025), which I moved over from the original issue you opened on the SERVER project. "No suitable servers found" is a very generic error that only implies that the driver was unable to select a server based on its view of the topology. The actual cause for that failure can be very different case to case.
