### ISSUE TITLE
Suggestion to Provide Access to `WriteResult` in `*Result` Classes

### ISSUE THREAD

**Issue by rbchasesc** [mongodb/mongo-php-library#173]
The various `*Result` classes, `Insert[Many|One]Result`, `DeleteResult`, `UpdateResult`, etc., store the underlying `WriteResult` object in the class in a private variable, but don't provide a `getWriteResult` method to access it. This prevents access to the `WriteResult` `get*Count` methods for cross checking expected outcomes of insert/update operations. For example, in `DeleteResult` you can call the `getDeletedCount` to find out the number of records deleted, but you do not have access to the `WriteResult`'s `getMatchedCount` to determine if the two match or match the expectations of your calling code. Suggest adding a `getWriteResult` method to each of the `*Result` classes:

```
    /**
     * Gets the WriteResult object that was used to create this class instance.
     *
     * @return \MongoDB\Driver\WriteResult
     */
    public function getWriteResult()
    {
        return $this->writeResult;
    }
```

I've actually done this in a couple cases, `DeleteResult` and `UpdateResult` and it has proven very helpful, but I cannot persist _our_ customization of this library and hope for easy maintenance of this public library in our environment.

Thanks for your consideration.

**Comment by jmikola** [comment]
> For example, in DeleteResult you can call the getDeletedCount to find out the number of records deleted, but you do not have access to the WriteResult's getMatchedCount to determine if the two match or match the expectations of your calling code.

In what cases would the underlying WriteResult report non-zero values for anything other than `getDeletedCount()`? The `Insert[Many|One]Result`, `DeleteResult`, and `UpdateResult` classes are only used by the respective single-type CRUD methods in `MongoDB\Collection`, so I'd consider it a bug (in either the library, driver, or server) if some other operations snuck into there (or were reported in the result).

The write result classes in the library are derived from our cross-driver [CRUD specification](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst) and purposefully only have relevant fields. As such, only the `BulkWriteResult` class (returned via `Collection::bulkWrite()`) provides access to all of the `MongoDB\Driver\WriteResult` getters. From the library's perspective, `MongoDB\Driver\WriteResult` is purely an internal, implementation detail.

**Comment by rbchasesc** [comment]
It's less about a difference between `WriteResult->getMatchedCount()`  `DeleteResult->getDeletedCount()` and more about the calling code's need to verify its expectations were met relative to the code that lead to the delete call.

For example:
The calling code executes a query and other logic in order to determine that 150 records need to be deleted, but, due to the execution time of the client code between the query and potentially other activity or similar delete activity against the data in a high traffic system, the remove only matches 140 and deletes 140. Although those two numbers may be okay because they match, they don't meet the caller's expectation of 150. This may be either a legitimate outcome or and unexpected behavior. With only the ability to say we deleted 140 but the calling code expects 150, this could only safely be deemed an error. However, with the addition of the ability to cross check the discrepancy against the matched count, the client code is given the ability to decide if the outcome is favorable or in error based on its business needs.

**Comment by lindelius** [comment]
MongoDB doesn't report a "matched count" for delete operations (see [the MongoDB WriteResult documentation](https://docs.mongodb.com/manual/reference/method/db.collection.remove/#writeresults-remove)).

> The remove() returns a WriteResult object that contains the status of the operation. Upon success, the WriteResult object contains information on the number of documents removed

**Comment by jmikola** [comment]
Closing this, as I believe @lindelius addressed the misunderstanding. The server only reports the number of deleted documents. The matched and modified counts are specific to update operations. Their getters exist on the BulkWriteResult library class and WriteResult extension class because bulk write operations may included a mix of inserts, updates, and deletes.

**Comment by fellars** [comment]
So, how would I get access to the getWriteErrors() on the underlying writeResult of an updateResult?  I would agree unless you add wrappers for all functions on the WriteResult then you need to make that variable accessible.

**Comment by jmikola** [comment]
@fellars: In the event of a write concern error or one or more write errors, the driver will throw a BulkWriteException, which has a [getWriteResult()](http://php.net/manual/en/mongodb-driver-writeexception.getwriteresult.php) method.

The library currently does not abstract the driver's write exceptions, although we may do so down the line for https://github.com/mongodb/mongo-php-library/issues/261 (tracked in [PHPLIB-225](https://jira.mongodb.org/browse/PHPLIB-225)). At that point, the library exception will also have an accessor method for either the underlying write result or the errors directly.

**Comment by fellars** [comment]
gotcha @jmikola . makes sense.

thanks
