### ISSUE TITLE
I have mongo.so but still not installing.

### ISSUE THREAD

**Issue by kazi-mainuddin-ahmed** [mongodb/mongo-php-library#174]
I have old depricated mongo.so not mongodb.so. So mongo db is installed but still not able to install it.

**Comment by alcaeus** [comment]
You need to install mongodb.so in order to use mongo-php-library. It is not compatible with the old legacy driver.

**Comment by jmikola** [comment]
Closing this, as @alcaeus answered the question. This library requires [ext-mongodb](https://pecl.php.net/package/mongodb), not [ext-mongo](https://pecl.php.net/package/mongo).
