### ISSUE TITLE
problem with listIndexes

### ISSUE THREAD

**Issue by TaunT** [mongodb/mongo-php-library#176]
Hi! 
**collection->listIndexes** always returns empty object
MongoDB\Model\IndexInfoIteratorIterator Object ()

I created index with **collection->createIndex** and got valid answer with new index name, but still don't  see list of indexes for collection

**Comment by TaunT** [comment]
Documents doesn't have information about the receipt of the index object using ->current
I found this myself

**Comment by jmikola** [comment]
I see you closed this shortly after opening. Did you ultimately resolve a problem with your own code, or is there an outstanding issue in the library?

**Comment by TaunT** [comment]
I realized myself that it is necessary to call functions (such as getName) with received objects
it would be good to do a little more examples and documentation :)

**Comment by jmikola** [comment]
> it would be good to do a little more examples and documentation :)

Thanks for the feedback. I'll make a note of that. :+1:

**Comment by jmikola** [comment]
Sorry for losing track of this. I've opened [PHPLIB-278](https://jira.mongodb.org/browse/PHPLIB-278) to track the documentation improvement.
