### ISSUE TITLE
Find() twice - Magic document duplication :)

### ISSUE THREAD

**Issue by RobIsHere** [mongodb/mongo-php-library#177]
```php
$oldCol = $client->selectCollection("editor1", $collectionName);
foreach ($oldCol->find() as $oldDoc)
{
    if ((string)$oldDoc["_id"] == "56c1954188a6888aed888e78")
    {
        echo "56c1954188a6888aed888e78\n";
    }
}
```

```
root@rob:/var/apps# php migratedata.php 
56c1954188a6888aed888e78
56c1954188a6888aed888e78
```

The last document appears twice.

**Comment by moderndeveloperllc** [comment]
Can you provide the data you are using to populate the `editor1` collection? What does a `var_dump()` of `$oldDoc` look like (assuming you aren't listing 500 docs :-) ?

**Comment by moderndeveloperllc** [comment]
Understood, just trying to help because I don't get that error at all.

1. Is `$oldDoc` an array or object?
2. What versions of the library and driver?
3. Does doing a `db.collection.find()` for that ID give you one or two outputs?

**Comment by RobIsHere** [comment]
```
root@rob:/var/apps# php -v
PHP 7.0.6-12+donate.sury.org~xenial+4 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
root@rob:/var/apps# php -v --ri mongodb
PHP 7.0.6-12+donate.sury.org~xenial+4 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

I'm using array transforms, so the document is retrieved as an array. Everything looks ok.
```
$client = new \MongoDB\Client(null, [], ['typeMap' => ['root' => 'array', 'document' => 'array', 'array' => 'array']]);
```

I checked on mongo js console. The document is stored only once. You can relax, it's not the database storing the same _id twice ;)
Also gives "1":
```
$test = $oldCol->find(["_id" => new \MongoDB\BSON\ObjectId("56c1954188a6888aed888e78")]);
echo "Count: ".count($test);
```

Maybe some weired problem with the iterator not stepping forward?
Things like these worked on the old driver with almost the same data.

**Comment by RobIsHere** [comment]
MongoDB is Version 3.2.6 btw.

**Comment by moderndeveloperllc** [comment]
I'm out of ideas. I guess we get to wait till @jmikola can help.

**Comment by lindelius** [comment]
What does the surrounding code look like? Is the code snippet you posted called from somewhere else and perhaps run twice for some reason? I once had to debug a similar problem, and the cause of that one was some weird lines in the `.htaccess` file that made the script run twice.

If you haven't already tried, does it still output the ID twice if you move that code snippet to a new, empty php file and run that?

**Comment by alcaeus** [comment]
@RobIsHere could you please run the following queries in your MongoDB shell for me please?

```
db.yourCollectionName.count({_id: '56c1954188a6888aed888e78'})
db.yourCollectionName.count({_id: ObjectId('56c1954188a6888aed888e78')})
```

Since you are casting the ID to string it could be that these are two different documents: one with an ObjectID, one with a string as an ID; hence the two queries above.

**Comment by RobIsHere** [comment]
You are right :) Thank you!!! I deleted it and everything is running well again :+1:
