### ISSUE TITLE
method collection::find works incorrectly

### ISSUE THREAD

**Issue by 0xff00ff** [mongodb/mongo-php-library#190]
in documentation says that method collection::find returns cursor, that can be iterated, but it cat`t. I do not want to use toArray method (i get MongoDB\Driver\Cursor class instance). How can i iterate cursor? (i use 1.1.6 mongodb extension and php 7.0.7)

**Comment by moderndeveloperllc** [comment]
Can you please provide the code that you are using that you feel is not working properly? `MongoDB\Driver\Cursor` implements `Traversable`, so you can just do a `foreach` over that returned class and you will get your results. The type of results you get will be based off of the [typeMap](http://mongodb.github.io/mongo-php-library/tutorial/bson/#type-maps) you use.

[From the documentation](http://mongodb.github.io/mongo-php-library/tutorial/crud/#finding-many-documents):
```
$collection = (new MongoDB\Client)->demo->zips;

$cursor = $collection->find(['city' => 'JERSEY CITY', 'state' => 'NJ']);

foreach ($cursor as $document) {
    echo $document['_id'], "\n";
}
```

**Comment by 0xff00ff** [comment]
Sorry, it's my fault. i used wrong syntax:
foreach ($cursor as $key => $document) {
    echo $document['_id'], "\n";
}
$key throws an error.

**Comment by jmikola** [comment]
@0xff00ff: Is this issue resolved? I don't see anything wrong with the code snippet you shared. During each iteration, `$key` should get set to the zero-based offset of the document in the result set.

This differs from the [legacy driver](https://pecl.php.net/package/mongo), where it would have assumed the value of `$document['_id']`.

**Comment by 0xff00ff** [comment]
Yes, thanks, it was my fault, not an issue. I tried to use mongo cursor as an array (write by key).
