### ISSUE TITLE
unable to install mongodb using composer in ubuntu trusty

### ISSUE THREAD

**Issue by specialedge** [mongodb/mongo-php-library#194]
can someone identify whats wrong?

> steve@localhost:~$ sudo pecl install mongodb
sudo: unable to resolve host localhost.localdomain
downloading mongodb-1.1.7.tgz ...
Starting to download mongodb-1.1.7.tgz (806,777 bytes)
.............done: 806,777 bytes
360 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /tmp/pear/temp/pear-build-root0d0xTR/mongodb-1.1.7
running: /tmp/pear/temp/mongodb/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20121212
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 50509
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to use system libbson... no
checking configuring libmongoc... ...
checking whether to use system libmongoc... no
checking for pkg-config... no
configure: error: Cannot find OpenSSL's libraries
ERROR: `/tmp/pear/temp/mongodb/configure' failed

system is
> steve@localhost:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Comment by jmikola** [comment]
> configure: error: Cannot find OpenSSL's libraries

This looks suspect. Do you have the OpenSSL library installed? Per [Ubuntu's OpenSSL docs](https://help.ubuntu.com/community/OpenSSL#Practical_OpenSSL_Usage):

> In order to build software which requires the OpenSSL general-purpose library, you must first install the development instance of the OpenSSL library. Install the following packages: `libssl-dev`.

**Comment by mbretter** [comment]
apt install pkg-config

the error message is misleading, not openssl is missing, but pkg-config.

had the same issue

**Comment by jmikola** [comment]
I missed "pkg-config... no" in the above paste. Installing that may certainly help. Note that PHP does have a [fallback method](https://github.com/php/php-src/blob/67e23f4be3c01a389043ee97b98d6bcc703d3557/acinclude.m4#L2354) for looking up the OpenSSL library if `pkg-config` is not available. That appears to be what is failing here, since we rely on PHP's `PHP_SETUP_OPENSSL()` function.

**Comment by veerendraudoshi** [comment]
I had the same error, and this command made the trick for me:
sudo apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev pkg-config libsasl2-dev libpcre3-dev

**Comment by maheshareddy** [comment]
@veerendraudoshi thank you, it helped me.

**Comment by rishii7** [comment]
@maheshareddy  Refer [this comment](https://github.com/mongodb/mongo-php-driver/issues/299#issuecomment-237181260).
With the above command we are creating header files which are required by pecl to install mongodb.

**Comment by J-Ibarra** [comment]
@veerendraudoshi, @rishii7, Thank very much
