### ISSUE TITLE
How can we create additional arbitrary fields when use Bucket upload a file?

### ISSUE THREAD

**Issue by lichungfen** [mongodb/mongo-php-library#195]
$bucket = new Bucket($manager, $databaseName, array("bucketName" => "soft"));
$bucket->uploadFromStream($file_name, $source, array("metadata" => array("f_key" => 123), "contentType" => $data["image-file"]["type"]));

How can we create additional arbitrary fields  in the files Collection?

The $options accept only  "aliases, chunkSizeBytes,  contentType,  metadata";

![tmp](https://cloud.githubusercontent.com/assets/18589143/16176007/7a0b1fcc-3634-11e6-843a-a0943a288e30.png)

**Comment by jmikola** [comment]
The `metadata` field is intended to be used for storing additional user data (in lieu of top-level fields). To quote the [specification](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) we're implementing here:

> Note: some older versions of GridFS implementations allowed applications to add arbitrary fields to the files collection document at the root level. New implementations of GridFS will not allow this, but must be prepared to handle existing files collection documents that might have additional fields.

IMO, "handling existing files collection documents that might have additional fields" means that the data can still be queried and returned when we expose a stream's files document. At the moment, we only have a `getIdFromStream()` method that returns the `_id`, but I intend to add a general method to return the entire `fs.files` document for a stream (it is currently accessible via `stream_get_meta_data($stream)['wrapper_data']`).

**Comment by jmikola** [comment]
I opened [PHPLIB-215](https://jira.mongodb.org/browse/PHPLIB-215) to track the addition of a helper method for returning the file document for a stream. The relevant PR is https://github.com/mongodb/mongo-php-library/pull/239.
