### ISSUE TITLE
MongoDB Driver insert

### ISSUE THREAD

**Issue by cossbow** [mongodb/mongo-php-library#199]
I used MongoDB Driver insert a record , but how can i get the last insert _id? My code like that: 

```
<?php
$manager = new MongoDB\Driver\Manager('mongodb://127.0.0.1');
$bulk = new MongoDB\Driver\BulkWrite();
$record = new stdClass();
$record->name = 'Bob';
$record->email = 'Bob@13.net';
$bulk->insert($record);
$result = $manager->executeBulkWrite($collection, $bulk);
```

There is no way to get insert _id ?

**Comment by moderndeveloperllc** [comment]
A couple of things: This repo is for the "wrapper" around things like `MongoDB\Driver\Manager` and `MongoDB\Driver\BulkWrite`. You might want to look into the `MongoDB\Client` that this repo provides. This question really belongs in the [driver repo](https://github.com/mongodb/mongo-php-driver).

But to answer your question, you should be able to use:

 ```$id = \MongoDB\extract_id_from_inserted_document($record);```

 after your `executeBulkWrite`. This is basically what the [`BulkWrite` wrapper](https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/BulkWrite.php#L241) this repo provides does.

**Comment by jmikola** [comment]
[`BulkWrite::insert()`](http://php.net/manual/en/mongodb-driver-bulkwrite.insert.php) actually returns the ID value if it was generated. If the inserted document already had an ID, nothing is returned. In your case, you'll want to save this value:

```
$generatedId = $bulk->insert($record);
```

Alternatively, if you are using this library and its write methods, the following methods exist:

 * `InsertOneResult::getInsertedId()`
 * `InsertManyResult::getInsertedIds()`
 * `BulkWriteResult::getInsertedIds()`

The write operations, which return these result objects, attempt to obtain the ID from the return value of `BulkWrite::insert()`. In the case where the inserted document already had an ID, we still want to populate the result objects. For that reason, we have an internal  `\MongoDB\extract_id_from_inserted_document()` function that attempts to pull the ID out of the user-supplied document. That said, the function is a not part of our public API (the best we can do is annotate it with `@internal`), so please do not depend on it.
