### ISSUE TITLE
Nested arrays do not JSON-encode properly

### ISSUE THREAD

**Issue by LarsKemmann** [mongodb/mongo-php-library#200]
#39 is closed saying ArrayObject instances are returned from queries by default. However, I still can't do:

`echo json_encode($model);`

and get out a JSON array for array-type values (especially nested arrays inside the document(s)). I found myself writing this hack to work around it:

    $x = array();
    $i = 0;
    foreach ($model as $k => $v) {
        $x[$i++] = $v;
    }
    echo json_encode($x));

Help?

**Comment by LarsKemmann** [comment]
I ended up writing this lovely hack as a temporary workaround.

    function toSeqArray($arg, $callbacks)
    {
        $retval = [];
        $i = 0;
        foreach ($arg as $k => $v) {
            if (is_scalar($v)) {
                $value = $v;
            } else {
                $value = [];
                foreach ($v as $k2 => $v2) {
                    if (array_key_exists($k2, $callbacks)) {
                        $value[$k2] = $callbacks[$k2]($v2);
                    } else {
                        $value[$k2] = $v2;
                    }
                }
            }
            $retval[$i++] = $value;
        }
        return $retval;
    }
    
    $notificationsList = toSeqArray($model['ArrayInDocument'], [
        "NestedArrayA" => function ($nestedA) {
            return toSeqArray($nestedA, [
                "NestedSubArrayA1" => function ($nestedSubA1) { return toSeqArray($nestedSubA1); },
                "NestedSubArrayA2" => function ($nestedSubA2) { return toSeqArray($nestedSubA2); }
            ]);
        },
        "NestedArrayB" => function ($nestedB) { return toSeqArray($nestedB); }
    ]);

**Comment by jmikola** [comment]
If I understand this issue correctly, you'd like the default [BSONArray](https://github.com/mongodb/mongo-php-library/blob/master/src/Model/BSONArray.php) class to implement [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php) and return its data as a sequential array (per [this example](http://php.net/manual/en/jsonserializable.jsonserialize.php#refsect1-jsonserializable.jsonserialize-examples)). Is that right?

This would be a trivial fix and I can work on getting it in soon. Note that you will still likely need [PHPC-459](https://jira.mongodb.org/browse/PHPC-459) implemented in the underlying extension to make full use of `json_encode()` (currently, BSON classes in the extension don't serialize very nicely to JSON). We're targeting that for 1.2.0.

**Comment by jmikola** [comment]
PR: https://github.com/mongodb/mongo-php-library/pull/202

**Comment by materliu** [comment]
just do composer update mongodb/mongodb, the new version mongo-php-library will resolve your problem.
