### ISSUE TITLE
streamWrapper::stream_seek implementation

### ISSUE THREAD

**Issue by evilforce** [mongodb/mongo-php-library#204]
Hello. Are you planning to implement streamWrapper::stream_seek method in StreamWrapper class?

**Comment by jmikola** [comment]
This is a suggested feature in the [GridFS specification](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#partial-file-retrieval); however, there are no immediate plans to implement it. I've opened [PHPLIB-213](https://jira.mongodb.org/browse/PHPLIB-213) to track the feature and cross-referenced it with this issue.

**Comment by jmikola** [comment]
Closing this. Any updates on the subject will take place in [PHPLIB-213](https://jira.mongodb.org/browse/PHPLIB-213).

**Comment by jmikola** [comment]
@yura-tovt: We have an implementation of seeking for readable streams in https://github.com/mongodb/mongo-php-library/pull/325 if you'd like to test that out. Since it's a new feature, it will not be released until 1.2.0; however, I'd be interested to hear whether it meets your needs.
