### ISSUE TITLE
Call to undefined method MongoDB\Database::getGridFS()

### ISSUE THREAD

**Issue by lenyapugachev** [mongodb/mongo-php-library#205]
In first, huge thanks for your work.

I'm using Laravel multiple db connections and the main is mysql over [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb), so I'm trying to get GridFS like this:

`$grid = DB::connection('mongo')->getMongoDB()->getGridFS();`

But it's throwing "Call to undefined method MongoDB\Database::getGridFS()".

I've checked phpinfo() and PECL driver mongodb is up-to-date. This library is 1.0.2, have a try with master branch current code, but no changes.

I've read the Database.php, but mentioned that there is no function called getGridFS.

I've searched through your issues and seeing that you still working on GridFS, but there is some allusions of it's working in issues of [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb), so I'm posting this.

**Comment by lindelius** [comment]
You are correct in that there is no function in `MongoDB\Database` for getting a GridFS instance of any sort. The classes for handling GridFS actions are located in the `GridFS\` folder and `MongoDB\GridFS` namespace. As far as I know there are no mentions of GridFS in any section of the documentation or source code for Jens Segers' MongoDB connector, so I'm a bit curious why you would expect the code above to work.

**Comment by lenyapugachev** [comment]
@lindelius Hello, Tom. Thanks for your answer, will dig into GridFS class, as I see there is couple of issues to solve, maybe it will work. Why I was expecting code above to work is two kinda-success-mentions of this code [here](https://github.com/jenssegers/laravel-mongodb/issues/231) and [here](https://github.com/jenssegers/laravel-mongodb/issues/231)

**Comment by lindelius** [comment]
All right, I looked into it a bit further and I now know where the problem lies. Your code (and the code examples from the issues you linked) were using the legacy driver. In the legacy driver[ the MongoDB class](http://php.net/manual/en/class.mongodb.php) has a function called `getGridFS()`, which is what is used in the code snippets. This is not supported in the new driver, which is the reason for why this doesn't work anymore.

**Comment by lenyapugachev** [comment]
I'm closing this issue. But if I have any chance of developers answer it would be just awesome:

If you are making project and have one month for this do you prefer to dig into current GridFS implementation here to try to use old legacy driver?

**Comment by lindelius** [comment]
@jmikola Any comments for https://github.com/mongodb/mongo-php-library/issues/205#issuecomment-228829812?

**Comment by jmikola** [comment]
Cross-referencing with https://github.com/jenssegers/laravel-mongodb/issues/262.

To paraphrase my reply in https://github.com/jenssegers/laravel-mongodb/issues/838#issuecomment-228841563:

> [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library) does not yet implement GridFS. Support for GridFS will show up in 1.1.0 (see: [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114)); however, it's API will differ significantly from the [legacy driver's GridFS API](http://php.net/mongogridfs).

> If you are making project and have one month for this do you prefer to dig into current GridFS implementation here or try to use old legacy driver?

The legacy driver is the only released GridFS implementation at present.

I can tell you that most of the GridFS implementation is sitting in the `master` branch. [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114) is up-to-date with a list of remaining tasks for the component. Beyond that, there are a handful of other tickets slated for 1.1.0 (e.g. new command helper methods). I estimate this will be wrapped up during the month of July.

**Comment by jmikola** [comment]
[1.1.0-alpha1](https://github.com/mongodb/mongo-php-library/releases/tag/1.1.0-alpha1) has been tagged and includes the GridFS classes.
