### ISSUE TITLE
select certain field?

### ISSUE THREAD

**Issue by cenxun** [mongodb/mongo-php-library#206]
Does the current support select certain fields? just like [Project Fields](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#projection-document)
Such as SQL, select `a, b, c`
```sql
select a, b, c from x 
```
I see the Mongo client is supported, such as the following statement to return to the city field
``` Db.zips.find ({'city': 1} {},.Limit) (1) ```
Thank you for providing this library ！

**Comment by jmikola** [comment]
[Field projections](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#projection-document) are possible using the "projection" option on the `MongoDB\Collection::find()` and `findOne()` methods. See: http://mongodb.github.io/mongo-php-library/tutorial/crud/#query-projection for some examples.

If you are using the extension directly, you would specify this option in the second argument to [`MongoDB\Driver\Query::__construct()`](http://php.net/manual/en/mongodb-driver-query.construct.php).

**Comment by cenxun** [comment]
cool~  thanks.
