### ISSUE TITLE
String representation of ObjectID in JSON serialization of a BSONDocument

### ISSUE THREAD

**Issue by Gochip** [mongodb/mongo-php-library#213]
Hello

I use json_encode function for generate JSON of a BSONDocument. My problem is that the ObjectID is not show. I solved this because I overwrote jsonSerialize method in BSONDocument class with:

```
public function jsonSerialize()
{
   $obj = $this->getArrayCopy();
   foreach ($obj as $key => $elem) {
      if(is_object($elem) && get_class($elem) === "MongoDB\BSON\ObjectID") {
         $obj[$key] = $elem->__toString();
      }
   }
   return (object) $obj;
}
```

But my question is: Is there another way to do this?

**Comment by moderndeveloperllc** [comment]
Probably related to #150 and https://github.com/mongodb/mongo-php-driver/issues/270

**Comment by subversivo58** [comment]
In line:

     $obj[$key] = $elem->__toString();

change to return string:

     $obj[$key] = (string) $obj[$key];

**Comment by jmikola** [comment]
@moderndeveloperllc: #150 and mongodb/mongo-php-driver#270 only pertained to PHP serialization ([PHPC-460](https://jira.mongodb.org/browse/PHPC-460)), which is currently implemented in the extension's master branch.

Having the BSON classes implement [JsonSerializable](php.net/jsonserializable) will be done in [PHPC-459](https://jira.mongodb.org/browse/PHPC-459) (also slated for 1.2.0). That said, the `jsonSerialize()` methods will be returning data consistent with [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/), which means an ObjectID would be serialized as `{ "$oid": "<id>" }` (see: [here](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#oid)). If users need the ObjectID displayed as a string, that will still require manual casting as @subversivo58 suggested.

**Comment by moderndeveloperllc** [comment]
@jmikola That's me not reading the question properly - sorry about that.

**Comment by Gochip** [comment]
@jmikola Thanks!

**Comment by jmikola** [comment]
Closing this issue as I don't believe there's anything remaining. Please follow [PHPC-459](https://jira.mongodb.org/browse/PHPC-459) for updates on our BSON classes implementing JsonSerializable.
