### ISSUE TITLE
Forcing close on TCP sockets to mogodb nodes with new API

### ISSUE THREAD

**Issue by lglayal** [mongodb/mongo-php-library#215]
Hi,

Considering a bunch of PHP fastcgi processes, a firewall, and a mongo replicaset.
By using persistent connections to mongo nodes we can improve performance but on low traffic between fastcgi processes and the nodes the FW may timeout TCP sessions, three ways for a FW to drop session :
(1) - drop session table entry without sending end of TCP session to both legs/endpoints
* in this case nor kernel or the fastcgi process has  clue on the real state of TCP session,  any TCP reuse will generate timeout/exceptions/delayed processing. 

(2) - drop session table entry and send end of TCP session to only one leg
* in this case the fastcgi process has no clue on the real state of TCP session, any TCP reuse will generate timeout/exceptions/delayed processing

(3) - drop session table entry and send end of TCP session to both legs
* in this case the kernel knows a socket is closed but the fastcgi process will only see a state change when it tries to reuse socket, so generating an error and needs to recreate a new session.

Dropped sessions in FW can also occur on FW rules reloaded.

With legacy driver, to limit the number of issues we used to check creation time for TCP sockets (tracked using a status file) and we closed it (with reduced timeout configuration) too old. 

We also close sockets  for application we know only use db for a couple of reqests a day.

How can we force a close with latest mongodb driver and new mongo-php-library ?

NB : it's also usefull to get control on client side sockets and force close() to limit number of TCP sessions on platform/firewalls/servers.
Thanks.
BR.

**Comment by jmikola** [comment]
In the future, such an issue would be better opened on [mongo-php-driver](https://github.com/mongodb/mongo-php-library/), as this userland library is only responsible for high-level APIs (e.g. command wrappers). All connection handling happens in the underlying driver and libmongoc.

> With legacy driver, to limit the number of issues we used to check creation time for TCP sockets (tracked using a status file) and we closed it (with reduced timeout configuration) too old.

Can you elaborate on how this was done? AFAIK, the legacy driver did not expose its sockets, so I'm at a loss for how you would have manually closed them unless you're talking about [MongoClient::close()](http://php.net/manual/en/mongoclient.close.php).

There are no plans to reintroduce close methods in the new driver at this time.

libmongoc implements a "serverSelectionTryOnce" mode from the [server selection specification](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#serverselectiontryonce), which should be capable of reconnecting once. It is also possible to disable that mode, which is the default for single-threaded drivers such as PHP, to have libmongoc make several attempts until a configurable timeout is reached. If this implementation does not play nicely with firewalls, that may be worthy of a bug report to libmongoc ([CDRIVER](https://jira.mongodb.org/browse/CDRIVER) in JIRA) for further investigation.

**Comment by lglayal** [comment]
Yes, we are closing sockets using MongoClient::close() on legacy. 
I will open a bug on JIRA to follow this case. 
Thanks. 
BR
