### ISSUE TITLE
Wrong Documentation: findOne(['_id' =>new MongoDB\BSON\ObjectID('94301')])  instead of findOne(['_id' => '94301'])

### ISSUE THREAD

**Issue by ok-at-github** [mongodb/mongo-php-library#217]
Hi,
it seems to me that if we'd like to search by the internal _id we have to use "new MongoDB\BSON\ObjectID($_id)" instead of using the _id just as string:

E.g. instead of:
`$document = $collection->findOne(['_id' => '94301']);`

we have to do this:
`$document = $collection->findOne(['_id' => new MongoDB\BSON\ObjectID('94301')]);`

Found here:
http://lornajane.net/posts/2016/find-mongo-document-by-id-using-the-php-library

If this is right could somebody update the docs?

Thanks,
Olaf

E.g. docs for "Finding One Document":
![mongodb_phplib_docs](https://cloud.githubusercontent.com/assets/14052170/17101629/eda22bd0-5275-11e6-854d-1ff693087bd2.PNG)

**Comment by lindelius** [comment]
The `_id` field for a MongoDB document can be any value, as long as it's unique. It doesn't necessarily have to be an **ObjectID**. In the example in the documentation, the ID of the document is a string -- as that makes most sense for a collection containing zip codes.

**Comment by ok-at-github** [comment]
I've just test it by creating an document that contains the `_id` as string. It could be retrieved by just passing the `_id` to the `findOne()` function as you said and as it described in the docs.
Thank you for the hint!

So this is not an issue but I think without this knowledge this is a kind of needless pitfall, especially for beginners like me.
Maybe a hint that for documents that were stored using the auto generated `_id` we have to pass the `_id` as **ObjectId** to be able to retrieve it might be helpful.

Thanks,
Olaf

**Comment by lindelius** [comment]
I think this is more of a misunderstaning in how the MongoDB `_id` field works, rather than an issue with the documentation for this library. However, I guess it wouldn't hurt to include it somewhere just to remove any possibility for confusion.

**Comment by jmikola** [comment]
I've opened [PHPLIB-208](https://jira.mongodb.org/browse/PHPLIB-208) to track this task so we can make sure an example ends up in the documentation. We're currently not making any changes while MongoDB's docs team ports our existing content over to a new format; otherwise, I'd simply make the change today.

**Comment by ok-at-github** [comment]
Sounds good, thank you!

**Comment by samuele-artuso** [comment]
six months in and this hasn't been solved yet... it took me an 2 hours to work out that there was an error in the documentation.

**Comment by subversivo58** [comment]
It took me a while to find this discussion.

I also had error after upgrading from an older version to the current version.

The old code used **BSON\ObjectID** and I found nothing in the documentation that explains why I can use `{string}` now

**Comment by lindelius** [comment]
This was actually added to the documentation a few weeks back.

> When evaluating query criteria, MongoDB compares types and values according to its own comparison rules for BSON types, which differs from PHP’s comparison and type juggling rules. When matching a special BSON type the query criteria should use the respective BSON class in the driver (e.g. use MongoDB\BSON\ObjectID to match an ObjectId).

Also, note that this is not a functionality that has recently been added to the driver or the library. This has always worked. The way that the `_id` field works in MongoDB has nothing to do with the client code. You have always been able to use any BSON type as `_id` for your documents, as long as the value is unique across your collection. The type you use in your documents determines which value you have to use in your queries. If you use strings as `_id` you have to query with string IDs, if you use `ObjectId` you have to query with `MongoDB\BSON\ObjectID` IDs, and so on.

**Comment by code100** [comment]
It took me a while to figure it out, with solution of $collection->findOne(['_id' => new \MongoDB\BSON\ObjectID($id)]), although it is described in the document, why don't you just give an example in the document, one line of code won't hurt.

**Comment by jmikola** [comment]
> why don't you just give an example in the document

None of the [example datasets](https://docs.mongodb.com/php-library/master/tutorial/example-data/) used in the documentation include ObjectIDs, so any code examples querying by an ObjectID would not have been reproducible for users since different ObjectIDs would have been created when they imported the datasets.

That said, I added an example without the usual "expected output" line in https://github.com/mongodb/mongo-php-library/pull/380. It should be deployed within the hour.

**Comment by keyurptl** [comment]
Hey Guys I am trying this way in My CI model but it not giving me any result. 
$collection->findOne(['_id' =>'59f99ee7ffc11d17940026cb'])

Same way if I am passing other filed name and value it gives me result any one please help me on this.

**Comment by alcaeus** [comment]
@keyurptl see the first comment: if you stored an `ObjectID`, you have to query for an `ObjectID`:
`$collection->findOne(['_id' => new MongoDB\BSON\ObjectID('59f99ee7ffc11d17940026cb']));`

**Comment by ShwetaTaral** [comment]
$data= $blogsData->findOne(["_id"=>new \MongoDB\BSON\ObjectID($blogId)]); but still I am getting issue. Can some one help.

**Comment by mbritton** [comment]
Getting this issue in PHP 7.1.19. Lumen, MongoDB default drivers.

`public function getLoaner(Request $request)
{
    $client = new MongoDB\Client("mongodb://localhost:27017");
    $collection = $client->dbName->loaners;

    $id = new MongoDB\BSON\ObjectId($request->input('loanerID'));
    $filter = ['_id' => $id];
    $loanerResults = $collection->findOne($filter);

    $this->doOutput($loanerResults);
}`

Returns null. The _id is present and the loanerID is a string.

**Comment by jmikola** [comment]
@mbritton: Please open a new issue, rather than continuing discussion in this closed thread. When doing so, please also share the exact document you expect to be returned by `findOne()` here (querying it via the `mongo` shell would be fine) and also `var_dump()` the return value of `$request->input('loanerID')` before you use it to construct a new ObjectId object for the query.
