### ISSUE TITLE
GridFS Module not loaded by composer

### ISSUE THREAD

**Issue by yonus** [mongodb/mongo-php-library#220]
I loaded by using composer. But in file systems  , there are not GridFS module.   
the version in  my composer file is  "mongodb/mongodb":"^1.0.0"

**Comment by jmikola** [comment]
The GridFS functionality has not been published in a stable release, so you won't be able to access it in Composer without pulling in an unstable version. A forthcoming 1.1.0-alpha1 release should be the first version with the feature.

**Comment by jmikola** [comment]
[1.0.0-alpha1](https://github.com/mongodb/mongo-php-library/releases/tag/1.1.0-alpha1) has been tagged and includes the GridFS classes.
