### ISSUE TITLE
How to save file as bytes

### ISSUE THREAD

**Issue by yonus** [mongodb/mongo-php-library#221]
In old mongo extentions ,  I can save content in GridFS by $gridFs->storeBytes(). In this library how to save byte content as file and read ? unfortunetly I can not find documentation for this.

Thanks your helps

**Comment by jmikola** [comment]
We've yet to document any of the new GridFS classes as we're still waiting for MongoDB's docs team to 
migrate our existing manual to a new format (consistent across all of the driver projects).

That said, the new API uses PHP streams, so you would use need to use [`stream_get_contents()`](http://php.net/stream_get_contents) on the resource returned by the Bucket's `openDownloadStream()` or `openDownloadStreamByName()` method. On a related note, the `downloadToStream()` and `downloadToStreamByName()` methods use the same resources but pipe the file contents directly to a writable stream via [`stream_copy_to_stream()`](http://php.net/stream_copy_to_stream).

Feel free to ask additional questions as needed.

**Comment by jmikola** [comment]
Closing this as I believe my last comment answered the original question. Feel free to open a new issue if you have additional questions.

To reiterate, this is definitely an example we will have in our forthcoming GridFS documentation.
