### ISSUE TITLE
How can I use the $pull modifier?

### ISSUE THREAD

**Issue by sergiorighi** [mongodb/mongo-php-library#222]
I'm trying to use **$pull** (and **$unset** too), but I'm only having error messages. These modifiers are not implemented yet, or there is another way I can use them?

**Comment by jmikola** [comment]
> These modifiers are not implemented yet, or there is another way I can use them?

These modifiers are syntax for update operations (e.g. `updateOne()`, `findOneAndUpdate()`), so there is no reason they would be implemented in the library. The examples in the MongoDB manual use the shell, but they are analogous to how you would invoke this library's update methods:

 * https://docs.mongodb.com/manual/reference/operator/update/pull/
 * https://docs.mongodb.com/manual/reference/operator/update/unset/

Here is a concise example using both operators:

```
<?php

require 'vendor/autoload.php';

$collection = (new MongoDB\Client)->test->foo;
$collection->drop();

$collection->insertOne(['_id' => 1, 'x' => 0, 'y' => [1, 2, 3]]);

var_dump($collection->findOne(['_id' => 1]));

$collection->updateOne(
    ['_id' => 1],
    [
        '$pull' => ['y' => ['$lt' => 3]],
        '$unset' => ['x' => 1]
    ]
);

var_dump($collection->findOne(['_id' => 1]));
```

Expected output should be similar to:

```
object(MongoDB\Model\BSONDocument)#14 (1) {
  ["storage":"ArrayObject":private]=>
  array(3) {
    ["_id"]=>
    int(1)
    ["x"]=>
    int(0)
    ["y"]=>
    object(MongoDB\Model\BSONArray)#13 (1) {
      ["storage":"ArrayObject":private]=>
      array(3) {
        [0]=>
        int(1)
        [1]=>
        int(2)
        [2]=>
        int(3)
      }
    }
  }
}
object(MongoDB\Model\BSONDocument)#11 (1) {
  ["storage":"ArrayObject":private]=>
  array(2) {
    ["_id"]=>
    int(1)
    ["y"]=>
    object(MongoDB\Model\BSONArray)#10 (1) {
      ["storage":"ArrayObject":private]=>
      array(1) {
        [0]=>
        int(3)
      }
    }
  }
}
```
