### ISSUE TITLE
Aggregation Framework isDead true

### ISSUE THREAD

**Issue by Roycohen** [mongodb/mongo-php-library#223]
Hi Guys,

I had an aggregation pipeline which worked in the old Mongo driver.
I saw that there is no change between the 2 drivers, however the pipeline is not returning data.

The 'match' stage includes MongoRegex which I've changed to 'MongoDB\BSON\Regex' and MongoDate in unix timestamp which I've change to MongoDB\BSON\UTCDateTime in milliseconds.

2 question:
1. Does MongoDB\BSON\UTCDateTime needs to get time in milliseconds or can I send it php unix timestamp which is in seconds? I think it is currently only working with milliseconds.
2. The most important one: Why does it my pipeline is not working. The same pipeline works in the old driver. BTW, When the result is returned I always see isDead=true.

I really need your help guys.

**Comment by lindelius** [comment]
The constructor for `MongoDB\BSON\UTCDateTime` does indeed require the time to be in milliseconds, and not in seconds. If you only have the time in seconds (UNIX timestamp), you can just multiply it by 1000 when you create the `UTCDateTime` object.

Could you please post the actual code that you use when calling the `aggregate()` function, including the pipeline.

**Comment by Roycohen** [comment]
[aggregation-pipeline.txt](https://github.com/mongodb/mongo-php-library/files/401778/aggregation-pipeline.txt)
Uploaded.
I've attached pipeline, result and options.

Please let me know what can I do.
I must understand what is not working
[aggregation-pipeline.txt](https://github.com/mongodb/mongo-php-library/files/401787/aggregation-pipeline.txt)

**Comment by moderndeveloperllc** [comment]
Also note that the [forthcoming 1.2 version](https://jira.mongodb.org/browse/PHPC-536?jql=fixVersion%20%3D%201.2.0%20AND%20project%20%3D%20PHPC) of the driver [will allow you to set](https://github.com/mongodb/mongo-php-driver/pull/336) a `DateTimeInterface` object (`DateTime` or `DateTimeImmutable`) as the instantiation parameter for `MongoDB\BSON\UTCDateTime`. It does the math on the `DateTime` object for you.

```php
use MongoDB\BSON\UTCDateTime;

$dateTime = (new DateTime())->setTimestamp($timestamp);
$mongoDate = new UTCDateTime($dateTime);
```

**Comment by Roycohen** [comment]
Thanks!!
multiplying it by 1000 :).
I'm doing something similar in my app. I have a class which gets anything and returns a MongoDB\BSON\UTCDateTime in the right format.

Can you tell me why my pipeline is not working and why the result object is dead.

**Comment by moderndeveloperllc** [comment]
@Roycohen When you iterate over the cursor, you get no results? That's one big change between drivers - you now get an iterable Cursor object as opposed to an array of results. Per the docs:

> A cursor being "dead" does not mean that it cannot be iterated further. The database sends responses in batches of documents (up to 4MB of documents per response). The client's cursor may still have results to be iterated even if the server has no more batches to send.

From a pure performance point of view, I would question the need to search for the entire ID using regex expressions. But I'm guessing that IDs aren't the only thing your code can put into this pipeline.

**Comment by jmikola** [comment]
@Roycohen: Both of the text files you attached have extra formatting. Can you either re-attach these as plain text or simply embed the content as a [fenced code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) within your comment?

Since it hasn't been discussed above, I should remind you that [`MongoRegex::__construct()`](http://php.net/manual/en/mongoregex.construct.php) and [`MongoDB\BSON\Regex::__construct()`](http://php.net/manual/en/mongodb-bson-regex.construct.php) take their arguments in different forms.

**Comment by moderndeveloperllc** [comment]
@jmikola Just an FYI if you want to see them now, make the extension .rtf and they open nicely. The second is all you need I think as the returned cursor dump includes the command from the first file.

**Comment by Roycohen** [comment]
Hi Guys,

I know Regex is an ass, and I should avoid it. Thanks.
The Regex is built in the new format. Otherwise you'll get an exception.
MongoDB\BSON\Regex("/$id/", "i")

@jmikola, whats @moderndeveloperllc suggest indeed makes the file readable. If it still doesn't work for you, just let me know.

@moderndeveloperllc, I know it is a cursor. Before I've user aggregateCursor so it is the same.
I'm iterating over this object but never have results.
I'm using read preference.

`        $readPreference = new \MongoDB\Driver\ReadPreference(\MongoDB\Driver\ReadPreference::RP_SECONDARY_PREFERRED);
        try {
            $result = $this->_statsMongo->{$aggrCollection}->aggregate(
                $pipeline,
                array(
                    'allowDiskUse' => true,
                    'batchSize' => 100,
                    'explain' => true,
                    'readPreference' => $readPreference
                )
            );
`

Really need help in this. Something is not working there.

**Comment by jmikola** [comment]
> MongoDB\BSON\Regex("/$id/", "i")

[`MongoDB\BSON\Regex::__construct()`](http://php.net/manual/en/mongodb-bson-regex.construct.php) does not expect the pattern to be wrapped with delimiters. MongoRegex used delimiters because it took the pattern and flags in a single string. I expect that's your problem.

**Comment by Roycohen** [comment]
Thanks..
Funny I've tried to remove it and it didn't worked.
Now when I ran it, it is working.

Any how, I'll keep you updated with more things like this.
Now I have a strange phenomena which I don't know whether it is related to this library.

**Comment by Roycohen** [comment]
Now I have a very strange behavior. Don't know if it is because PHP7 or because pf the driver but I suspect 99.9% it is something in the driver.
I'm iterating over the result cursor from the aggregation pipeline and I have the following structure in each returned doc:
array with 2 fields:
```
_id => array(
'date' => MongoDB\BSON\UTCDateTime
)
'value' => array(
'x' => 1,
'y' => 2,
...
)

```
And I want to get the date as timestamp so I'm using this function:

```
static public function getTimestampFromMongoDate($mongoDate, $usec = false)
    {
//        var_dump($mongoDate);
        if (is_object($mongoDate) && is_a($mongoDate, 'MongoDate')) {
            return $mongoDate->sec;
        } else if (is_object($mongoDate)
            && is_a($mongoDate, 'MongoDB\BSON\UTCDateTime')
            && isset($mongoDate->milliseconds)
        ) {
            if ($usec) {
                return $mongoDate->milliseconds;
            } else {
                return intval($mongoDate->milliseconds/1000);
            }
        } else if (is_numeric($mongoDate)) {
            return intval($mongoDate);
        } else {
            return null;
        }
    }

```

Now the phenomena...
When I'm stopping in xDebug on the place where I'm using the above function the timestamp is returned good.
When I'm running it without debug the timestamp is 0 or empty.
If I'm adding a var_dump to the beginning of the 'getTimestampFromMongoDate' function, it is working as expected without debug... But obviously I can't do that :)

I can show you this phenomena in Remote Access if you want to see this in action.
I know it might not make sense but it is happening to me, and really appreciate your help on this guys.

**Comment by lindelius** [comment]
`MongoDB\BSON\UTCDateTime` doesn't have any public properties, so `isset($mongoDate->milliseconds)` is always going to return `false`.
When you pass a `MongoDB\BSON\UTCDateTime` object to this function, the returned value will always be `null`.

**Comment by Roycohen** [comment]
OK Great, thanks, it seems to work.
There is only one question that I would love to get an answer.
Why when I stop in debug or var_dump the object before using it as I used it before, it worked?

**Comment by lindelius** [comment]
I don't know what you mean by "worked as I used it before", but if you `var_dump()` an instance of `MongoDB\BSON\UTCDateTime` it outputs something like this

```php
object(MongoDB\BSON\UTCDateTime)#2 (1) {
    ["milliseconds"]=>
    string(13) "1470580534000"
}
```

The `milliseconds` property that is displayed is an internal property, so even though it's there when you dump it out, you can't access it. I don't know if this answers the question as I don't know how you used it before, or how it "worked" when you debugged it. If it doesn't, please reply with an example and an explanation of what seems to work when you are debugging it, and I'll have a look.

**Comment by Roycohen** [comment]
Thanks @lindelius.
First of all, your solution to cast the 'MongoDB\BSON\UTCDateTime' is working.
Now for my question. I don't know if it is related to the Library, but I would like to hear your thoughts.

My 'getTimestampFromMongoDate' function that posted above didn't worked if I used it as is.
But if you would take a look in the function, in the beginning of it I commented out `var_dump($mongoDate); `. If I'm un-commenting this line and execute my function then the function returns the right result and the result isn't false. if I'm commenting the line then the result is as you said, NULL.

So my Question is, how can you explain this behavior?
Hope you understand what I meant.

**Comment by lindelius** [comment]
When I test your function I get `null` as expected, and when I add the `var_dump()` back I get the following output, just as expected

```php
object(MongoDB\BSON\UTCDateTime)#2 (1) {
    ["milliseconds"]=>
    string(13) "1470609336000"
}
NULL
```

I have no idea how this just "works" for you by adding a `var_dump()` to the function. It sounds absolutely bizarre. You must have some weird problem elsewhere, or just read the output incorrectly.

**Comment by Roycohen** [comment]
I agree with you that it is bizarre.
I can show it to you on Screen share, you'll be blown.
If you have the time and want to see a phenomena, then we can Share screen via Skype.

**Comment by jmikola** [comment]
If you guys are seeing `milliseconds` reported as a string when `var_dump()`-ing a UTCDateTime, your PHP environment likely has 32-bit integers. This may pose a problem if you're expecting to work with the timestamp as an integer (this includes dividing it by 1000 to convert to seconds).

[`UTCDateTime::__toString()`](http://php.net/manual/en/mongodb-bson-utcdatetime.tostring.php) can be used to obtain the milliseconds value as a string, after which you can manually trim characters to convert to seconds or do proper division with GMP or BCMath. Alternatively, you can use [`UTCDateTime::toDateTime()`](http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php) and invoke [`DateTime::format('U')`](http://php.net/manual/en/datetime.format.php) to get the Unix timestamp in seconds.

**Comment by Roycohen** [comment]
I have 64-bit machine.
I must show someone this bizarre issue so you'll understand what I'm experiencing.
Then you'll understand what I mean.

**Comment by marcusesa** [comment]
@jmikola always that we need save `MongoDB\BSON\UTCDateTime` type, we should pass `$milliseconds` parameter in construct. 

Questions:

- The `$milliseconds` parameter must be`UTC` timezone, right?
- Always that we have `DateTime` object we need do something like this:
```php
$datetime = convert_to_utc_timezone($datetime);
$milliseconds = $datetime->format('U') * 1000;
$valueConverted = new \MongoDB\BSON\UTCDateTime($milliseconds);
```

- Is not be usefull, if always that `DateTimeInterface` object was received, `mongo-php-library` encapsulate the above block? (I was thinking make same PR about it. What do you think?)

**Comment by lindelius** [comment]
As the object is a **UTC** date object, it's preferable to pass a UTC timestamp (in milliseconds) as the time is presumed to be in the UTC timezone.

For converting `DateTime` objects, I currently use the following function (which performs better than 5-6 other versions I've tested):

```php
/**
 * Converts a `DateTime` object to a `MongoDB\BSON\UTCDateTime` object.
 *
 * @param  DateTime $dateTime
 * @return UTCDateTime
 */
function getBsonDateFromDateTime(DateTime $dateTime)
{
    $milliseconds = (float) substr((string) $dateTime->format('Uu'), 0, -3);

    return new UTCDateTime($milliseconds);
}
```

**Comment by marcusesa** [comment]
@lindelius I wasn't thinking pass `DateTime` to `UTCDateTime`. I was thinking, if this conversion would not be more useful if it was automatically for `DateTimeInterface` objects.
Example: 
```php
$collection->insertOne(['created_at' => \DateTime('now')]);
```

**Comment by moderndeveloperllc** [comment]
@marcusesa Check my comment from the top of this issue. That functionality will be in [the next driver release - 1.2.0](https://jira.mongodb.org/browse/PHPC-536?jql=fixVersion%20%3D%201.2.0%20AND%20project%20%3D%20PHPC)

**Comment by marcusesa** [comment]
@moderndeveloperllc nice

**Comment by lindelius** [comment]
@marcusesa Yes, that would of course be ideal,but it isn't possible at the moment. However, just like @moderndeveloperllc said, it's coming :)

**Comment by marcusesa** [comment]
Guys the [release pointed](https://jira.mongodb.org/browse/PHPC-536?jql=fixVersion%20%3D%201.2.0%20AND%20project%20%3D%20PHPC) by @moderndeveloperllc it's about a change in `mongodb` extension, that can receive a `DateTime` object in constructor of `UTCDateTime`. This is nice and useful.
But I still think that high level library like `mongo-php-library`, could understand that a value with `DateTime` object never should save like a `array` as is today, and always should make something like this:
```php 
<?php

function checkValue($value) {
    if ($value instanceof \DateTimeInterface) { 
        $milliseconds = $value->format('U') * 1000;
        return new UTCDateTime($milliseconds);
    }

    return value;
}
```
When a instance of `DateTimeInterface` was passed in write methods such as: `insertOne`, `replaceOne` etc, the value should be automatically converted to `UTCDateTime`.
And the inverse could be applied in read methods.

cc: @lindelius

**Comment by jmikola** [comment]
> But I still think that high level library like mongo-php-library, could understand that a value with DateTime object never should save like a array as is today

Serializing classes to BSON is not the responsibility of the library (we do define BSONDocument and BSONArray classes, but those are merely used by the driver). All actual BSON logic is contained within the driver itself and we require [implementing interfaces](http://php.net/manual/en/mongodb.persistence.serialization.php) to control serialization.

We don't want to make any assumptions about handling of DateTime objects in the driver. There are at least two cases where we wouldn't be able to successfully round-trip a DateTime object between PHP and BSON:

 * The BSON date type doesn't have a time zone, so that would be lost.
 * The BSON date type has millisecond precision, while DateTime can have microseconds.

[PHPC-536](https://jira.mongodb.org/browse/PHPC-536), which @lindelius linked above, is likely the best we'll get for DateTime support.

[PHPC-640](https://jira.mongodb.org/browse/PHPC-640), which is further down the line, would allow users (or an ODM) to define their own date class; however, that still wouldn't be usable with DateTime directly. It would require a class to implement the requisite interfaces.

----

On a separate note, this issue has veered quite a bit from the original question about an aggregation framework query. @Roycohen: if the issue last discussed in https://github.com/mongodb/mongo-php-library/issues/223#issuecomment-238501903 is still affecting you, please create a separate ticket so it can be tracked.

In the future, please keep threads to a single issue. This will keep discussion on topic and make it easier for folks to reference a particular issue later on.
