### ISSUE TITLE
MongoDB\Driver\Exception\BulkWriteException on insert not documented

### ISSUE THREAD

**Issue by jacobweber** [mongodb/mongo-php-library#229]
If I have a collection with an indexed field, and I call insertOne to try to insert a duplicate value in that field, I get a BulkWriteException:

```
class MongoDB\Driver\Exception\BulkWriteException#197 (9) {
  protected $message =>
  string(126) "insertDocument :: caused by :: 11000 E11000 duplicate key error index: STF.preferences.$sviUserId_1  dup key: { : "00090A19" }"
...
```

Shouldn't this throw one of the exceptions from this library, or an InsertOneResult? The documentation doesn't say that this function can throw an exception.

Using mongodb extension 1.1.8, PHP library 1.0.2, PHP 5.4.5.

**Comment by moderndeveloperllc** [comment]
You wouldn't get a `InsertOneResult` as that would imply you got a "positive" (non Error/Exception) result. This library has very few exceptions coded actually. They are for when you use the library incorrectly as opposed to doing something that the database itself feels is wrong (inserting a duplicate). 

One could argue that [`BulkWriteException`](http://php.net/manual/en/class.mongodb-driver-exception-bulkwriteexception.php) is odd, but remember that all insert/update/deletes by the driver are done via [`BulkWrite`](http://php.net/manual/en/class.mongodb-driver-bulkwrite.php), so it does make sense in that respect. At least it has a useful exception message!

**Comment by jacobweber** [comment]
Yeah, it's not a big deal once you know about it. Feel free to close. I was a little confused, because other similar things don't throw an exception (e.g. deleteOne when nothing matches the filter).

**Comment by lindelius** [comment]
But "nothing matches filter" isn't supposed to throw an exception, though, as that isn't actually an error. Trying to insert a document with a duplicate _id, however, is.

**Comment by jmikola** [comment]
@schmalliso: Do you recall if the new documentation covers thrown exceptions? This is likely something we'll want to add if not.

**Comment by schmalliso** [comment]
@jmikola I do not believe it does currently, no…

**Comment by jmikola** [comment]
Documentation task is being tracked in [PHPLIB-214](https://jira.mongodb.org/browse/PHPLIB-214).
