### ISSUE TITLE
Hint feature is not implemented?

### ISSUE THREAD

**Issue by bigdaddymax** [mongodb/mongo-php-library#232]
Hi, is there a way to force Mongo to use specific index when doing find() or findOne()? 

It seems that hint option is not implemented in this lib.

Thanks.

**Comment by jmikola** [comment]
Cross-referencing with https://github.com/mongodb/mongo-php-library/pull/214. The SPEC ticket I referred to there is currently in progress being reviewed internally, after which drivers will end up adding "hint" options to these methods.

At present, a hint needs to be specified via the `modifiers` option. For instance:

```
$collection->find(
    ['x' => 1],
    ['modifiers' => ['$hint' => 'index_name']],
);
```

**Comment by jmikola** [comment]
Just to update, "hint" will become a first-class option with [PHPC-783](https://jira.mongodb.org/browse/PHPC-783). Once the change lands in the PHP and HHVM extensions, we'll add it to the library.

Please watch that issue for updates.
