### ISSUE TITLE
GridFS Bucket should be able to accept a MongoDB\Client

### ISSUE THREAD

**Issue by rpavlicek** [mongodb/mongo-php-library#236]
Apologies if this is already done (or planned).

The MongoDB\GridFS\Bucket class only accepts a manager and db as parameters to its constructor. Since this lives in the same library as the MongoDB\Client, either:

1) It can accept a MongoDB\Client object instead of MongoDB\Driver\Manager (or both). Or subclass Bucket with a class that works with MongoDB\Client instead...?
2) Have a 'friendlier' method in MongoDB\Client to access the driver manager (other than __debuginfo)

**Comment by wrey75** [comment]
This should be not an issue anymore. The `MongoDB\Client` provides (in the last versions) a method `getManager()`. This method returns the manager itself.

**Comment by jmikola** [comment]
Cross-referencing with [PHPLIB-186](https://jira.mongodb.org/browse/PHPLIB-186). Thanks for pointing that out, @wrey75.
