### ISSUE TITLE
Library events

### ISSUE THREAD

**Issue by myovchev** [mongodb/mongo-php-library#237]
Hey guys,

I quick question - do you plan to implement at some point any kind of event management into the library, which IMO will be priceless in development environment (and not only).

My question is based on the fact I'm planning to use the library extensively in micro-services architecture so  I did a fresh Silex 2.x integration (already contributed to the great Silex community), but I'm missing a native library PSR-3 logging support. It would be easy to be implemented if I'm able to hook into library events. 

Cheers!

**Comment by jmikola** [comment]
We do plan to implement the [Command Monitoring specification](https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst) in an upcoming version of the extension (see: [PHPC-349](https://jira.mongodb.org/browse/PHPC-349)). That will allow read, write, and command operations to be logged by some userland function.

Once implemented, the library could then implement some bridge for a PSR-3 logger; however, we've yet to spec out any library API around this spec.

**Comment by myovchev** [comment]
@jmikola some great news, thanks for the prompt response. I'll follow the ticket as per your suggestion.
