### ISSUE TITLE
Collection::findOneAndUpdate not respecting typeMap set in client

### ISSUE THREAD

**Issue by rikkiloades** [mongodb/mongo-php-library#256]
I have set a typeMap in the global client:

```
$connectionString = '...'; // omitted actual value
$db = 'mydb';
$collection = 'mycollection';
$uriOptions = [];
$driverOptions = ['typeMap' => ['root' => 'array', 'document' => 'array', 'array' => 'array']];
$mongoDb = new \MongoDB\Client($connectionString, $uriOptions, $driverOptions);
```

Then when i call `findOneAndUpdate`:

```
$mongoDb->selectDatabase($db)->selectCollection($collection)->findOneAndUpdate($criteria, $updates, $options);
```

I get back a `stdClass` object at the root level. I was expecting an array. The old pecl/mongo driver used to return an `array` and the typeMap is not being respected to allow me to get it back just like the old driver.

I appreciate and understand the move to BSONDocument and BSONArray and if this were a new project I would not be setting that typemap and taking advantage of the new BSON serialisation behaviours. However there is a fairly large codebase that is sitting on top of the old behaviour and relying on it and updating all that code to use the new BSON behaviour is unpractical.

**Comment by lindelius** [comment]
This is a problem in the driver. See @136 for more info

**Comment by jmikola** [comment]
As @lindelius said, this is waiting on functionality in the driver ([PHPC-314](https://jira.mongodb.org/browse/PHPC-314)).

For the time being, you will need to recursively walk the `value` field (i.e. result document) and cast `stdClass` objects to arrays. I do realize that's an unfortunate work-around.

**Comment by jmikola** [comment]
@lindelius, @rikkiloades: Please see my idea in [this comment](https://jira.mongodb.org/browse/PHPLIB-112?focusedCommentId=1395992&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1395992). I think we can come up with a stop-gap solution based on the current driver limitations that should satisfy most users.

The restriction would be that the "root" and "document" mappings would need to be the same and also match a list of classes/types we know how to handle (e.g. library classes, stdClass, or PHP array).
