### ISSUE TITLE
Implementing TTL (expiration) with GridFS

### ISSUE THREAD

**Issue by rpavlicek** [mongodb/mongo-php-library#259]
I took the liberty of modifying the source code (my own local) to allow GridFS to have TTL expirations in both the files and chunks collections. This only requires a small change, however it only works with the TTL flavor "expireAfterSeconds" : 0 (otherwise it gets complex).

I realize this is not standard, but (perhaps?) this could be added to this library as an extra feature. If you prefer I submit this via github as a pull request, let me know..

```
Index: external/vendor/mongodb/mongodb/src/GridFS/CollectionWrapper.php
===================================================================
--- external/vendor/mongodb/mongodb/src/GridFS/CollectionWrapper.php	(revision 147982)
+++ external/vendor/mongodb/mongodb/src/GridFS/CollectionWrapper.php	(working copy)
@@ -230,12 +230,15 @@
     private function ensureChunksIndex()
     {
         foreach ($this->chunksCollection->listIndexes() as $index) {
-            if ($index->isUnique() && $index->getKey() === ['files_id' => 1, 'n' => 1]) {
+            if ($index->isUnique() && $index->getKey() === ['files_id' => 1, 'n' => 1, 'expireAt' => 1]) {
                 return;
             }
         }
 
         $this->chunksCollection->createIndex(['files_id' => 1, 'n' => 1], ['unique' => true]);
+
+        // TTL support
+        $this->chunksCollection->createIndex(['expireAt' => 1], ['expireAfterSeconds' => 0]);
     }
 
     /**
@@ -244,12 +247,15 @@
     private function ensureFilesIndex()
     {
         foreach ($this->filesCollection->listIndexes() as $index) {
-            if ($index->getKey() === ['filename' => 1, 'uploadDate' => 1]) {
+            if ($index->getKey() === ['filename' => 1, 'uploadDate' => 1, 'expireAt' => 1]) {
                 return;
             }
         }
 
         $this->filesCollection->createIndex(['filename' => 1, 'uploadDate' => 1]);
+
+        // TTL support
+        $this->filesCollection->createIndex(['expireAt' => 1], ['expireAfterSeconds' => 0]);
     }
 
     /**
Index: external/vendor/mongodb/mongodb/src/GridFS/WritableStream.php
===================================================================
--- external/vendor/mongodb/mongodb/src/GridFS/WritableStream.php	(revision 147982)
+++ external/vendor/mongodb/mongodb/src/GridFS/WritableStream.php	(working copy)
@@ -47,6 +47,8 @@
      *  * metadata (document): User data for the "metadata" field of the files
      *    collection document.
      *
+     *  * expireAt (MongoDB\BSON\UTCDatetime): Expiration date
+     *
      * @param CollectionWrapper $collectionWrapper GridFS collection wrapper
      * @param string            $filename          Filename
      * @param array             $options           Upload options
@@ -75,6 +77,11 @@
             throw InvalidArgumentException::invalidType('"metadata" option', $options['metadata'], 'array or object');
         }
 
+        // TTL support
+        if (isset($options['expireAt']) && ! ($options['expireAt'] instanceof UTCDatetime) ) {
+            throw InvalidArgumentException::invalidType('"expireAt" option', $options['expireAt'], 'MongoDB\BSON\UTCDatetime');
+        }
+
         $this->chunkSize = $options['chunkSizeBytes'];
         $this->collectionWrapper = $collectionWrapper;
         $this->buffer = fopen('php://temp', 'w+');
@@ -86,7 +93,7 @@
             'filename' => (string) $filename,
             // TODO: This is necessary until PHPC-536 is implemented
             'uploadDate' => new UTCDateTime(floor(microtime(true) * 1000)),
-        ] + array_intersect_key($options, ['aliases' => 1, 'contentType' => 1, 'metadata' => 1]);
+            ] + array_intersect_key($options, ['aliases' => 1, 'contentType' => 1, 'metadata' => 1, 'expireAt' => 1]);
     }
 
     /**
@@ -220,6 +227,9 @@
             'data' => new Binary($data, Binary::TYPE_GENERIC),
         ];
 
+        // Add TTL support to the chunk collection
+        $toUpload += array_intersect_key($this->file, ['expireAt' => 1]);
+
         hash_update($this->ctx, $data);
 
         $this->collectionWrapper->insertChunk($toUpload);
```

**Comment by jmikola** [comment]
The library's schema for the `fs.files` and `fs.chunks` collections in the library needs to conform to the cross-driver [GridFS specification](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst). Modifying `fs.chunks` is out of the question here, so we can't consider this patch.

A potential issue with this implementation is that [MongoDB's TTL indexes](https://docs.mongodb.com/master/tutorial/expire-data/) have no consistency across multiple collections. Although an edge case, it's possible that a file's chunks might be removed before its `fs.files` document.

I think a better approach for your own application would be to manually create a `metadata.expiresAt` TTL index on the `fs.files` collection and then implement a separate batch script to check for and delete orphan chunks (where their `files_id` has no matching document in `fs.files` collection). Relying on the TTL index to delete documents in `fs.files` should work just fine, as the `fs.files` document is the only authority on a file's existence (as far as the Bucket is concerned). That batch script could be scheduled as a cron job.

It's certainly up to you if you'd like to maintain this modification in your own fork; however, the above implementation should obviate the need for any patch and also avoid the possible edge case.

**Comment by rpavlicek** [comment]
Based on the GridFS specification, I see that you cannot allow the patch since it breaks the chunks definition:

  "_id" : <ObjectId>,
  "files_id" : <TFileId>,
  "n" : <Int32>,
  "data" : <binary data>

Your suggested implementation was a consideration of ours, however it is not feasible given our innumerable dynamic databases. On top of that it would add more complexity to the production environment. In the end we decided expirations were the way to go. The system is designed to handle chunks missing when a file is retrieved (exception/error handling).

Given that our situation may not be unique, perhaps this PHP Library could be written to allow more sub-classing instead of direct modification. This would make it easier for users to add their own behavior without having to merge direct changes. Changing class functions/members from private to protected should not violate the GridFS spec.

Please see my request/comment: 

[Extensive use of private methods instead of protected](https://github.com/mongodb/mongo-php-library/issues/235)
