### ISSUE TITLE
Exact Match on the Embedded Document?

### ISSUE THREAD

**Issue by subversivo58** [mongodb/mongo-php-library#260]
[QUESTION]

in native mongodb search this for exact fild:

    db.users.find( { favorites: { artist: "Picasso", food: "pizza" } } )

php in this library have this function or equivalent?

    $request = (new MongoDB\Client)->{'database'};
    $res = $request->{'collection'}->find( ['favorites'=>['artist'=>'Picasso]] );

or... *Equality Match on Fields within an Embedded Document*

    $request = (new MongoDB\Client)->{'database'};
    $res = $request->{'collection'}->find( ['favorites.artist'=>'Picasso'] );

this methods is describle on [manual](https://docs.mongodb.com/manual/tutorial/query-documents/)

**Comment by subversivo58** [comment]
ok, my question was related to version 1.0.2 ... I updated to 1.0.3 but:

only match to  *Equality Match on Fields within an Embedded Document* in findOne

    $request = (new MongoDB\Client)->{'database'};
    $res = $request->{'collection'}->findOne( ['favorites.artist'=>'Picasso'] );

I would ask to close the issue but still do not know if *Exact Match on the Embedded Document* is supported?

I tried using find and findOne unsuccessfully

this return "null":

    $request = (new MongoDB\Client)->{'database'};
    $res = $request->{'collection'}->findOne( ['favorites' => ['artist'=>'Picasso']] );

this return "{}":

    $request = (new MongoDB\Client)->{'database'};
    $res = $request->{'collection'}->find( ['favorites' => ['artist'=>'Picasso']] );

**Comment by lindelius** [comment]
Please post an example document

**Comment by subversivo58** [comment]
@lindelius I do not understand what you mean to post an example?

I believe there is no need to "post" an example since the first two comments have a request to the database and query the collection as examples.

**Comment by lindelius** [comment]
Yes, but I do not understand what your issue is. All query forms that are supported in MongoDB are also supported by the library, and all the example queries that you have posted are valid and should return matching documents. If you get nothing back from them when you expect to get one or more documents, then you are not querying the right fields.

**Comment by subversivo58** [comment]
When I started this issue I was using version 1.0.2. I am updated to version 1.0.3.

    // create and save object
    $obj = new \stdClass;
    $a   = new \stdClass;

    $a->name   = 'Lauro';
    $a->status = 'active';
    $a->code   = 12345;
    $a->mail   = 'lauromail@domain.com';

    $obj->account = $a;

    // assume database name is "localtest"
    $request = (new MongoDB\Client)->{'localtest'};

    // assume collection name is "users"
    $insert = $request->{'users'}->insertOne( $obj );

this result in new object in mongodb like:

    {
        "_id": "mongoObjectId",
        "account": {
            "name": "Lauro",
            "status": "active",
            "code": 12345,
            "mail": "lauromail@domain.com"
        }
    }

ok. to receive | recover this object according to [documentation](https://docs.mongodb.com/manual/tutorial/query-documents/#query-on-embedded-documents) using:

**A: Exact Match on the Embedded Document**
**B: Equality Match on Fields within an Embedded Document**

the following methods using **find** returns **cursor**:

**method A:**

    $request = (new MongoDB\Client)->{'localtest'};
    $res = $request->{'users'}->find( ['account'=>['name'=>'Lauro']] );

    var_dump($res);

    /**
     output

    object(MongoDB\Driver\Cursor)

    */

**method B:**

    $request = (new MongoDB\Client)->{'localtest'};
    $res = $request->{'users'}->find( ['account.name'=>'Lauro'] );

    var_dump($res);

    /**
     output

     object(MongoDB\Driver\Cursor)

   */


To retrieve object **BSONDocument** by **findOne** using **method B**, like:

    $request = (new MongoDB\Client)->{'localtest'};
    $res = $request->{'users'}->findOne( ['account.name'=>'Lauro'] );

    var_dump($res);

    /**
     output (that this functional, this really returning the object)

     object(MongoDB\Model\BSONDocument)

    {
        "_id": {},
        "account": {
            "name": "Lauro",
            "status": "active",
            "code": 12345,
            "mail": "lauromail@domain.com"
        }
    }

    // I could use the result

    echo $res->account->mail; //output   lauromail@domain.com

    */

I believe that I was not clear enough in previous reviews.

I want to know is if the following query should not return an object?

**method A:**

    $request = (new MongoDB\Client)->{'localtest'};
    $res = $request->{'users'}->findOne( ['account'=>['name'=>'Lauro']] );

    var_dump($res);

    /**
     output 

     NULL

    */

if **findOne** runs in the structure of the method "B" because it does not run in the method "A" ?

**Comment by lindelius** [comment]
If you are not matching all of the fields in the embedded document you must speficy the fields using dot-notation, instead of a nested array. To match documents using the nested array aproach you must match on all of the fields.

For example, if you have a document that looks like
```
{
    _id: ObjectID('...'),
    embedded: {
        a: 'a-value',
        b: 'b-value',
        c: 'c-value'
    }
}
```

You can match this document by using either
```php
$doc = $collection->findOne([
    'embedded' => [
        'a' => 'a-value',
        'b' => 'b-value',
        'c' => 'c-value'
    ]
]);
```
or
```php
$doc = $collection->findOne(['embedded.a' => 'a-value']);
```

**Comment by subversivo58** [comment]
ok. your example is equal my example... see:

    // your example:
    $doc = $collection->findOne(['embedded.a' => 'a-value']);
    
    // my example:
    $res = $request->{'users'}->findOne( ['account.name' => 'Lauro'] );

both return exactly one object **"object(MongoDB\Model\BSONDocument)"**

This method is described in [the documentation](https://docs.mongodb.com/manual/tutorial/query-documents/#query-on-embedded-documents) as **"Equality Match on Fields within an Embedded Document"** see:

![equality-match](https://cloud.githubusercontent.com/assets/6475273/19017862/31584cc4-8822-11e6-8035-a5369f876dcc.PNG)


This works great! But...

My question as described in the text is: **Exact Match on the Embedded Document?**

This method is described in [the documentation](https://docs.mongodb.com/manual/tutorial/query-documents/#query-on-embedded-documents) as **"Exact Match on the Embedded Document"** see:

![query-exact-match](https://cloud.githubusercontent.com/assets/6475273/19017912/fa998092-8824-11e6-81ba-cc555780f631.PNG)


Using this structure as I did above:

    $res = $request->{'users'}->findOne( [ 'account' => [ 'name' => 'Lauro' ] ] );

This return **NULL**

if I used this structure with his example would look like this:

    $doc = $collection->findOne( [ 'embedded' => [ 'a' => 'a-value' ] ] );

which also return **NULL**


So I ask again:

The method described as **Exact Match on the Embedded Document**  exists in this library?


If this method exists in the library would not be like this:

    // original structure mongodb
    db.users.find( { favorites: { artist: "Picasso", food: "pizza" } } )

    // one equivalent in PHP ???
    $doc = $collection->findOne( [ 'favorites' => [ 'artist' => 'Picaso', 'food' => 'pizza' ] ] );


Sorry insistence. But the [documentation](https://docs.mongodb.com/manual/tutorial/query-documents/#query-on-embedded-documents) describes these two methods and the method I mentioned (**Exact Match on the Embedded Document**) I'm apparently running correctly but returns NULL.

The library support this method? Y/N

If NO. Excuse me for lengthy discussion. Close the question.

**Comment by alcaeus** [comment]
> The method described as Exact Match on the Embedded Document exists in this library?

This has nothing to do with the library. As the name suggests, the document is only returned if there is an **exact** match on the embedded document. Taking your example query: `$res = $request->{'users'}->findOne( [ 'account' => [ 'name' => 'Lauro' ] ] );` it will only return documents of the following structure:
```
{
...
account: {
    name: 'Lauro'
}
...
```

If the document contains an additional field (as it does in your sample document), it is no longer an exact match and so won't be returned. If you want to query using an exact match, you'll have to specify the entire embedded document. So, for your example above, the query would have to be:
```
$res = $request
    ->{'users'}
    ->findOne([
        'account' => [ 
            'name' => 'Lauro',
            'status' => 'active',
            'code' => 12345,
            'mail' => 'lauromail@domain.com',
        ]
    ])
;
```

**Comment by lindelius** [comment]
I don't think you understood my answer, or the documentation. If you want to "equal match" a document you *must* specify all the embedded fields, and you have to do it in the right order. Just like in my example, and just like @alcaeues wrote in his. The difference between my example and yours is that you try to equal match a document by specifying just one of the fields. This does not work. You always have to specify all the fields in order for the equality match to actually match the document.

**Comment by subversivo58** [comment]
Thank you @alcaeus and @lindelius  the last two comments make it clear that I should in my query  specify all fields and in due order and not just an item.

Now it was clear to me. I appreciate the patience.

**Comment by lindelius** [comment]
No problem, @subversivo58  :)

**Comment by jmikola** [comment]
Thanks for fielding this question, @lindelius and @alcaeus. I think it can be closed now.

@subversivo58: In the future, it may be helpful to use [`MongoDB\Driver\Cursor::toArray()`](http://php.net/manual/en/mongodb-driver-cursor.toarray.php) when dumping results of a cursor. In one of your earlier posts, you pasted:

```
/**
 output

object(MongoDB\Driver\Cursor)
*/
```

Had you dumped the cursor's contents, it would have shown that the first query, which was matching by an incomplete, exact document, was returning no results. The `findOne()` examples wouldn't have been needed.
