### ISSUE TITLE
\MongoDuplicateKeyException missing

### ISSUE THREAD

**Issue by rikkiloades** [mongodb/mongo-php-library#261]
In the new library and/or driver if you try to insert a document which results in a duplicate key error then you get the following exception:

```
object(MongoDB\Driver\Exception\BulkWriteException)#824 (8) {
    ["message":protected]=> string(96) "E11000 duplicate key error collection: app.exchangeRates index: _id_ dup key: { : "2016-10-05" }"
    ["string":"Exception":private]=> string(0) ""
    ["code":protected]=> int(0)
    ["file":protected]=> string(81) ".../mongo-php-library-1.0.2/src/Operation/InsertOne.php"
    ["line":protected]=> int(86)
    ["trace":"Exception":private]=> array(16) { ... }
}
```

The problem with this is if you want to use the exception to then do some further processing the only way you can determine it was a duplicate key exception is to do some string matching on the message. This is because the code always appears to be 0 and nothing else about the exception identifies it as a duplicate key error. Its not particularly robust to rely on error messages, they can and do change over time. Given how much this new library has changed things means relying on this is rather fragile.

The old driver in the early versions throw a `\MongoCursorException` which set the code on the exception to 11000. Later versions introduced a specific exception subclass called `\MongoDuplicateKeyException`. Both of these were much more robust ways to detect and deal with specific types of error. See http://php.net/manual/en/book.mongo.php for more details on these exceptions.

**Comment by jmikola** [comment]
[PHPLIB-225](https://jira.mongodb.org/browse/PHPLIB-225) is opened as a tracking issue. Recent improvements in libmongoc ([CDRIVER-709](https://jira.mongodb.org/browse/CDRIVER-709)) may make this possible.

I expect the extension would still present all write errors as a [BulkWriteException](http://php.net/manual/en/class.mongodb-driver-exception-bulkwriteexception.php), but it should be possible for the library to rely on the now-consistent error code to translate the error into its own DuplicateKeyException.

**Comment by jmikola** [comment]
Closing this, but feel free to follow [PHPLIB-225](https://jira.mongodb.org/browse/PHPLIB-225) for updates. The most recent development was that we were still prototyping this in https://github.com/mongodb/mongo-php-library/pull/418.
