### ISSUE TITLE
GridFS classes undocumented?

### ISSUE THREAD

**Issue by fpiraneo** [mongodb/mongo-php-library#263]
I need to use GridFS classes to store / retrieve files in MongoDB but the related classes seems not be documented. Any help is appreciated.

**Comment by moderndeveloperllc** [comment]
@fpiraneo This is being tracked here: https://jira.mongodb.org/browse/PHPLIB-221. There have been some [work on GridFS recently](https://github.com/mongodb/mongo-php-library/pulls?utf8=✓&q=is%3Apr%20GridFS), so it's possible they wanted to finish that up before documenting.

**Comment by fpiraneo** [comment]
Ok perfect, thanks!

**Comment by fpiraneo** [comment]
Mark, just some questions about the library:
- Can I consider it stable and ready for production?
- There are absolutely no example about how to work with GridFS and mongo-php-lib? Also a preview to point me at the right direction would be great!
Thank you again.

**Comment by moderndeveloperllc** [comment]
@fpiraneo Hard to say. I'm in a multi-month dev cycle right now, so I'm only betting that it will be truly "solid" by next summer! It's not really a question of if the library is ready, but the driver to be honest. The library is purely optional, and none of the classes are `final`, so you can always tweak around issues. The 1.2.0 driver makes [lots of changes and improvements](https://github.com/mongodb/mongo-php-driver/releases), but it might be a while before it goes final.

Unless @jmikola or @schmalliso have something elsewhere, I can't find any GridFS docs specific to this library. The only thing I could suggest right now is to look over the docs and examples in the main docs while looking at the classes here and play around.

**Comment by fpiraneo** [comment]
@moderndeveloperllc 
So, let me understand because I'm a bit confused: The new mongodb driver is far to be stable (next summer you wrote!) but the old mongo driver is already deprecated and on the official php documentation you can find the invitation to use the new driver with the mongo-php-library that - at the time - is in development stage with some undocumented features, I'm right?

At this point your idea will be apreciated: Do you think is the case to develop the first version of a new application with OLD mongo drivers (deprecated because old BUT complete, well documented and stable) and wait next summer to let you (and your team) finish and document the high level library and the guys working on the drivers to reach a stable release to migrate to new driver & library?

Thank you very much for your answers! :-)

**Comment by moderndeveloperllc** [comment]
Sorry for the confusion. I'm just a dev like you - not any part of the MongoDB team. I just troll around these tickets quite a bit :-) The mongodb extension (from my perspective) feels as stable as any other software driver out there. The stable version is 1.1.8 and is installable from PECL, etc. As a fellow developer, it would be hard to recommend using the deprecated drivers. It would be quite a bit of work to go back and change out the calls for a v2, but that's just my opinion.

**Comment by fpiraneo** [comment]
Nothing to sorry about! :-) Thank you very much again!
