### ISSUE TITLE
Aggregation Framework - $out - not master

### ISSUE THREAD

**Issue by Roycohen** [mongodb/mongo-php-library#266]
Hi Guys,

Don't think it is a bug, but rather misconfiguration or something that I can't find.
I'm trying to make aggregation pipeline where my last stage is $out.
I'm running it and I'm almost sure that I have a connection to the master, but for some reason it failed with the following error:

Error while executing mongo aggregation: failed to create temporary $out collection 'statslive.tmp.agg_out.8': { ok: 0.0, errmsg: "not master", code: 10107 }Code: 16994

This is my options while creating new client.
new \MongoDB\Driver\ReadConcern(MongoDB\Driver\ReadConcern::LOCAL)
new \MongoDB\Driver\ReadPreference(\MongoDB\Driver\ReadPreference::RP_PRIMARY)

Also, does the read concern and preference is something that related?
I have Cluster with 5 Shards and each shard has 3 replica sets.

Thanks for the help.

**Comment by jmikola** [comment]
What versions of the extension and library are you using? Additionally, what version(s) of MongoDB are at play with the shard cluster?

Can you share a stand-alone script that reproduces this error?

Lastly, can you investigate what ReadPreference (if any) is being passed when `Aggregate::execute()` invokes [`Server::executeCommand()`](https://github.com/mongodb/mongo-php-library/blob/1.0.3/src/Operation/Aggregate.php#L168)?

The `Collection::aggregate()` method has some logic to check if the last pipeline operator is `$out`. If so, it will hard-code a primary read preference, which we expect libmongoc to set as a `$readPreference` field on the command document. If you [profile queries](https://docs.mongodb.com/manual/tutorial/manage-the-database-profiler/) on the mongos node(s), you should be able to check for that in the `aggregate` command document.

**Comment by jmikola** [comment]
@Roycohen: Is there follow up for the questions above, or should I close this out?

**Comment by Roycohen** [comment]
Hi @jmikola,

Have a lot of things lately, and I've tried to it in another way.
I think I'm using secondary_prefered.
I will be able to investigate it in the upcoming days.
