### ISSUE TITLE
Persistent connections?

### ISSUE THREAD

**Issue by putc** [mongodb/mongo-php-library#277]
Hello,

With other PHP database drivers, for example some databases with PDO, you can create persistent connection (pools) that are kept alive after a PHP script finishes so the next script doesn't have to make another HTTP handshake and authorization with the database.

I have found it very hard to find any information on this matter regarding the new MongoDB driver, but from the timings found while debugging some PHP scripts I am guessing that the MongoDB driver and this library do not by default cache connections. Is this correct? If so, is there a way I can turn on persistent connections and specify a maximum pool size, similar to how one would do it with MongoDB and NodeJS?

Sorry to ask here, but I wouldn't have if I had found anything on Google, StackOverflow etc.

Thank you very much

(Also sorry, I don't know how to mark this as a question)

**Comment by moderndeveloperllc** [comment]
All connections are persistent by default: http://php.net/manual/en/mongodb.connection-handling.php

**Comment by putc** [comment]
@moderndeveloperllc Thank you very much for that link.

So the current stable driver version (1.1.9) can persist connections but not authentication information and topology. I have installed 1.2.0alpha3 just for testing and it really increases the performance since it can persist additional information. I will stick with the stable channel, but it is good to know these features are just around the corner.
