### ISSUE TITLE
is_first_key_operator() fails to properly inspect ArrayObject instances

### ISSUE THREAD

**Issue by zamrih** [mongodb/mongo-php-library#286]
Hi,

Not a mongo-php-library issue per se but HHVM fails to return an array of properties when get_object_vars is used with an ArrayObject instance.
\MongoDB\Model\BSONDocument extending ArrayObject is therefore failing to verify the "is_first_key_operator" function.

`$document = get_object_vars($document);`

Could be quickly fixed by using getArrayCopy in case of an ArrayObject instance.

`$document = $document instanceof \ArrayObject ? $document->getArrayCopy() : get_object_vars($document);`

An (object) (array) type casting could do the trick but would probably be a less robust fix.

Regards,

**Comment by jmikola** [comment]
I can confirm this isn't specific to HHVM. [`get_object_vars()`](http://php.net/get_object_vars) returns an empty array on an ArrayObject instance in PHP as well:

```
$a = new ArrayObject([1,2,3]);

var_dump(get_object_vars($a));
var_dump($a->getArrayCopy());
```

Output:

```
array(0) {
}
array(3) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
}
```

May I ask how you encountered this error? Were you using a BSONDocument instance as a replacement document with `MongoDB\Collection::replaceOne()`?

Aside from [`is_first_key_operator()`](https://github.com/mongodb/mongo-php-library/blob/1.1.0-alpha1/src/functions.php#L71), we also use `get_object_vars()` in [`generate_index_name()`](https://github.com/mongodb/mongo-php-library/blob/1.1.0-alpha1/src/functions.php#L42) for generating the name for an index specification document. I believe the most appropriate solution here would check if an object implements [MongoDB\BSON\Serializable](http://php.net/manual/en/class.mongodb-bson-serializable.php) and use the return value of its `bsonSerialize()` method if so. That is what we currently do in [`extract_id_from_inserted_document()`](https://github.com/mongodb/mongo-php-library/blob/1.1.0-alpha1/src/functions.php#L24).

**Comment by jmikola** [comment]
Opened [PHPLIB-239](https://jira.mongodb.org/browse/PHPLIB-239) to track this.

**Comment by zamrih** [comment]
Hello jmikola,

I think you're mistaken with the get_object_vars behavior.
You didn't pass an associative array to the ArrayObject constructor in the provided sample and get_object_vars does return as it should an empty array.

About how the error was encountered, it was indeed when using a BSONDocument instance but not specifically with MongoDB\Collection::replaceOne().

The BSONDocument instance is used by the alcaeus/mongo-php-adapter package ( https://github.com/alcaeus/mongo-php-adapter/blob/1.0.6/lib/Mongo/MongoCollection.php#L380 )

The BSONDocument is instanciated when ensuring the correct type is used ( https://github.com/alcaeus/mongo-php-adapter/blob/1.0.6/lib/Alcaeus/MongoDbAdapter/TypeConverter.php#L149 ).

The package intent is to keep the legacy driver API available even when using the new driver stack ( via the mongodb/mongo-php-library package ).

You're right, I did notice get_object_vars is used with both is_first_key_operator() and generate_index_name().
From what I understand, both expect to check an associative array like variable properties ( a BSONDocument in this case ).

As of the bsonSerialize() use, I agree with you. It makes more sense to do that prior to getting back the document properties in any other way ... or even throwing an invalid argument exception as a last resort.

Thanks for the fix!

Regards,

**Comment by jmikola** [comment]
> You didn't pass an associative array to the ArrayObject constructor in the provided sample and get_object_vars does return as it should an empty array.

@zamrih: Ah, I didn't realize it was specific to associative arrays. I added some more test cases to the HHVM issue that you opened: https://github.com/facebook/hhvm/issues/7510#issuecomment-264160030

In any event, the referenced PR should resolve this for the library's needs.

/cc @alcaeus: this is relevant to mongo-php-adapter
