### ISSUE TITLE
Remove won't execute on documents

### ISSUE THREAD

**Issue by joyebright** [mongodb/mongo-php-library#287]
Hi @jmikola  ,
there are two different id into UserCollection , by the following structure : 
```
{ "_id" : ObjectId("5838176ff74ea10b2c005951"), "name" : "Javad PourMostafa ", "number" : "09111500816", "email" : "java
d.pourmostafa@gmail.com" }                                                                                              
{ "_id" : ObjectId("583818d6f74ea10b2c005952"), "name" : "Kami DarvizhNezhad", "number" : "09112635656", "email" : "kami
@yahoo.com" }         
```                     
now by the PHP , I want to delete one of the document , based on _id and I have the following code
```
$db = $client->phonebook; //use phonebook
                $userCollection = $db->userCollection;
                $data = array('_id' => $_GET['id']);
                $deleteResult = $userCollection->deleteOne($data);    
```                                                                         
interestingly , I won't get any errors but deletion , I meant removing won't work at this point , what should i do?

**Comment by lindelius** [comment]
In order to delete documents that use MongoDB ObjectIDs as their primary ID you have to specify them as such when deleting them

```php
use MongoDB\BSON\ObjectID;

$deleteResult = $userCollection->deleteOne(['_id' => new ObjectID($_GET['id'])]);
```

**Comment by joyebright** [comment]
yeah , tnq , I got it !
first I have tried this and cause of didn't use ObjectID location , I meant 

> use MongoDB\BSON\ObjectID;
I have tried another method which is called : 
`$deleteResult = $userCollection->findOneAndDelete($data);`
and it works properly 
by the way tnq @lindelius

**Comment by lindelius** [comment]
No problem!

Glad I could help :)
