### ISSUE TITLE
Undefined index: wrapper_data

### ISSUE THREAD

**Issue by prolic** [mongodb/mongo-php-library#299]
```
$bucket = $this->client->selectDatabase($this->dbName)->selectGridFSBucket([
    'bucketName' => 'some_name',
    'readConcern' => $this->readConcern,
]);

try {
    $stream = $this->createStream();
    $bucket->downloadToStream($aggregateId, $stream);
} catch (FileNotFoundException $e) {
    return null;
}

var_dump($bucket->getFileDocumentForStream($stream)); die; // this fails
var_dump($bucket->getFileIdForStream($stream)); die; // this fails, too
```

Undefined index: wrapper_data

.../vendor/mongodb/mongodb/src/GridFS/Bucket.php:250

**Comment by prolic** [comment]
ping @jmikola

**Comment by jmikola** [comment]
The `$stream` parameter for `getFileDocumentForStream()` and `getFileIdForStream()` must be a GridFS stream. That said, I currently only check that the argument is a stream resource and assume that "wrapper_data" exists in its metadata (see: [here](https://github.com/mongodb/mongo-php-library/blob/b4338692387082f941de464d09eba237fa8823d1/src/GridFS/Bucket.php#L524)). I'll add an additional `isset()` check so we can throw an exception instead of this warning.

**Comment by prolic** [comment]
Thanks for your information @jmikola.
But this leads to a next problem, see here:

```
$bucket = $this->client->selectDatabase($this->dbName)->selectGridFSBucket([
    'bucketName' => 'some_name',
    'readConcern' => $this->readConcern,
]);

try {
            $gridFsStream = $bucket->openDownloadStream($aggregateId);
        } catch (FileNotFoundException $e) {
            return null;
        }

$metadata = $bucket->getFileDocumentForStream($gridFsStream); // works
$createdAt = $metadata->metadata->created_at->toDateTime(); // works
$stream = stream_copy_to_stream($gridFsStream, $this->createStream()); // fails
```

Does the last line fail because I accessed the metadata already? rewind seems not to be possible. What the good way to access metadata and file content? Or does it simply requires two queries (That would be not the optimal solution)?

**Comment by jmikola** [comment]
How does `stream_copy_to_stream()` fail?

Readable streams do not yet support seeking, so they can only be read once; however, your example doesn't appear to read `$gridFsStream` multiple times.

**Comment by prolic** [comment]
I got this:

```
PHP Warning:  fclose(): supplied resource is not a valid stream resource in /home/sasa/code/mongodb-snapshot-store/vendor/mongodb/mongodb/src/GridFS/ReadableStream.php on line 78
```

**Comment by jmikola** [comment]
Can you reproduce the error with the following script?

```php
<?php

require 'vendor/autoload.php';

function createStream($data = '')
{
    $stream = fopen('php://temp', 'w+b');
    fwrite($stream, $data);
    rewind($stream);

    return $stream;
}

$bucket = (new MongoDB\Client)->test->selectGridFSBucket();
$bucket->drop();

$id = $bucket->uploadFromStream('file', createStream('foo'), [
    '_id' => 1,
    'metadata' => ['created_at' => new MongoDB\BSON\UTCDateTime],
]);

var_dump($id);

$stream = $bucket->openDownloadStream(1);

$metadata = $bucket->getFileDocumentForStream($stream);
$createdAt = $metadata->metadata->created_at->toDateTime();

$dest = createStream();

printf("Copied %d byte(s)\n", stream_copy_to_stream($stream, $dest));
var_dump(stream_get_contents($dest, -1, 0));
```

This outputs:

```
int(1)
Copied 3 byte(s)
string(3) "foo"
```

None of the functions in ReadableStream should leave the `$buffer` property in a closed state except for `close()`, and I don't see why the stream wrapper would call that multiple times in your example.

> rewind seems not to be possible. What the good way to access metadata and file content? Or does it simply requires two queries (That would be not the optimal solution)?

Rewinding and seeking through GridFS streams is not yet supported ([PHPLIB-213](https://jira.mongodb.org/browse/PHPLIB-213)); however, accessing the metadata (i.e. `fs.files` document) for a stream does not require reading the file contents (i.e. `fs.chunks` documents).

**Comment by prolic** [comment]
@jmikola Your test-script works, can you check my implementation here? https://github.com/prooph/mongodb-snapshot-store/blob/implementation/src/MongoDBSnapshotStore.php

I cannot find the bug - maybe I'm stupid or there's still a problem.

**Comment by jmikola** [comment]
@prolic: Can you provide me with some instructions for reproducing the error with that code? Assuming it's just a matter of cloning the repository and running `composer update`, a line to execute PHPUnit and filter down to a specific test case would be great.

**Comment by prolic** [comment]
@jmikola Ok, I got it working now!
Still don't know what going on, but it works! :-)

If you want to see the difference:
https://github.com/prooph/mongodb-snapshot-store/compare/bdc19b1...fd4b586

Thanks for your help, mate!

**Comment by jmikola** [comment]
I assume this was fixed by:

```diff
-            stream_copy_to_stream($gridFsStream, $destination);
-            $aggregateRoot = unserialize(stream_get_contents($destination));
+            stream_copy_to_stream($stream, $destination);
+            $aggregateRoot = unserialize(stream_get_contents($destination, -1, 0));
```

`stream_copy_to_stream()` reads from `$gridFsStream` and writes to `$destination`, after which both streams' positions are advanced. By default, `stream_get_contents()` reads from the current position onward. Specifying `0` as the final argument rewinds its position to read the entirety of `$destination`.
