### ISSUE TITLE
cant install with php 7.0.8 in Ubuntu 16 platform 

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb/mongo-php-library#308]
I cant install mongodb driver for php 7.0.8 in Unbuntu 16 with pecl install mongodb it return me pecl command not found

**Comment by Visualq** [comment]
This is not a library problem. 

Try installing pecl: 

sudo apt-get install php-pear php-dev

**Comment by jmikola** [comment]
Duplicate of https://github.com/mongodb/mongo-php-driver/issues/482.

@DBARUNNER: Please do not create duplicate issues on the driver *and* library projects. Simply use the project that is most relevant to the issue.
