### ISSUE TITLE
Is MongoDB\Collection exists?

### ISSUE THREAD

**Issue by keita1314** [mongodb/mongo-php-library#316]
Mongodb driver version is 1.2.1,
>/etc/php5/cli/conf.d/20-mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.2.1
mongodb stability => stable
libmongoc version => 1.5.0
mongodb.debug => no value => no value

but I found this when I use MongoDB\Collection, also can't find MongoDB\Collection in the newest php doc.
>PHP Fatal error:  Class 'MongoDB\Collection' not found in /home/ketia1314/test.php on line 4

other api like MongoDB\Driver\..., MongoDB\BSON\... is OK.

**Comment by lindelius** [comment]
The classes `MongoDB\Driver\xxx` and `MongoDB\BSON\xxx` etc are defined in the MongoDB PHP driver, so if they are found it means that the PHP driver is loading properly. The `MongoDB\Collection` class is defined here in the PHP library, so if you can't find this class in your script you haven't fully included the library.

Did you install the library using Composer, or did you manually download the library files?

**Comment by jmikola** [comment]
For reference, installation instructions for the library are documented [here](https://docs.mongodb.com/php-library/master/tutorial/install-php-library/).

**Comment by jmikola** [comment]
Closing this, as it looks to be resolved based on the OP's thumbs up on https://github.com/mongodb/mongo-php-library/issues/316#issuecomment-268202563.
