### ISSUE TITLE
Warning: rewind(): stream does not support seeking

### ISSUE THREAD

**Issue by acid24** [mongodb/mongo-php-library#317]
## mongo-php-library version: 1.1.0

Hello,

Using this code

```php

/*
Uses MongoDb\GridFS\Bucket::openDownloadStreamByName($filename, array $options = []); to retrieve the file
*/
$file = $gw->retrieveFileByName('3142184dbed342fbb5ad6dc495d02405');


$metadata = stream_get_meta_data($file['stream']);
rewind($file['stream']);
```

I get a "Warning: rewind(): stream does not support seeking" even though stream_get_meta_data function advertises that the stream is seekable

```php
array (
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
  'wrapper_data' => '(removed for brevity)',
  'wrapper_type' => 'user-space',
  'stream_type' => 'user-space',
  'mode' => 'r',
  'unread_bytes' => 0,
  'seekable' => true,
  'uri' => 'gridfs://mydb/fileStore.files/585bc30888461f001a7a4412',
)
```

This behavior causes an error in Slim framework which tries to rewind the stream in the Response object if the stream is seekable before sending it out

**Comment by jmikola** [comment]
Seeking GridFS streams is an outstanding feature, which is being tracked in [PHPLIB-213](https://jira.mongodb.org/browse/PHPLIB-213).

Based on discussion in https://github.com/fruux/sabre-dav/issues/787, StreamWrapper implementations have no control over the "seekable" property of `stream_get_meta_data()` and always advertise themselves as seekable. Slim may want to implement similar `fseek()` checks that went into sabre-dav to address this (not just for GridFS but other StreamWrappers that do not support seeking).

/cc @codeguy @akrabat

**Comment by jmikola** [comment]
@acid24: We have an implementation of seeking for readable streams in https://github.com/mongodb/mongo-php-library/pull/325 if you'd like to test that out. Since it's a new feature, it will not be released until 1.2.0; however, I'd be interested to hear whether it meets your needs.

**Comment by acid24** [comment]
@jmikola OK, I will test it and let you know. Thank you

**Comment by jmikola** [comment]
[1.2.0-alpha1](https://github.com/mongodb/mongo-php-library/releases/tag/1.2.0-alpha1) is now tagged and includes seeking functionality for GridFS.
