### ISSUE TITLE
 Unable to load dynamic library 'mongodb.so

### ISSUE THREAD

**Issue by naveenabt** [mongodb/mongo-php-library#328]
PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongodb.so' - /usr/lib/php/20151012/mongodb.so: undefined symbol: php_json_serializable_ce

I am getting above issue, i am using php7 and os is linux mint.

please help me on this.

**Comment by alcaeus** [comment]
This is not an issue with mongo-php-library, but rather your operating system. @derickr has written about it [on his blog](https://derickrethans.nl/undefined-symbol.html). TL;DR: the json extension needs to be loaded before the MongoDB extension for this to work. See [this driver issue](https://github.com/mongodb/mongo-php-driver/issues/475) for more details.

**Comment by jmikola** [comment]
[PHPC-878](https://jira.mongodb.org/browse/PHPC-878) (to be included in ext-mongodb 1.2.3) should also ensure that a better error message noting the dependency is printed in lieu of the "undefined symbol" error.
