### ISSUE TITLE
No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling ismaster on '10.0.0.37:27017']

### ISSUE THREAD

**Issue by pradyotghate** [mongodb/mongo-php-library#330]
I have two server, one running Apache+PHP and another running Mongodb. I am trying to connect to the Mongodb server using following code -
```
require '/phpcomposer/vendor/autoload.php';
$mongo_conn = new MongoDB\Client('mongodb://10.0.0.37:27017/');
$collection = $mongo_conn->mydb->cpu_load_short;
$result = $collection->find();
```

The server IP is correct, the database and collection names are correct. However, every time I run the file, I am getting the following error -
```
PHP Fatal error:  Uncaught exception 'MongoDB\Driver\Exception\ConnectionTimeoutException' with message 'No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling ismaster on '10.0.0.37:27017']' in /var/www/phpcomposer/vendor/mongodb/mongodb/src/Collection.php:498
Stack trace:
#0 /var/www/phpcomposer/vendor/mongodb/mongodb/src/Collection.php(498): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference))
#1 /var/www/cronjobs/get_mongo_data.php(8): MongoDB\Collection->find()
#2 {main}
  thrown in /var/www/phpcomposer/vendor/mongodb/mongodb/src/Collection.php on line 498
```

Not sure what I am doing wrong. Any help would be useful. Thanks!

**Comment by petr-buchin** [comment]
@pradyotghate , can you connect to the mongo using console mongo client?
Try to run in console:

```bash
mongo --host=10.0.0.37:27017
```

**Comment by pradyotghate** [comment]
@petr-buchin - no it doesn't. It gives the following output.
`-bash: mongo: command not found`

I haven't got mongodb installed on the Apache+PHP server. Does that server also need to have mongod running?

**Comment by petr-buchin** [comment]
No, you just need to install mongo client. If you are using Ubuntu, it can be installed as follows:
```bash
sudo apt-get install mongodb-clients
```

**OR**, it can be insalled like described in this article:
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

You just need package `mongodb-org-shell` from this article.

**Comment by jmikola** [comment]
@pradyotghate: This is likely due to the [binding IP](https://docs.mongodb.com/manual/reference/configuration-options/#net.bindIp) in the server configuration. I expect that the server may only listening on the local interface.

Note that if you change the configuration to allow external connections, you should configure the server to require authentication. I'd suggest reading through the [security checklist](https://docs.mongodb.com/manual/administration/security-checklist/) for more information on best practices.

**Comment by pradyotghate** [comment]
@petr-buchin - Got it... installed the `mongodb-org-shell` (on Amazon Linux). Ran the same command, out come -
```
MongoDB shell version v3.4.1
connecting to: mongodb://10.0.0.37:27017/
2017-01-18T15:30:21.104+0000 W NETWORK  [main] Failed to connect to 10.0.0.37:27017 after 5000ms milliseconds, giving up.
2017-01-18T15:30:21.105+0000 E QUERY    [main] Error: couldn't connect to server 10.0.0.37:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:234:13
@(connect):1:6
exception: connect failed
```

**Comment by petr-buchin** [comment]
@pradyotghate , so, like you see, this is not an issue with the php library, this is an issue with your server configuration. See @jmikola comment for details.

**Comment by jmikola** [comment]
Closing this, as it appears unrelated to the driver or library. If you need additional assistance configuring the server to listen on public interfaces and handle authentication, I'd suggest one of the [community support channels](https://docs.mongodb.com/manual/support/#community-support), unless you have a commercial support contract, in which case one of the engineers can walk you through this process.

**Comment by pradyotghate** [comment]
Sure... for now, I have commented out the net.bindIp line from the config file (not that it has helped). But I will use the support channels. Doesn't seem like a driver/library issue. Thanks for all the help :)
