### ISSUE TITLE
PHP MongoDB Driver

### ISSUE THREAD

**Issue by Trukess** [mongodb/mongo-php-library#342]
Hello, in old MongodDB I had this code `$valoraciones[] = $document['valoraciones'];`  but actually in the new MongoDB Driver I get this error "[] operator not supported for strings", can someone help me?

**Comment by moderndeveloperllc** [comment]
Can you provide the code you are using to connect to the database leading up to this line? It's a bit difficult to understand what you are trying to do here. 

Also, in case you didn't know, this is the repository for the MongoDB provided userland library that provides useful classes to use on top of the actual driver commands. So:

Your code
    |
This library (https://docs.mongodb.com/php-library/master/)
    |
MongoDB PHP Driver (http://php.net/mongodb)
    |
MongoDB database

**Comment by Trukess** [comment]
Hello, thanks for answer me, I tried to solve this error, but I didn't get
it, in the old MongoDB version worked, I'm just trying to get an array from
the information store in name field "valoraciones", this is my code:

$connection = new MongoDB\Client;
        $database = $connection->usuarios;
            $collection = $database->valoraciones;

                $find_parameters = array ('propiouser' => $_GET["user"]);

                $cursor = $collection->find($find_parameters);

                foreach ($cursor as $document) {

                    $nombreusuario_valoracion = $document['propiouser'];
                    $valoraciones[] = $document['valoraciones'];
                    $valoraciontotal = array_sum($valoraciones);
                    $valoracionfinal = $valoraciontotal / $total;
                }

2017-02-20 15:13 GMT+01:00 Mark Garrett <notifications@github.com>:

**Comment by lindelius** [comment]
By the error you are given it looks like the `$valoraciones` variable has been given a string value before you try to push new values to it. How do you instantiate the variable (this is not shown in the code you gave us), and do you do anything else with it before the `foreach` loop?

**Comment by Trukess** [comment]
Oh I'm sorry, didn't notice, the error has been solve, the issue was before
the foreach, I wrote "$valoraciones=array();" before the foreach

$connection = new MongoDB\Client;
        $database = $connection->usuarios;
            $collection = $database->valoraciones;

                $find_parameters = array ('propiouser' => $_GET["user"]);

                $cursor = $collection->find($find_parameters);

                foreach ($cursor as $document) {

                    $nombreusuario_valoracion = $document['propiouser'];
                    $valoraciones[] = $document['valoraciones'];
                    $valoraciontotal = array_sum($valoraciones);
                    $valoracionfinal = $valoraciontotal / $total;
                }



2017-02-20 18:45 GMT+01:00 Tom Lindelius <notifications@github.com>:

**Comment by Trukess** [comment]
Oh I'm sorry, didn't notice, the error has been solve, the issue was before
the foreach, I wrote "$valoraciones=array();" before the foreach, thank you
very much for support me.


    $connection = new MongoDB\Client;
        $database = $connection->usuarios;
            $collection = $database->valoraciones;

                $find_parameters = array ('propiouser' => $_GET["user"]);

                $cursor = $collection->find($find_parameters);

                $valoraciones=array();
                foreach ($cursor as $document) {

                    $nombreusuario_valoracion = $document['propiouser'];
                    $valoraciones[] = $document['valoraciones'];
                    $valoraciontotal = array_sum($valoraciones);
                    $valoracionfinal = $valoraciontotal / $total;
                }

2017-02-20 18:45 GMT+01:00 Tom Lindelius <notifications@github.com>:

**Comment by lindelius** [comment]
No problem :)

**Comment by jmikola** [comment]
@Trukess: I see that your original code snippets have:

```php
$find_parameters = array ('propiouser' => $_GET["user"]);
```

You should not be creating MongoDB query criteria from raw query parameters, as that opens you up to [request injection](http://php.net/manual/en/mongodb.security.request_injection.php). For instance, the query string `?user%5B%24exists%5D%3Dtrue` would translate to criteria of `{ "propiouser": { "$exists": true }}` and match any document where the `propiouser` field [exists](
https://docs.mongodb.com/manual/reference/operator/query/exists/). I strongly suggest that you explicitly cast values from request parameters to the expected type (e.g. strings, integers) before using them in a query.
