### ISSUE TITLE
WritableStream / Upload Date / UTCDateTime Missing Argument

### ISSUE THREAD

**Issue by E1101** [mongodb/mongo-php-library#344]
mongo-php-library/src/GridFS/WritableStream.php::105

Rise an Exception:
MongoDB\\BSON\\UTCDateTime::__construct() expects exactly 1 parameter, 0 given

environment:
mongo-php-driver ver 1.1.9
mongo-php-library ver 1.1.2

**Comment by jmikola** [comment]
Version 1.1.2 of the library [requires version 1.2.0+ of the extension](https://github.com/mongodb/mongo-php-library/blob/1.1.2/composer.json#L14). You can find newer versions of the extension on [PECL](https://pecl.php.net/package/mongodb) (the most recent is 1.2.5).
