### ISSUE TITLE
Support required for fseek();

### ISSUE THREAD

**Issue by pyrosz** [mongodb/mongo-php-library#345]
I'm trying to use fseek() on a stream provided from 
```
$fileId = new MongoDB\BSON\ObjectId($fileId);
$bucket = (new MongoDB\Client)->example->selectGridFSBucket();
$stream = $bucket->openDownloadStream($fileId);
```
and _get a 500 error: fseek(): stream does not support seeking_
This worked on the legacy version for streaming a video file that is stored in GridFS.
I'm using version 1.2.6 stable for PHP 7.0.15 on Ubuntu 16.04.4

**Comment by jmikola** [comment]
> I'm using version 1.2.6 stable for PHP 7.0.15 on Ubuntu 16.04.4

I assume you're referring to [extension version 1.2.6](https://pecl.php.net/package/mongodb/1.2.6). Note that the PHP library has its own versions.

GridFS seeking was implemented in https://github.com/mongodb/mongo-php-library/pull/325 ([PHPLIB-213](https://jira.mongodb.org/browse/PHPLIB-213)) and is currently available in the `master` branch (aliased as [`1.2.x-dev`](https://github.com/mongodb/mongo-php-library/blob/7acb440a4d04c26fc776bdc2cdd7b9675c6b9d51/composer.json#L28) if you're using Composer). We've yet to release 1.2.0 as there are other issues awaiting completion, but I can look into tagging an alpha release for the current master branch if that would help in the meantime.

**Comment by pyrosz** [comment]
Thanks for the quick response. 
Sorry, I was referring to the extension with version 1.2.6.
An alpha release would allow me to test if things are going to work or not.
Thanks for all the hard work you and your team are doing.

**Comment by jmikola** [comment]
> An alpha release would allow me to test if things are going to work or not.

[1.2.0-alpha1](https://github.com/mongodb/mongo-php-library/releases/tag/1.2.0-alpha1) is now tagged.
