### ISSUE TITLE
mongodb can't get valid connection

### ISSUE THREAD

**Issue by dwoon** [mongodb/mongo-php-library#349]
Now latest mongodb extention (1.2.8)  still has a problem  that   when query data from mongodb server   throw a excption   No suitable servers found (`serverSelectionTryOnce` set): [connection closed calling ismaster on '192.168.1.78:28019'].    connection  manager  can't get a valid connection from  php worker.    When I modify  the mongodb libray  let it reconnect  the mongodb server every time, this problem  dispear.

env：
linux+nginx+ fastcgi     php-fpm
code like below

```
<?php
use MongoDB\Driver\Manager;
use MongoDB\Driver\Command;
use MongoDB\Driver\BulkWrite;
use MongoDB\Driver\Query;

$config = [
      "host"=>"192.168.1.78",
      "port"=>28017,
      "dbname"=>"my_test",
      "user"=>"test_mongo32",
      "pass"=>"7q0yJ7xxx_x1LVCa92d04xx"
];
$uri    = sprintf('mongodb://%s:%s@%s:%s/%s',
    rawurlencode($config['user']), rawurlencode($config['pass']),
    $config['host'], $config['port'],
    $config['dbname']);
$conn = new Manager($uri);
$tableName = 'ist_' . 1253748%100;
$where= [];
$where['$and'][] = ['user_id' => ['$ne' => 1253748]];
$condition =["limit"=>5,"sort"=>['_id'=> -1]];
$fields = [
      "user_id",
      "created_at"
];
$obj    = new Query($where, $condition);
$ret    = $conn->executeQuery($config['dbname'].'.'.$tableName, $obj);
$rets   = array();
var_dump($ret);
```
The excetption like below
2017/03/21 18:10:00 [error] 35935#0: *7117063 FastCGI sent in stderr: "PHP message: 
No suitable servers found (`serverSelectionTryOnce` set): [connection closed calling ismaster on '192.168.1.78:28019']" while reading response header from upstream

**Comment by dwoon** [comment]
when can't get data from mongo server ,the debug info can't be generate

**Comment by jmikola** [comment]
For reference, this was moved to https://github.com/mongodb/mongo-php-driver/issues/564.
