### ISSUE TITLE
Close connection with Database.

### ISSUE THREAD

**Issue by trunganh07** [mongodb/mongo-php-library#351]
Hi all,

I don't know MongoDB library close connection when browser finish. We find out http://php.net/manual/en/mongoclient.close.php but not exist in documentation.

**Comment by jmikola** [comment]
[`MongoClient::close()`](http://php.net/manual/en/mongoclient.close.php) is found in the legacy `mongo` extension. We did not implement an analogous method in the newer `mongodb` extension (see: [PHPC-535](https://jira.mongodb.org/browse/PHPC-535)), nor the library.

For reference, connection persistence in the new driver is documented [here](http://php.net/manual/en/mongodb.connection-handling.php).
