### ISSUE TITLE
aggregate $count not working

### ISSUE THREAD

**Issue by lanlin** [mongodb/mongo-php-library#354]
**db version v3.4.2
php version v7.1.3
mongo php library version v1.2.0-alpha1**

When query from CLI directly using aggregate $count, it works.

But not working when query from php, even when just set $count as the only pipeline.

```php
$pipeLine = 
[
    ['$count' => 'count']
];

// function below mongodb/src/Collection.php, line 180
\MongoDB\Collection\aggregate($pipeLine);
```

**Comment by jmikola** [comment]
> even when just set $count as the only pipeline.

That is not a valid use case for the [`$count`](https://docs.mongodb.com/manual/reference/operator/aggregation/count/) aggregation operator. It's intended to be used following other operators that populate the pipeline with documents.

The PHP library applies no special processing to the pipeline array, so any example in the `mongo` shell should work equivalently. If this isn't the case, please provide complete scripts (i.e. populating a new collection and executing an aggregation pipeline) for both the shell and PHP library so we can compare.

**Comment by lanlin** [comment]
Thanks, the problem has resolved.
Sorry, it's my mistake. As you saied, i made a valid use case for the $count.
