### ISSUE TITLE
Why to use this lib?

### ISSUE THREAD

**Issue by Anan5a** [mongodb/mongo-php-library#358]
Why I should use it instead of Raw api in PHP?

**Comment by moderndeveloperllc** [comment]
@Anan5a First off, you don't _have_ to use this library to connect to mongodb instances. Yes, you can use the `\MongoDB\Driver` classes directly to do everything, but the driver classes were designed to do _one_ thing - communicate via the unified API to the MongoDB instances and return results. They do so in a very efficient, but not overly user-friendly way. This library adds a very fast, easy convenience layer on top of this. Take a look at some of the code for things like [`MongoDB\Client`](https://github.com/mongodb/mongo-php-library/blob/master/src/Client.php). You will see that it's doing pretty much what you would have to do in your code anyways. Allowing you to set options to create a `Manager`, saving typeMaps to be used for further commands like in [selectCollection()](https://github.com/mongodb/mongo-php-library/blob/master/src/Client.php#L193). 

In my opinion, the real heart of the convenience is [`Collection`](https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php). To do the equivalent of `db.users.findOne({_id:"myUniqueId"})` in the CLI:

With Library:
```
$users = (new \MongoDB\Client())->selectCollection('testDB', 'users');
$me = $users->findOne(['_id' => 'myUniqueId']);
```
Very short and sweet. The library sets up my defaults for read and write preferences, typemaps, etc. the `findOne()` method gives a clear indication of what you are trying to do.

Without a library.
```
$manager = new \MongoDB\Driver\Manager();
$readPreference = new \MongoDB\Driver\ReadPreference(\MongoDB\Driver\ReadPreference::RP_PRIMARY);
$query = new \MongoDB\Driver\Query(['_id' => 'myUniqueId']);
$cursor = $manager->executeQuery('testDB.users', $query, $readPreference);
$me = current($cursor->toArray());
```
You have to wire everything yourself and use `executeQuery()` or `executeCommand()`. Not overly descriptive if you are skimming the code looking for what's going on with DB commands.

This isn't even getting into things like having error classes for faults, typed classes for [update/delete results](https://github.com/mongodb/mongo-php-library/blob/master/src/UpdateResult.php), etc.  The library is basically setting up the object oriented structure that you would want to do for any decent sized project anyways. Why create your on when it's done for you already?

**Comment by Anan5a** [comment]
Ok.
