### ISSUE TITLE
support for amp and react-php

### ISSUE THREAD

**Issue by cordovapolymer** [mongodb/mongo-php-library#370]
Hi,
are there plans to support asynchronous php frameworks, such as [amp](https://github.com/amphp/amp) and react-php?

**Comment by jmikola** [comment]
I followed up in https://github.com/amphp/amp/issues/138.

[PHPC-160](https://jira.mongodb.org/browse/PHPC-160) is an outstanding ticket to track this request, but it is not a priority at the moment.

All network IO in the current extension is handled by [libmongoc](https://github.com/mongodb/mongo-c-driver) and I don't see a way to nicely integrate that with the userland event loops for React PHP and other async frameworks. If PHP core ends up adding first-class async support (perhaps modeled after [HHVM](https://docs.hhvm.com/hack/async/awaitables)), that may be something we can integrate with.

As-is, an entirely separate driver implementation would be required.
