### ISSUE TITLE
Execute defined functions

### ISSUE THREAD

**Issue by niesuch** [mongodb/mongo-php-library#379]
How to execute defined in DB functions?

**Comment by jmikola** [comment]
[Store a JavaScript Function on the Server](https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/) in the MongoDB manual may be what you're looking for. It discusses how to create Javascript functions that are stored on the server and accessible from any Javascript context (e.g. `$where` query operator, or `mapReduce` command).

Note that the library currently does not have a helper method for the [`mapReduce` command](https://docs.mongodb.com/manual/reference/command/mapReduce/). That feature is being tracked in [PHPLIB-53](https://jira.mongodb.org/browse/PHPLIB-53). In the meantime, you will need to construct the command document (as show in the [documentation](https://docs.mongodb.com/manual/reference/command/mapReduce/)) and rely on [`MongoDB\Database::command()`](https://docs.mongodb.com/php-library/master/reference/method/MongoDBDatabase-command/).

**Comment by niesuch** [comment]
Ok, thx for help
