### ISSUE TITLE
db.collection.group() does not exist in the package.

### ISSUE THREAD

**Issue by JefferyHus** [mongodb/mongo-php-library#382]
Hi,
I have been struggling with a query where I want to select some fields and count too,
I have tried with `$project` and  `$group` as well as `$count`, `$match`, the issue is that when I take off the projection the query returns then results, and vice versa.
So my only solution is to use `db.collection.group()`, and unfortunately there is no such function existing in the current package.
Please if there is anything to help me.
```php
$reduce = "function(obj, prev) {if (obj.crawler != null) if (obj.crawler instanceof Array)prev.count+=obj.crawler.length;else prev.count++;}";
// select all proxies
$proxies = $_coll->group([ 'key' => [ 'crawler' => 1 ], 'initial' => [ 'count' => 0 ], 'reduce' => $reduce, 'cond' => [ 'website' => [ '$in' => $website ], 'crawler' => [ '$in' => static::$proxies ] ] ]);
``

**Comment by JefferyHus** [comment]
Duplicate of: https://github.com/mongodb/mongo-php-library/issues/127

**Comment by jmikola** [comment]
As mentioned in [PHPLIB-177](https://jira.mongodb.org/browse/PHPLIB-177), we will not be adding a [`group` command](https://docs.mongodb.com/manual/reference/command/group/) helper in the library as the command is being deprecated in the server ([SERVER-28524](https://jira.mongodb.org/browse/SERVER-28524)); however, you can certainly construct the command document yourself an execute it with [`MongoDB\Database::command()`](https://docs.mongodb.com/php-library/master/reference/method/MongoDBDatabase-command/). Note that any Javascript code strings will need to be wrapped with [`MongoDB\BSON\Javascript`](http://php.net/manual/en/class.mongodb-bson-javascript.php).

That said, the `reduce` function you shared above makes me think this could be done using the aggregation framework. If you want to share a few example documents from the collection and an example result from grouping on those documents, I'd be happy to take a crack at porting this to an aggregation pipeline for you.

**Comment by JefferyHus** [comment]
Hi, thanks for your help.
This is an example from my document:
```javascript
{
        "_id" : ObjectId("594c5477ae771746e663ae0c"),
        "website" : "www.ex.com",
        "ip" : "127.0.0.1",
        "agent" : "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
        "country" : null,
        "city" : null,
        "time" : "2017-06-20",
        "back" : null,
        "browser" : "Chrome",
        "os" : "Windows",
        "device" : "Desktop",
        "crawler" : "DCH",
        "status" : 1,
        "created_at" : 1498174583,
        "updated_at" : null
}
```
and this is what I did as a solution to my needs:

```php
$reduce = "function(obj, prev) {if (obj.crawler != null) if (obj.crawler instanceof Array)prev.count+=obj.crawler.length;else prev.count++;}";

// select all proxies
$proxies = $_database->command([
    'group' => [
        'ns' => 'visitors',
        'key' => [ 'crawler' => 1 ],
        'initial' => [ 'count' => 0 ],
        '$reduce' => new \MongoDB\BSON\Javascript($reduce),
        'cond' => [ 'website' => [ '$in' => $website ], 'crawler' => [ '$in' => static::$proxies ] ]
    ],
]);
```
It will be greate if an aggregation could do the work, as `group()` is slower

**Comment by jmikola** [comment]
If I understand your example correctly, you're grouping by the `crawler` field and then incrementing the accumulator by either one or the length of the array depending if the `crawler` field is a string or array, respectively. MongoDB provides a [`$size`](https://docs.mongodb.com/manual/reference/operator/aggregation/size/) operator that can return the length of an array value. We can use [`$type`](https://docs.mongodb.com/manual/reference/operator/aggregation/type/) to check if a value is an array (before trying to run `$size` on it). Lastly, we can wrap that with [`$cond`](https://docs.mongodb.com/manual/reference/operator/aggregation/cond/). I may be missing logic to check if `crawler` is `null`, but I don't think that would come up if we're matching `crawler` against a list of possible values with `$in` (both in my pipeline example and your original `group` command).

```php
<?php

require_once 'vendor/autoload.php';

$database = (new \MongoDB\Client)->test;
$collection = $database->visitors;

$collection->drop();
$collection->insertMany([
    ['website' => 'a.example.com', 'crawler' => 'A'],
    ['website' => 'a.example.com', 'crawler' => 'B'],
    ['website' => 'a.example.com', 'crawler' => 'C'],
    ['website' => 'a.example.com', 'crawler' => 'D'],
    ['website' => 'a.example.com', 'crawler' => ['B', 'C']],
    ['website' => 'a.example.com', 'crawler' => ['C', 'D']],
    ['website' => 'b.example.com', 'crawler' => 'A'],
    ['website' => 'b.example.com', 'crawler' => 'B'],
    ['website' => 'b.example.com', 'crawler' => 'C'],
    ['website' => 'c.example.com', 'crawler' => 'A'],
    ['website' => 'c.example.com', 'crawler' => 'B'],
    ['website' => 'c.example.com', 'crawler' => 'C'],
]);

$reduce = 'function(obj, prev) { if (obj.crawler != null) if (obj.crawler instanceof Array) prev.count += obj.crawler.length; else prev.count++; }';

$websites = ['a.example.com', 'b.example.com'];
$crawlers = ['B', 'C'];

$cursor = $database->command([
    'group' => [
        'ns' => 'visitors',
        'key' => [ 'crawler' => 1 ],
        'initial' => [ 'count' => 0 ],
        '$reduce' => new \MongoDB\BSON\Javascript($reduce),
        'cond' => [ 'website' => [ '$in' => $websites ], 'crawler' => [ '$in' => $crawlers ] ]
    ],
]);

echo json_encode($cursor->toArray(), \JSON_PRETTY_PRINT);

$cursor = $collection->aggregate([
    ['$match' => ['website' => ['$in' => $websites], 'crawler' => ['$in' => $crawlers]]],
    ['$group' => [
        '_id' => '$crawler',
        'count' => ['$sum' => ['$cond' => [
            'if' => ['$eq' => [['$type' => '$crawler'], 'array']],
            'then' => ['$size' => '$crawler'],
            'else' => 1,
        ]]],
    ]],
]);

echo json_encode($cursor->toArray(), \JSON_PRETTY_PRINT);
```

**Comment by JefferyHus** [comment]
Thanks mate, I will be testing this and back to you shortly ;)
