### ISSUE TITLE
change sub array ObjectId - PHP

### ISSUE THREAD

**Issue by redimongo** [mongodb/mongo-php-library#386]
Ok I have tried to do this a number of ways from updateOne, findOneAndUpdate to insert and even tried bulkWrite with no success.

What I have done is I have two collections the users collection and the image_upload collection. I store the users profile image inside image_upload along side all the other images that the user uploads.

What I then store in the users collection is the ObjectID of the image_upload collection that matched the image the user uploaded while creating their account (they can upload a new profile image anytime via edit profile)

So what I would like is the ability to update a ObjectId as I get

>  The field 'personal.profile_id' must be an array but is of type objectId in document 
Here is the code if anyone can help that would be great - I ideally want it to have the ObjectID and not just a string.

```
$db = static::db()->image_upload;
					try {
						$newdata = [
									"data"=>
											[
											"url" => $publlic_url,
											"type"=> $mimetype,
											"date"=>new MongoDB\BSON\UTCDateTime(),
											"profile_pic" => true
											],
									"uid"=>New MongoDB\BSON\ObjectId($uid)
									];
						
						$oauth_update = $db->insertOne($newdata);
							
						$view['newdata'] = $newdata;
						} catch(MongoResultException $e) {
							return $response->withStatus(200)
								->withHeader('Content-Type', 'application/json')
								->write($e->getDocument());
								
						}
						
						$ids = $oauth_update->getInsertedId();
						
						$latest = $db->findOne(array("uid"=>New MongoDB\BSON\ObjectId($uid)));
						
						// Check first, last and other personal details.
						$db = static::db()->users;
						try {
						$newdata = ['$set' =>["personal.profile_id"=>New MongoDB\BSON\ObjectId($ids)]];
						
						$member_profile = $db->findOneAndUpdate(
							['kst'=>New MongoDB\BSON\ObjectId($uid)],
							['$push' =>["personal.profile_id"=>['$oid'=>New MongoDB\BSON\ObjectId($ids)]]],
							[
								'projection' => 
									[ 'personal' => 1 ],
								"returnDocument" => MongoDB\Operation\FindOneAndUpdate::RETURN_DOCUMENT_AFTER
							]);
						
						} catch(MongoResultException $e) {
								echo $e->getCode(), " : ", $e->getMessage(), "\n";
								var_dump($e->getDocument());
								return $response->withStatus(200)
								->withHeader('Content-Type', 'application/json')
								->write(array('code'=>$e->getCode(), 'message'=>$e->getMessage));
						}
						
						return $response->withStatus(200)
						->withHeader('Content-Type', 'application/json')
						->write(json_encode($member_profile));
```

**Comment by jmikola** [comment]
GitHub and JIRA issues are the appropriate place to ask general usage questions and this does not appear to be a library or driver bug. Please refer to one of the [community support forums](https://docs.mongodb.com/manual/support/#community-support).

**Comment by redimongo** [comment]
@jmikola But it is a driver / library issue because if this feature is not in MongoDB it should be.
