### ISSUE TITLE
Does not work in symfony commands

### ISSUE THREAD

**Issue by AKarmanov** [mongodb/mongo-php-library#396]
Hi all, 

I run a symfony command where I want to execute mongo db client but it fails with the following message:
`[Symfony\Component\Debug\Exception\ClassNotFoundException]          
  Attempted to load class "Manager" from namespace "MongoDB\Driver".  
  Did you forget a "use" statement for another namespace?  `

Here's what I do:

`
    namespace AppBundle\Command;

    use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;

    class TestCommand extends ContainerAwareCommand {

    protected function configure() {
        $this->setName('test:update')
            ->setDescription('Desc...')
            ->setHelp('Help...');
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        new \MongoDB\Client("mongodb://localhost:27017");

        $output->writeln([
            'Test',
            '========================'
        ]);
    }
}`

Any ideas what might be wrong?

I'm on ubuntu 16 and php 7.0.22-0ubuntu0.16.04.1, symfony 3.2.13

**Comment by jmikola** [comment]
`MongoDB\Driver\Manager` is a class in [`mongodb` extension](http://php.net/manual/en/set.mongodb.php), which is a requirement for using the library (as noted in [the documentation](https://docs.mongodb.com/php-library/master/tutorial/install-php-library/) and [`composer.json`](https://github.com/mongodb/mongo-php-library/blob/1.1.2/composer.json#L14)).

Based on the class loader exception, it looks like the driver classes were not found, which can only mean that the extension is not loaded. If you installed the library via Composer, it should have verified that the extension was present (assuming you didn't ignore platform requirements).

Given that the CLI and web SAPIs may have different PHP configurations, it's also possible that the extension is being loaded in one or not the other (that could explain why you might be able to connect to MongoDB through web services but not via command-line scripts).

**Comment by AKarmanov** [comment]
As you mentioned, it seems that the extension is simply not loaded when executing commands.  Will investigate this further. Thanks for pointing me in that direction.
