### ISSUE TITLE
Missing \MongoDb\Operation docs

### ISSUE THREAD

**Issue by viniciusbo** [mongodb/mongo-php-library#414]
Can't find `\MongoDb\Operation` docs anywhere. It shouldn't already be used in production or documentation is missing?

**Comment by jmikola** [comment]
We've documented the methods on the core classes (e.g. `MongoDB\Database`, `MongoDB\Collection`), which use these operations internally and serve as the real public-facing API.

I don't intend on documenting the operation classes in the [library documentation](https://docs.mongodb.com/php-library/current/), as most users will never interact with them directly and there is significant overhead involved with maintaining two sets of documentation for the same operation (e.g. `MongoDB\Collection::find()` and `MongoDB\Operation\Find`). That said, I've tried to be thorough with doc block comments across the operation classes so you can rely on those if you like. Additionally, you can rely on BC being preserved for classes annotated with `@api` (e.g. [FindOneAndDelete](https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/FindOneAndDelete.php)). Private classes with no API guarantees have been annotated with `@internal` (e.g. [FindAndModify](https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/FindAndModify.php)).

**Comment by viniciusbo** [comment]
I understand @jmikola. Thanks for the info.

Actually I'm looking for info about Map Reduce operations. I see some tests using `\MongoDb\Operations\MapReduce` here https://github.com/mongodb/mongo-php-library/blob/dcb9d12023ebf9cc4782ffce454b3e191b5d3e8c/tests/Operation/MapReduceTest.php.

Since Map Reduce is widely used (not for internal stuff I guess), shouldn't at least `\MongoDb\Operations\MapReduce` and `\MongoDb\Operations\MapReduceResults` operations be documented?

**Comment by jmikola** [comment]
Ah, it looks like I forgot to add documentation in #392. I've re-opened [PHPLIB-53](https://jira.mongodb.org/browse/PHPLIB-53) and will make sure we get the `Collection::mapReduce()` method documented with 1.2.0. MapReduceResult will likely be documented on the same page, as that's the only time users will encounter the object.
