### ISSUE TITLE
Call to undefined method WriteConcern::isDefault()

### ISSUE THREAD

**Issue by harishkurup** [mongodb/mongo-php-library#444]
https://github.com/mongodb/mongo-php-library/blob/f7c686485151590b1ea451465918cd855a2d56fa/src/Operation/Update.php#L120

While using updateOne() getting the issue. 

> Fatal error: Uncaught Error: Call to undefined method MongoDB\Driver\WriteConcern::isDefault()

It's returning the empty object,
MongoDB\Driver\WriteConcern Object
(
)

and In Update constructor case for empty object is not handled. 
`if (isset($options['writeConcern'])  && $options['writeConcern']->isDefault()) {
           unset($options['writeConcern']);
 }`

**Comment by jmikola** [comment]
[`MongoDB\Driver\WriteConcern::isDefault()`](http://php.net/manual/en/mongodb-driver-writeconcern.isdefault.php) was introduced in ext-mongodb 1.3, and the code you referenced is from library version 1.2, which [depends on ext-mongodb 1.3+](https://github.com/mongodb/mongo-php-library/blob/1.2.0/composer.json#L16).

> In Update constructor case for empty object is not handled.

I don't completely understand what you mean by "case for empty object", but I think that's related to the notion of a default write concern (i.e. no user-specified options). The call to `isDefault()` is essentially checking for that. First, we verify that a "writeConcern" option, if provided, is of the appropriate type. We then unset the option if it is considered a default write concern:

https://github.com/mongodb/mongo-php-library/blob/f7c686485151590b1ea451465918cd855a2d56fa/src/Operation/Update.php#L116-L122

**Comment by harishkurup** [comment]
I was using the below code to update the document,
`$collection->updateOne(['order_id' => 'OI123'], ['$set' => ['status' => 'pending', 'price' => 10]], ['upsert' => true]);`  
But giving me the error,

> Fatal error: Uncaught Error: Call to undefined method MongoDB\Driver\WriteConcern::isDefault()

and if you var_dump $options['writeConcern'] it shows an empty object.

**Comment by harishkurup** [comment]
sorry issue was due to the different version(on our staging env).

**Comment by jmikola** [comment]
> sorry the issue was due to the different version of mongo(on our staging env, which is 2.6). Upgraded to Mongo 3.2, now issue solved.

Glad to hear this is resolved.

For the record, this error must have been caused by differing driver versions between your environments. The server versions would not have factored into `WriteConcern::isDefault()` being undefined.

**Comment by alcaeus** [comment]
> For the record, this error must have been caused by differing driver versions between your environments.

Sounds like it. It may be a good time to mention [`config.platform`](https://getcomposer.org/doc/06-config.md#platform) in `composer.json` to avoid such issues in the future. composer will not pick `mongodb/mongodb` 1.2 and higher unless `ext-mongodb` 1.3+ is present, so this should be guarded against by either having the same versions locally and on production, or use `config.platform` if the first isn't possible.
