### ISSUE TITLE
FAILS TO INSTALL ON MULTI-PHP SYSTEM

### ISSUE THREAD

**Issue by MichaelBrenden** [mongodb/mongo-php-library#448]
System running PHP-5.6 and also PHP-7.1 on different (but identical) apache servers.  All PHP and Apache installs have their own distinct, isolated, non-sharing-of-anything directory trees.

Yet, composer require mongodb/mongodb apparently defaults to the debian-installed Apache2 system (which, on this system is NOT even installed at all).  Here is the error reported by composer:

```
  Problem 1
    - Installation request for mongodb/mongodb ^1.2 -> satisfiable by mongodb/mongodb[1.2.0].
    - mongodb/mongodb 1.2.0 requires ext-mongodb ^1.3.0 -> the requested PHP extension mongodb is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php-5.6.31/lib/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

It's ungood to have that kind of check in composer require, since composer is a slow piece of work that doesn't always work, and also because it assumes everyone has the same basic system.

**Comment by MichaelBrenden** [comment]
I just discovered this works --

composer require mongodb/mongodb --ignore-platform-reqs

**Comment by alcaeus** [comment]
> Yet, composer require mongodb/mongodb apparently defaults to the debian-installed Apache2 system (which, on this system is NOT even installed at all).

composer runs in the PHP CLI. You can find out which one that is by running `which php` and either calling `/path/to/your/php composer.phar ...` or properly setting up your PATH environment variable to ensure the right PHP binary is being called..

> It's ungood to have that kind of check in composer require

No, it's proper dependency management. Also, Platform services like Heroku rely on that information to properly set up machines and install required modules when you deploy an app.

> I just discovered this works -- `composer require mongodb/mongodb --ignore-platform-reqs`

This will also happily install packages that require PHP 7.1 on your PHP 5.6 install, so there's that. I recommend setting up a [https://getcomposer.org/doc/06-config.md#platform](platform config) in your composer.json if you don't want to properly set up dependencies and configure your system.

**Comment by jmikola** [comment]
Closing this, as @alcaeus covered all of the points.

> composer require mongodb/mongodb apparently defaults to the debian-installed Apache2 system (which, on this system is NOT even installed at all)

This is surely a misunderstanding on the OPs part, as Composer can only check platform dependencies (e.g. PHP version, installed extensions) for the `php` process in which it is running.
