### ISSUE TITLE
[Question] Guide to contributing?

### ISSUE THREAD

**Issue by moderndeveloperllc** [mongodb/mongo-php-library#45]
Is MongoDB looking for 3rd-party contributions to this code, or is it intended for primarily internal development? With the library going 1.0 stable, and this class going 1.0 beta, will things like code styling and documentation be areas to contribute to?

**Comment by bjori** [comment]
We are absolutely looking for contributions!
That is actually one of the biggest factors behind our new architecture.

There are certain core concepts and APIs that are a *MUST* and are defined by MongoDB specifications, but outside of that we are looking for feedback, bugfixes, ideas and general community involvement with the driver, this package and what other packages are needed or should exist - a long with other ecosystems (such as framework and libraries) that need attention.

As for coding style changes, thats not up for debate no -- unless there are errors or inconsistencies within itself.

Documentations is a big piece we haven't resolved yet and are looking for an solution.
The PHP and HHVM docs are on http://php.net/mongodb but as the main entry point is supposed to be this library (as apposed to the raw driver) we have to document this library better and figure out where to host it and such things.

It appears we are missing a CONTRIBUTING.md file for this repo, whoopsy!

**Comment by moderndeveloperllc** [comment]
Wasn't looking to change the coding standards, I just didn't want to cause a ruckus by my IDE aligning all the assignment operators (or not). Obviously PSR-1/PSR-2 for everything, but lots of stuff left unsaid intentionally with those. Having great inline docs will help make the library feel more "ready for primetime". JM2C I'll wait for the CONTRIBUTING.md file.

**Comment by bjori** [comment]
I've created couple of followup tickets for the CONTRIBUTING.md guides:
https://jira.mongodb.org/browse/HHVM-141
https://jira.mongodb.org/browse/PHPLIB-140

Thanks for noticing! :)
