### ISSUE TITLE
Call to undefined method MongoDB\Driver\WriteConcern::isDefault()

### ISSUE THREAD

**Issue by olvlvl** [mongodb/mongo-php-library#455]
Hi,

I updated from `1.1.2` => `1.2.0` and now I'm getting the following error while dropping collections:

```
Error: Call to undefined method MongoDB\Driver\WriteConcern::isDefault()

/server/http/vendor/mongodb/mongodb/src/Operation/DropCollection.php:72
/server/http/vendor/mongodb/mongodb/src/Collection.php:431
/server/http/vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoCollection.php:247
/server/http/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Collection.php:1102
/server/http/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Collection.php:297
/server/http/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/SchemaManager.php:371
/server/http/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/SchemaManager.php:355
```

I'm not sure if it's related to `doctrine/mongodb-odm` (I tested both `1.1.7` and `1.2.0`) so I opened an issue there too: https://github.com/doctrine/mongodb-odm/issues/1737

**Comment by alcaeus** [comment]
1.2.0 requires version 1.3.0 of the mongodb driver, which includes the method in question. I see you also have mongo-php-adapter installed - did you maybe update your dependencies using ignore-platform-reqs?

**Comment by olvlvl** [comment]
Yes, I did. Maybe I should start by updating my container…

**Comment by alcaeus** [comment]
That might be your problem. Please see the revised installation instructions in https://github.com/alcaeus/mongo-php-adapter/blob/master/README.md - after that you can run composer update without ignore-platform-reqs.

What version of ext-mongodb do you have installed?

**Comment by olvlvl** [comment]
`ext-mongodb` is now v1.3.4, I updated everything and all my test pass. Thanks for the help @alcaeus! Sorry for the inconvenience.

**Comment by alcaeus** [comment]
No worries, it’s kinda my fault for suggesting ignore-platform-reqs in the first place.
