### ISSUE TITLE
Argument 1 passed to MongoDB\Driver\BulkWrite::__construct() must be of the type array

### ISSUE THREAD

**Issue by gabrielalan** [mongodb/mongo-php-library#46]
Hey guys,

I'm using mongo-phplibrary with mongodb driver, and trying to insertOne document to tests.

But I'm receiving that error:
```PHP Catchable fatal error:  Argument 1 passed to MongoDB\Driver\BulkWrite::__construct() must be of the type array, boolean given, in C:\...\vendor\mongodb\mongodb\src\Collection.php on line 1024```

I change that code:
```php
public function insertOne($document)
{
        $options = array_merge($this->getWriteOptions());

        $bulk = new BulkWrite($options["ordered"]);
```

To this, and worked:
```php
public function insertOne($document)
{
        $options = array_merge($this->getWriteOptions());

        $bulk = new BulkWrite($options);
```

So, is that a bug?

Edit: I'm using version 1.0.0 of mongodb driver

**Comment by bjori** [comment]
This was a very late change in the `mongodb` driver.

It is a bug in mongo-php-library yes, and your fix is correct :)

**Comment by jmikola** [comment]
@gabrielalan: I believe you're using a very old version of this library. The latest [1.0.0-beta1](https://github.com/mongodb/mongo-php-library/releases/tag/1.0.0-beta1) release should be compatible with the 1.0.0 driver API. In that version, `Collection.php` is also less than 600 lines.

**Comment by debo** [comment]
@jmikola the problem persist in 1.0.0-beta1 for what I'm seeing... I think I'm going to create a PR for this.

**Comment by jmikola** [comment]
Closing this out as I've not heard back from the OP. Feel free to re-open if the issue persists.
