### ISSUE TITLE
Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given

### ISSUE THREAD

**Issue by krimia** [mongodb/mongo-php-library#496]
After upgrading from mongodb/mongodb 1.2.0 to mongodb/mongodb 1.3.0, i have an issue with the 3th argument of executeQuery() that is now waiting for an object and not an array.

Can you explain or fixe this issue ?
Environment

My environment is PHP 7.1.13 and symfony 3.4

**Comment by jmikola** [comment]
This is a duplicate https://github.com/mongodb/mongo-php-driver/issues/757. Please do not report the same issue on both the library and extension repositories. We monitor both projects for activity.
