### ISSUE TITLE
[1.3.0] Error in using FindOne

### ISSUE THREAD

**Issue by moderndeveloperllc** [mongodb/mongo-php-library#499]
I'm having an issue in using the 1.3 library (1.4 driver). I'm getting this error:
```
"Argument 3 passed to MongoDB\\Driver\\Server::executeQuery() must be an instance of MongoDB\\Driver\\ReadPreference or null, array given"
```
This appears to be caused but the `createOptions()` method in `Find` that is returning an array that is passed to `executeQuery()`
```
$cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, $this->createQuery(), $this->createOptions());
```
Below is a `var_dump` of the parameters being sent to `executeQuery()`.
```
/project/vendor/mongodb/mongodb/src/Operation/Find.php:286:string 'spp.users' (length=9)
/project/vendor/mongodb/mongodb/src/Operation/Find.php:286:
object(MongoDB\Driver\Query)[335]
  public 'filter' => 
    object(stdClass)[333]
      public 'username' => string 'xxxxxx@xxxxx.com' (length=32)
      public 'isActive' => boolean true
  public 'options' => 
    object(stdClass)[371]
      public 'limit' => int 1
  public 'readConcern' => null
/project/vendor/mongodb/mongodb/src/Operation/Find.php:286:
array (size=1)
  'readPreference' => 
    object(MongoDB\Driver\ReadPreference)[103]
      public 'mode' => string 'primary' (length=7)
```

**Comment by jmikola** [comment]
> I'm having an issue in using the 1.3 library (1.4 driver)

Please confirm the version of the `mongodb` extension loaded by the same process emitting this exception (`phpversion('mongodb')` should work handily). This looks like a duplicate of https://github.com/mongodb/mongo-php-driver/issues/757.

As of driver 1.4.0, all of the execute methods on Manager and Server take an array as their third argument (old objects are still accepted for BC).

**Comment by moderndeveloperllc** [comment]
smh. Sorry about that. Forgot to check closed tickets, and forgot I'm running FPM, so needed to restart PHP, not nginx. It's just fine.
