### ISSUE TITLE
When will the version 1 stable released?

### ISSUE THREAD

**Issue by dattran92** [mongodb/mongo-php-library#53]
Any road map for it? 
I'm moving from MongoClient to this extension. Looking forward to the stable version to get it work on production.

**Comment by bjori** [comment]
The primary issue tracker is the ["PHPLIB" project in the MongoDB JIRA.](https://jira.mongodb.org/browse/PHPLIB-74).

The MongoDB 3.2 release has taken priority lately over shipping 1.0.0-final but its coming "soon" :)
See the [1.0.0 milestone in jira](https://jira.mongodb.org/browse/PHPLIB-74?jql=project%20%3D%20PHPLIB%20AND%20resolution%20%3D%20Unresolved%20AND%20fixVersion%20%3D%201.0.0%20ORDER%20BY%20priority%20DESC)
