### ISSUE TITLE
This is an issue...

### ISSUE THREAD

**Issue by cwbeck** [mongodb/mongo-php-library#54]
What advantages are there to this new driver? More importantly what was wrong with the old one? Moving forward this will cost thousands of companies including ours a great deal of time and effort to re-implement everything.

It feels there has been little explanation here for the change and feels more like a "because we can" situation.

When should this be upgraded? Is it now considered stable? When will support be lost for the old driver?

**Comment by bjori** [comment]
See: https://www.mongodb.com/blog/post/call-feedback-new-php-and-hhvm-drivers

The new driver is now considered as stable and we are no longer actively working on the old driver.
The new driver will also include [PHP7 support](https://jira.mongodb.org/browse/PHPC-285).

I think the release announcement did describe the reasons reasonably well: https://github.com/mongodb/mongo-php-driver/releases/tag/1.0.0

I understand your pain, but this is something we had to do to avoid even bigger issues.
