### ISSUE TITLE
Where is the Driver namespace?

### ISSUE THREAD

**Issue by beyazkurt** [mongodb/mongo-php-library#55]
I have installed this package from composer and despite the use of Driver namespace it's not defined.

**Comment by bjori** [comment]
I'm not sure what you mean.

What exactly isn't defined? Can you paste the exact error message?

I suspect maybe you didn't install the driver itself properly, try:

    pecl install mongodb

**Comment by mdoelker** [comment]
You also need to remove the old mongo extension for it to work properly.

**Comment by jmikola** [comment]
> You also need to remove the old mongo extension for it to work properly.

That should not be necessary as both extensions occupy different namespaces (top-level for legacy and `MongoDB\Driver` for new) and should not conflict.

**Comment by pashadude** [comment]
I have the same problems with BSON and Driver namespaces. I don't have old mongo anywhere in the system and don't have any links to old mongo anywhere in the configs or libraries. I have installed mongodb via pecl

**Comment by qutwala** [comment]
The same problem and for me. IDE says that namespaces are undefined. I have installed driver by pecl as in described in instructions. IDE is PHPStorm.

**Comment by mdoelker** [comment]
> That should not be necessary as both extensions occupy different namespaces (top-level for legacy and MongoDB\Driver for new) and should not conflict.

I thought the same, but the classes would not be available until i disabled the old extension.

> The same problem and for me. IDE says that namespaces are undefined. I have installed driver by pecl as in described in instructions. IDE is PHPStorm.

The current version of PHPStorm doesn't include the stubs for the new extension yet. You can add the stub file to your project though to get the autocomplete until it officially arrives in an update. Get it from here: https://raw.githubusercontent.com/JetBrains/phpstorm-stubs/master/mongodb.php

**Comment by jmikola** [comment]
IDE stubs are currently being left to the community and IDE authors, so I'm going to close this out.

Note that the extension does have reflection info defined to assist with stub generation. Any discrepancies between that info and reality (or PHP.net docs) are definitely a bug that we'll gladly look into. We've had a few reports already, which were fixed and should appear in any recently generated stubs.
