### ISSUE TITLE
CountDocuments: count command did not return a numeric "n" value

### ISSUE THREAD

**Issue by tsuijie** [mongodb/mongo-php-library#565]
### Description

When expected CountDocuments result is 0, cursor returns empty array without the 'n' value, which throws an exception instead of returning 0.

```
        $cursor = $server->executeReadCommand($this->databaseName, new Command($this->createCommandDocument()), $this->createOptions());
        // this is an empty array which will cause an unexpected exception
        $result = current($cursor->toArray());

        if ( ! isset($result->n) || ! (is_integer($result->n) || is_float($result->n))) {
            throw new UnexpectedValueException('count command did not return a numeric "n" value');
        }

        return (integer) $result->n;
```

### Environment

MongoDB server version: 3.6.4-rc0-2-g0fe08c834e
PHP Version 7.2.2
MongoDB extension version | 1.5.1
libbson bundled version | 1.11.0
libmongoc bundled version | 1.11.0
mongo-php-library version: 1.4.1

**Comment by jmikola** [comment]
Thanks for the report. I've opened [PHPLIB-376](https://jira.mongodb.org/browse/PHPLIB-376) to track this.

If you need an immediate solution and are not using transactions, the deprecated `Collection::count()` method should be usable.

**Comment by derickr** [comment]
[PHPLIB-376](https://jira.mongodb.org/browse/PHPLIB-376) is not closed, and will be part of an upcoming 1.4.2 release.

**Comment by fgm** [comment]
Not sure it's still relevant, got the same error today with:

* Mongod 4.0.0 (git version 3b07af3d4f471ae89e8186d33bbb1d5259597d51)
* PHP 7.2.8
* PHP Extension 1.5.0
* libbson bundled version | 1.11.0
* libmongoc bundled version | 1.11.0
* PHP Library 1.4.1

**Comment by derickr** [comment]
MongoDB PHP Library 1.4.2 which has this fix, is now released: https://groups.google.com/forum/#!topic/mongodb-announce/Z_XOpIQTJyo
