### ISSUE TITLE
Question: Is there compatibility documentation or recommendations for this lib + mongodb php driver?

### ISSUE THREAD

**Issue by desertdev** [mongodb/mongo-php-library#570]
In the mongo docs, they provide a MongoDB compatibility table to show which versions of this mongo-php-library + mongo php driver combinations are compatible with which versions of mongo:

![image](https://user-images.githubusercontent.com/15255757/43409750-9c098276-93d9-11e8-905a-5846aae1ce32.png)

https://docs.mongodb.com/ecosystem/drivers/php/

The left column of the table seems to _imply_ that PHPLIB versions are only compatible with specific versions of the driver. Is this in fact the case, or can PHPLIB 1.3 potentially also work with a driver version prior to 1.4 as well?

(Upgrading a php codebase to use PHPLIB 1.3 to add MongoDB 3.6 compatibility, but installs of the application in the wild may be running on web servers with different versions of the mongo php driver, and need to know if we should proactively update all the drivers to 1.4.)

Thank you

**Comment by jmikola** [comment]
We do not maintain a compatibility table between PHPLIB and the extension in the documentation. That compatibility is already tracked in the library's [`composer.json`](https://github.com/mongodb/mongo-php-library/blob/master/composer.json) file. The [Packagist page for the `mongodb/mongodb` package](https://packagist.org/packages/mongodb/mongodb) allows you to easily check requirements for multiple versions of the library. Selecting various tags/versions on the right-most column will update the requirements on the left. For instance, [1.4.2](https://packagist.org/packages/mongodb/mongodb#1.4.2) requires "ext-mongodb: ^1.5.0". Swapping over to [1.3.0](https://packagist.org/packages/mongodb/mongodb#1.3.2) will show a requirement of "ext-mongodb: ^1.4.0".

**Comment by desertdev** [comment]
Very helpful, thank you!
