### ISSUE TITLE
Invalid namespaces and missing imports

### ISSUE THREAD

**Issue by mrcnpdlk** [mongodb/mongo-php-library#577]
Some imports, for example: [here](https://github.com/mongodb/mongo-php-library/blob/25aeff8e669e6821bc607023e581d6ad6aa5f3f0/src/Model/BSONIterator.php#L54) and [here](https://github.com/mongodb/mongo-php-library/blob/25aeff8e669e6821bc607023e581d6ad6aa5f3f0/src/GridFS/Bucket.php#L256) and some namespaces in PHP doc section, for example: [here](https://github.com/mongodb/mongo-php-library/blob/25aeff8e669e6821bc607023e581d6ad6aa5f3f0/src/Client.php#L271) are invalid.

**Comment by derickr** [comment]
Closing this issue, as the corresponding PR has now been merged manually by @jmikola
