### ISSUE TITLE
findAndModify operation missing in MongoDB\Collection

### ISSUE THREAD

**Issue by mdoelker** [mongodb/mongo-php-library#58]
Is it intentional that this is missing in the Collection class and only available through the findOneAnd... operations? I found this to be missing while migrating from the legacy mongo extension.

**Comment by jmikola** [comment]
This was an intentional decision. The cross-driver [CRUD specification](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst) defines specific methods for each `findAndModify` mode and those should be used going forward. This is similar to the legacy `update()` method being split into `updateOne()`, `updateMany()`, and `replaceOne()` methods.

**Comment by vingrad** [comment]
Do you habe an example? How can I implement findAndModify with the new mongodb php driver?

**Comment by jmikola** [comment]
The following `MongoDB\Collection` methods abstract the findAndModify command:

 * [`findOneAndDelete()`](http://mongodb.github.io/mongo-php-library/classes/collection/#findoneanddelete), which sets the `{ remove: true }` option
 * [`findOneAndReplace()`](http://mongodb.github.io/mongo-php-library/classes/collection/#findoneanddelete), which requires the `update` option to be a replacement document
 * [`findOneAndUpdate()`](http://mongodb.github.io/mongo-php-library/classes/collection/#findoneandupdate), which requires the `update` option to [update operators](https://docs.mongodb.com/manual/reference/operator/update/)

These cover all permutations of a [`findAndModify`](https://docs.mongodb.com/manual/reference/command/findAndModify/) command. The generic [`MongoDB\Database::command()`](http://mongodb.github.io/mongo-php-library/classes/database/#command) method can be used to run _any_ command; however, users are advised to use helper methods when they exist.
