### ISSUE TITLE
Annotation support

### ISSUE THREAD

**Issue by eman1986** [mongodb/mongo-php-library#583]
On the C# version of this library there's annotations that let you define things in your model such as 

- BsonIgnore
- BsonIgnoreIfNull
- BsonInoreIfDefault
- etc....

would be really great to have that available on the PHP library, in theory it should be possible as there are annotation libraries available in PHP.

**Comment by jmikola** [comment]
Neither the [driver](https://github.com/mongodb/mongo-php-driver) (i.e. `ext-mongodb`) nor this library provide any specific APIs for mapping model classes.

The driver does define a handful of interfaces (documented in its [Persistence reference](http://php.net/manual/en/mongodb.persistence.php)), which can be used to control (de)serialization of BSON and model classes; however, all conversion logic is implemented in one of two methods: [`MongoDB\BSON\Serializable::bsonSerialize()`](http://php.net/manual/en/mongodb-bson-serializable.bsonserialize.php) or [`MongoDB\BSON\Unserializable::bsonUnserialize()`](http://php.net/manual/en/mongodb-bson-unserializable.bsonunserialize.php). Those methods behave analogously to methods in PHP's [Serializable](http://php.net/manual/en/class.serializable.php) interface.

The library builds upon the driver's functionality to provide default classes to represent BSON documents and arrays. This is discussed in the library's [BSON reference](https://docs.mongodb.com/php-library/current/reference/bson/); however, it does not attempt to fulfill the role of an object-document mapper.

The logic for the specific annotations you allude to _could_ easily be implemented in a `bsonUnserialize()` method, which is free to decide how to initialize class properties (or whatever structure is used to track the BSON document's state in PHP).

If you are looking for a more robust object document mapper, you may be interested in [Doctrine MongoDB ODM](https://www.doctrine-project.org/projects/mongodb-odm.html). That does allow you to create model classes and define BSON mappings in a number of formats (e.g. annotations, XML).

**Comment by eman1986** [comment]
I don't have much love for doctrine, it's too bulky and uses the older version of the mongo library and PHP 5.

I've already written something simpler [myself](https://github.com/eman-development-design/Leaf-Orm) just thought it'd be nice to have it baked into the mongo library.

**Comment by alcaeus** [comment]
> I don't have much love for doctrine, it's too bulky and uses the older version of the mongo library and PHP 5.

The upcoming 2.0 version uses the new driver and this library to talk to MongoDB servers and is currently in Alpha. Since I also dislike blanket statements like "it's too bulky" you're welcome to give more feedback on what's too bulky for you and what can be improved.

**Comment by eman1986** [comment]
meanwhile the stable version is outdated for what I want, but to answer your question I don't like how complex it is to setup my objects. The thing I wrote is pretty much what I want, just a thin wrapper that'll give me what I want, I don't need a full fledge library, just some helpers to make my life easier.
