### ISSUE TITLE
 Uncaught MongoDB\Driver\Exception\InvalidArgumentException: Integer overflow detected on your platform

### ISSUE THREAD

**Issue by garciacarmonaam** [mongodb/mongo-php-library#584]
Why am I getting that error everytime I try to run something from PHP Library (I got 1.3.0 because PHP driver latest version did not work at XAMPP Windows 10, with PHP 7)?

PD: With PHP driver I have none of these problems

**Comment by garciacarmonaam** [comment]
It resulted to be another problem. I used unnamed properties a lot.

**Comment by derickr** [comment]
Hi,

Glad that you found the problem. I just wanted to reply to this (you ended up closing it while I was writing this), for reference and to clear up a few misconceptions:

This is an error when the PHP *driver* tries to convert a 64-bit integer as stored into a PHP variable on a 32-bit system. A 32-bit system is either with a 32-bit CPU, *or* PHP 5 on Windows (even if you're using a 64-bit CPU).

The PHP Library can only be used as a layer on top of the PHP driver, so I'm not sure where your "PD: With PHP driver I have none of these problems" comment came from.

I can not see why there would be a difference between the PHP Driver and PHP Library with regards to this error.

cheers,
Derick
