### ISSUE TITLE
Howto insert with document validation of type "long".

### ISSUE THREAD

**Issue by drupal-daffie** [mongodb/mongo-php-library#589]
How do I insert data in a collection when the collection has a validation on it with for a particular column of the type "long". This is used for 64 bit integers. When I try to a large integer the response that I get is that the document validation failed. With other special columns you create first object and insert that object as the column value (Decimal128). Using the Int64 class is not possible, because the construct method is private. Has anybody have an idea/example how to fix my problem. 

I am using: PHP 7.1 and version 1.4.2 of this project and MongoDB 3.6.

**Comment by derickr** [comment]
Can you share:

- the code, as short as possible, and something I could run without modification
- the validation schema, perhaps also explaining how you've configured this
- the exact error message

Decimal128 should generally only be used for very specific use cases. 

Int64 is a class that is only used when reading data that is stored in MongoDB as a IntLong/64-bit integer on a 32-bit platform. Without an Int64 class wrapping the value, the data would end up being corrupt in that case. On 64-bit platforms, Int64 should never be generated for you when reading data.

**Comment by drupal-daffie** [comment]
$collection = (new MongoDB\Client)->test->test;

$insertOneResult = $collection->insertOne([
    'big_integer' => 223372036854775807,
]);

The validation level is strict.
The collection test has the following validation:
{ 
    "$and" : [
        {
            "big_integer" : {
                "$type" : "long"
            }
        },
        {
            "big_integer" : {
                "$exists" : true
            }
        }
    ]
}

The error message that I get is: "MongoDB\Driver\Exception\BulkWriteException: Document failed validation"

Hopefully this is enough. And thank you in advance for your help.

**Comment by drupal-daffie** [comment]
Yes, I am using query expression validation. I should have mentioned that.

Changing the validation from `$type => "long"` to `$type => ["int", "long"]` fixed my problem.
Thank you jmikola for your suggestion.

Integer values in the column are now stored as "Int32" for small integer values and as "Int64" for large integer values.
It was probably my [OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder) side that wanted to store all integer values in that column as "Int64".

I would like to thank both derickr and jmikola for their fast responce to my problem and their very expert help/suggestions.
I will now close this issue. If someone still would like to add something, please do.
