### ISSUE TITLE
Mongodb Possible to return only modified fields in UpdateOne with Upsert 

### ISSUE THREAD

**Issue by sajumani** [mongodb/mongo-php-library#595]
Hi,

Is it possible to get only modified filed ?

Example:

db.collection.updateOne({email:"xxx@gmail.com"},{$set:{name:'xxx',city:'yyy',country:'zzz'}},{upsert:true});

Name and Country not a new value;
City is new value  But some time; name will be update;

finally i want to know; only modified fields.  

Note:
For now getModifiedCount(); is returning 1; If the document any one of the field modified.

**Comment by derickr** [comment]
No, that's not possible. You will get the whole document back.

**Comment by sajumani** [comment]
Ok...

**Comment by jmikola** [comment]
@sajumani: The driver/library cannot report more information than the `update` command itself provides. Per the [`update` output documentation](https://docs.mongodb.com/manual/reference/command/update/#output) in the MongoDB manual, the command only reports a count for the number of documents selected, modified, and upserted by the command.

If you want to track the actual fields that were modified by a command, you can look into using [change streams](https://docs.mongodb.com/manual/changeStreams/). This feature was introduced in MongoDB 3.6 and lets you watch changes to documents based on oplog activity (i.e. it requires a replica set or shard cluster with replication). The stream can watch documents at different granularity levels (e.g. client, database, collection) and can also be filtered to match specific documents (using the `$match` aggregation operator). [`MongoDB\Collection::watch()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-watch/) has some examples that demonstrate how to use this feature via the PHP library. You'll also find `watch()` methods on the Database and Client classes.
