### ISSUE TITLE
How to raw query with mongoDB php library

### ISSUE THREAD

**Issue by hassaan-dev** [mongodb/mongo-php-library#601]
Hi,

I recently started using this library. 

1. Is there any method available to execute RAW query using this library?

2. I want to add where cause in $lookup query. Can someone help me?

**Comment by jmikola** [comment]
> Is there any method available to execute RAW query using this library?

It's not clear what you mean by "RAW" query. MongoDB generally provides two methods of querying for documents: `find` and `aggregate`. The [CRUD tutorial](https://docs.mongodb.com/php-library/current/tutorial/crud/#query-documents) for the library has examples of both.

> I want to add where cause in $lookup query. Can someone help me?

[`$lookup`](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/) is an aggregation pipeline operator, so you write that as part of the pipeline argument for [`MongoDB\Collection::aggregate()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-aggregate/). By default, `$lookup` uses an equality on two fields, but [Specify Multiple Join Conditions with $lookup](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#specify-multiple-join-conditions-with-lookup) demonstrates the syntax for more complex join criteria and involves specifying a separate pipeline just for the `$lookup` operation.

Where the MongoDB manual examples show a document (or JSON object for its shell examples) being used, you can use an associative array in PHP. There is an example of using `aggregate()` in the [CRUD tutorial](https://docs.mongodb.com/php-library/current/tutorial/crud/#complex-queries-with-aggregation).

**Comment by hassaan-dev** [comment]
By RAW query mean simple JSON query that I want to execute for any operation but I get it now as you provide example of `find` and `aggregate`. I need use respective method is query is for update or delete etc.

Thanks :)
