### ISSUE TITLE
problem after running composer install

### ISSUE THREAD

**Issue by coderzero8** [mongodb/mongo-php-library#604]
I am using centos 6 php 5.6 

can you help me guys.

  Problem 1
    - alcaeus/mongo-php-adapter 1.1.6 requires ext-mongodb ^1.2.0 -> the request                                             ed PHP extension mongodb is missing from your system.

been searching resolution for 2 days but nothing seems to work,

**Comment by coderzero8** [comment]
this worked for me. 
thanks

$ pecl install mongodb
$ echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

then composer install.


although i installed the mongodb driver and changed the php.ini with extension=mongodb.so
before this 


using this link

https://www.liquidweb.com/kb/how-to-install-the-mongodb-php-driver-extension-on-centos-6/


in any case installation now worked well

thanks

**Comment by jmikola** [comment]
For the record, the blog post you shared was instructing you to install the legacy [mongo](http://pecl.php.net/package/mongo) extension. This library depends on the newer [mongodb](http://pecl.php.net/package/mongodb) extension.

The [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) you referred to is a third-party library that implements the mongo extension's API through the mongodb extension. It was specifically created to allow legacy applications to run on PHP 7 (as the mongo extension was only released for PHP 5.x). I don't expect this library would have required that, but it's possible you were using another library (e.g. [Doctrine ODM](https://github.com/doctrine/mongodb-odm) 1.x) that suggested that dependency.
