### ISSUE TITLE
mongodb driver on amazon linux 2 default pecl install

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-library#666]
I rolled a brand new amazon linux 2 install, and run into the error `Cannot create SSL client. SSL is not enabled in this build.`
I am trying to connect to an atlas server.

I can see that ssl wasn't installed as part of the pecl install process. I did `pecl install mongodb` The relevant install debug is here:

```
checking whether to enable crypto and TLS... auto
checking deprecated option for OpenSSL library path... auto
configure: checking whether OpenSSL is available
checking for PHP_MONGODB_SSL... no
checking for EVP_DigestInit_ex in -lcrypto... no
configure: checking whether OpenSSL >= 1.1.0 is available
checking for OPENSSL_init_ssl in -lssl... no
configure: checking whether OpenSSL < 1.1.0 is available
checking for SSL_library_init in -lssl... no
configure: checking whether LibreSSL is available
checking for PHP_MONGODB_SSL... no
checking for EVP_DigestInit_ex in -lcrypto... no
checking for tls_init in -ltls... no
checking which TLS library to use... no
checking whether to use system crypto profile... no
checking deprecated option for whether to use system crypto profile... no
checking whether to enable ICU for SASLPrep with SCRAM-SHA-256 authentication... auto
```

And the resulting php reboot yields:

```
mongodb
libmongoc bundled version => 1.13.0
libmongoc SSL => disabled
libmongoc crypto => disabled
libmongoc SASL => disabled
libmongoc ICU => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
```

You can see ssl is disabled. Anyway, I imagine I can try yum installing some various ssl packages and re-running the pecl install to get it to work, but seeing as this is a default amazon 2 ami with nothing special, I figured it was worth a mention as I would have expected it to work without having to install any other libraries (especially as nothing was mentioned in the mongo install page here: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-amazon/)

Thank you

**Comment by 719media** [comment]
Interestingly enough:
```
sudo yum install openssl
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package 1:openssl-1.0.2k-16.amzn2.1.1.x86_64 already installed and latest version
Nothing to do
```

I figured openssl was one of the libraries that the driver installer looked for, so not sure what is misconfigured here

**Comment by jmikola** [comment]
Glad you sorted this out. As far as documentation is concerned, I believe this is covered by the note on the [Installing the MongoDB PHP Driver with PECL]( https://www.php.net/manual/en/mongodb.installation.pecl.php) article in the extension's docs:

> Note: If the build process fails to find an SSL library, check that the development packages (e.g. `libssl-dev`) and `pkg-config` are both installed. If that does not resolve the problem, consider using the manual installation process.

We cannot anticipate all package names for SSL headers, so "libssl-dev" is only used as an example.

It appears that https://docs.mongodb.com/manual/tutorial/install-mongodb-on-amazon/ only pertains to installation of the MongoDB server binaries, so I don't think that page would be suitable to discuss specific requirements for drivers.
