### ISSUE TITLE
"No data received error" when calling findOne method

### ISSUE THREAD

**Issue by levani** [mongodb/mongo-php-library#67]
I have a strange issue with `findOne` method. When I call it I get this `No data received ERR_EMPTY_RESPONSE` error in chrome. `find` method works fine!

This is what I found in apache error logs:

~~~
/private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/mongoc-cursor.c:52 _mongoc_n_return(): precondition failed: remaining > 0
[Mon Dec 21 00:08:58.512815 2015] [core:notice] [pid 11959] AH00052: child pid 15139 exit signal Abort trap (6)
/private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/mongoc-cursor.c:52 _mongoc_n_return(): precondition failed: remaining > 0
[Mon Dec 21 00:08:59.512918 2015] [core:notice] [pid 11959] AH00052: child pid 15323 exit signal Abort trap (6)
/private/tmp/pear/install/mongodb/src/libmongoc/src/mongoc/mongoc-cursor.c:52 _mongoc_n_return(): precondition failed: remaining > 0
[Mon Dec 21 00:09:30.388006 2015] [core:notice] [pid 11959] AH00052: child pid 15325 exit signal Abort trap (6)
~~~

**Comment by letrunghieu** [comment]
The reason is the current version of `libmongoc` does not support `limit` option with negative value. This issue is fixed in master, you can wait for the next version or use `^1.0@dev` instead of `^1.0@beta` in your `composer.json`

**Comment by bjori** [comment]
Thanks @letrunghieu !

See also https://github.com/mongodb/mongo-php-driver/issues/177 and https://jira.mongodb.org/browse/PHPLIB-152
