### ISSUE TITLE
Distinct method not getting Collection typeMap as default - Version 1.5

### ISSUE THREAD

**Issue by Cenadros** [mongodb/mongo-php-library#687]
In `Collection.php`, method `distinct` is not setting its typeMap to the Collection typeMap as default, which is generating issues when trying to make this operation. I think it should be implemented the same way as it is in the `drop`method:

`if (! isset($options['typeMap'])) {
            $options['typeMap'] = $this->typeMap;
        }`

**Comment by jmikola** [comment]
Thanks for the report. It looks like we missed this when introducing typeMap support for Distinct in 1.5.0. I've opened [PHPLIB-485](https://jira.mongodb.org/browse/PHPLIB-485) to track this.

**Comment by alcaeus** [comment]
See #688.

**Comment by jmikola** [comment]
Closing this as the fix has been included in the [1.5.1](https://github.com/mongodb/mongo-php-library/releases/tag/1.5.1) release.
