### ISSUE TITLE
Using the mongo-php-library with 7.3

### ISSUE THREAD

**Issue by jalite1991** [mongodb/mongo-php-library#691]
Hell when running 
`
composer require mongodb/mongodb
`

There is mdanter/ecc in dependencies of an old version, that required php 7.2 max.
So when i'm trying to add the mongo-php-library library to my project, i receive and error:
- mdanter/ecc v0.4.5 requires php >=5.6.0, <7.2 -> your PHP version (7.3.0) does not satisfy that requirement.

The fully php 7.* support for this library was arrived in release PHPECC v0.5.0.

Do you think you guys can add the upgraded mdanter/ecc in your library.

### Environment
PHP: 7.3.x
MAMP: 5.3
MongoDB Atlas.

**Comment by jalite1991** [comment]
Duplicated

**Comment by jmikola** [comment]
Superseded by #692
