### ISSUE TITLE
mongo change stream example for php ?

### ISSUE THREAD

**Issue by gfanini** [mongodb/mongo-php-library#693]
### Bug Report

where can I find any mongo change stream example for php ?
not tailable cursor on a "capped collection", I'd need to "watch" a modifiable collection from php

### Environment
WAMP php 7.2 windows

MongoDB support | enabled
-- | --
MongoDB extension version | 1.6.0
MongoDB extension stability | stable
libbson bundled version | 1.15.1
libmongoc bundled version | 1.15.1
libmongoc SSL | enabled
libmongoc SSL library | OpenSSL
libmongoc crypto | enabled
libmongoc crypto library | libcrypto
libmongoc crypto system profile | disabled
libmongoc SASL | enabled
libmongoc ICU | disabled
libmongoc compression | disabled

**Comment by jmikola** [comment]
I see you also posted this question on the [mongodb-user mailing list](https://groups.google.com/d/msg/mongodb-user/_saU8uO8voU/eVt5MPtEDgAJ) six minutes after opening this issue, and then created https://github.com/mongodb/mongo-php-driver/issues/1050 a few minutes after that (note: change streams are implemented entirely in the library, not the extension).

I've replied on the mailing list thread, and will close both GitHub issues. In the future, please do not cross-post the same question across multiple channels.
