### ISSUE TITLE
Return data from transaction callback 

### ISSUE THREAD

**Issue by bigdaddymax** [mongodb/mongo-php-library#700]
I have a question (or a feature request?): 

In the current implementation of transactions handler, there is no way to return any data from a callback.

This is pretty inconvenient, especially when you work with the legacy code and try to wrap some existing functionality in a transaction.

Is it possible to add a `return` statement to the handler? Or there are some specific reasons for current implementation?

Thank you.
Maksym

**Comment by alcaeus** [comment]
The call-back signature is defined in the [Convenient API for Transactions](https://github.com/mongodb/specifications/blob/master/source/transactions-convenient-api/transactions-convenient-api.rst#the-callback-function-has-a-flexible-signature) Spec. In the linked chapter, the spec elaborates on the signature of that callback function. To quote:
> Similarly, the specification does not concern itself with the return type of the callback function. If drivers allow the callback to return a value, they may also choose to propagate that value as the return value of withTransaction.

We have opted against this, mainly for the reason that the callback function may be executed multiple times. In such cases, it is not clear which value should be returned: whether the user would expect to receive the callback from the first or last call, or an array with all return values.

For now, I would recommend adding a reference variable to the scope of the callback:
```php
$callback = function (...) use (&$returnValue) {
    $returnValue = ...;
};
```

This allows you to check whether a return value has been assigned previously and act accordingly.

**Comment by bigdaddymax** [comment]
I see, that makes sense.

Thanks for the reference to specs, spared me asking more questions.
Maksym
