### ISSUE TITLE
What is the best alternate of hasNext & getNext?

### ISSUE THREAD

**Issue by ziyaindia** [mongodb/mongo-php-library#704]
I have used MongoClient in one of my application.
My old code having hasNext & getNext in my functions.
Please suggest me for the bbest alternative for these two functions.
Thanks in Advance

**Comment by jmikola** [comment]
Closing this as a duplicate of https://github.com/mongodb/mongo-php-library/issues/703. I realize the question above is a bit different than the "fatal error" reported in #703, but this could have easily been a comment on the original issue.
