### ISSUE TITLE
Get multiple files using GridFS

### ISSUE THREAD

**Issue by ti0rafa** [mongodb/mongo-php-library#705]
Is there a way to fetch multiple files in bulk?, currently I'm using `openDownloadStream` inside a loop to fetch everything, but I was wondering if there is a more efficient way to do this.

**Comment by jmikola** [comment]
There is no API to return multiple streams at once. You can use the [`Bucket::find()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBGridFSBucket-find/) method to query the `fs.files` collection (i.e. metadata documents) and use the `_id` from those documents to call [`Bucket::openDownloadStream()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBGridFSBucket-openDownloadStream/); however, the library still internally [fetches the entire file document](https://github.com/mongodb/mongo-php-library/blob/1.5.1/src/GridFS/Bucket.php#L474) to attach it to the returned stream resource. Given that, I don't think a `Bucket::find()` query would save you anything.

The library could theoretically group multiple `fs.files` queries by `_id` together, but each stream would still need to independently query the chunks collection to create its internal cursor (which itself reminds me of the [n+1 problem for ORMs](https://stackoverflow.com/q/97197/162228)). Grouping the initial `fs.files` queries could help applications with high latency between the app and database server (perhaps reducing `2 * (n+1)` to `1 + (n + 1)`), but such an approach wouldn't be feasible for filename-based queries (e.g. `openDownloadStreamByName`). Those APIs query on `filename` an optionally `uploadDate` (used for revision number) and depend on single-document queries using a `skip` option (see: [`CollectionWrapper::findFileByFilenameAndRevision()`](https://github.com/mongodb/mongo-php-library/blob/1.5.1/src/GridFS/CollectionWrapper.php#L140)).

Note that for both ID and filename-based queries in the Bucket API, those should all be using indexed fields such that the `findOne()` operations are efficient (concerns about database server latency aside).

**Comment by ti0rafa** [comment]
Thanks for the answer Jeremy
