### ISSUE TITLE
Iterate large collection

### ISSUE THREAD

**Issue by moazam1** [mongodb/mongo-php-library#724]
I am trying to iterate a very large collection, offset and limit is not working for me. I use last ID approach but the documents I am getting are less than the total total documents count I get from the query. I am prepared another test collection and also tested in CentOS, Debian and Windows but I got same results.

Below code I copied from my class. I remove irrelevant code to keep it to the point.

```
// function that iterate docs and print count
function getResults() {
  $lastId                 = null;
  $condition = []; // just grab entire collection for now  
  $total =  $this->collection->count( $condition );
  $docsFoundInMongoDB = 0;
 
  while ( true ) {
    $documents = $this->getDocumentsFromMongoDB( $lastId, $condition );
    if ( ! $documents ) {
      break;
    }
   
    $lastId     = null;
    foreach ( $documents as $doc ) {
      $docsFoundInMongoDB ++;
      $lastId = $doc ['_id'];
    }
    echo  'Got ' . $docsFoundInMongoDB . ' out of ' . $total;
  }
}
```

```
private function getDocumentsFromMongoDB( $lastId, $condition = [] )
{
  if ( $lastId != null ) {
    $condition['_id'] = [ '$gt' => $lastId ];
  }
// i tried with and without sort but no luck
  $options = [ 'limit' => $this->batchCheckMongoLimit, '$sort' => ['_id' => 0], 'projection' => ['id'=>1] ];
  $result  = $this->collection->find( $condition, $options )->toArray();
  if ( ! $result ) {
    return false;
  }

  return $result;
}
```

**Comment by alcaeus** [comment]
I see that your `$sort` specification is incorrect. For one, the option name is `sort`, not `$sort`. To sort by `_id` in ascending order, you must pass `1` as sort specification: `'sort' => ['_id' => 1]`.

Please note that the `count` method on `MongoDB\Collection` is deprecated as it can return inaccurate . You should use `countDocuments` instead.

**Comment by moazam1** [comment]
@alcaeus thanks so much. Changing sort worked for me.

**Comment by moazam1** [comment]
This solved one issue but opened another one. It worked on a small collection but on a large collection it's failing and giving me timeouts.

**Comment by alcaeus** [comment]
Hi @moazam1,

please create an topic in the [MongoDB Developer Community Forums](https://community.mongodb.com) to debug the timeout problem. Thanks!
