### ISSUE TITLE
How to force the value of Int64 to be saved?

### ISSUE THREAD

**Issue by hipig** [mongodb/mongo-php-library#740]
The database needs to be invoked in golang, and PHP is responsible for inserting data.

I want to know how to save an Int64 value in php7, but in a 64 bit system  `\mongodb\bson\Int64` cannot be called

**Comment by alcaeus** [comment]
Integers will be saved as 32-bit BSON type as long as they fit into the 32-bit range. For integers that exceed 32 bits, the value is stored as 64-bit integer in BSON. All you need to do is pass a 64-bit integer.

**Comment by hipig** [comment]
What should I do when I need to insert 0

> Integers will be saved as 32-bit BSON type as long as they fit into the 32-bit range. For integers that exceed 32 bits, the value is stored as 64-bit integer in BSON. All you need to do is pass a 64-bit integer.

**Comment by alcaeus** [comment]
> What should I do when I need to insert 0
> 
> > Integers will be saved as 32-bit BSON type as long as they fit into the 32-bit range. For integers that exceed 32 bits, the value is stored as 64-bit integer in BSON. All you need to do is pass a 64-bit integer.

0 is a valid 32-bit integer and is saved like all other 32-bit integers.

**Comment by AndeYashwanth** [comment]
Also you can't insert 64bit unsigned integer. Only 64bit signed integers are allowed. For this reason, I had to store numbers only up to 63bits.

**Comment by jmikola** [comment]
Closing this as @alcaeus answered the original question by clarifying that the driver chooses to use BSON integer types based on the integer value itself. There is no public API to force storage of an integer within the signed 32-bit range as a 64-bit integer in BSON.

> Only 64bit signed integers are allowed.

And this is based on the [BSON specification](http://bsonspec.org/spec.html), which defines both of its 32-bit and 64-bit integer types as signed.
