### ISSUE TITLE
Query Result Object should implement Countable Interface

### ISSUE THREAD

**Issue by Airy301** [mongodb/mongo-php-library#742]
As of PHP 7.2, a function call **count()** would generate a warning on the objects which do not implement Countable interface. So, a query like

    $recordsFound = $mongo->selectCollection('users')->find();
    echo count($recordsFound); //<-- Very important when need to be sure before further code execution

Will generate a warning as 
   
    PHP Warning:  count(): Parameter must be an array or an object that implements Countable in...

Therefore, when it generates the database query result, it should also implement PHP's Countable Interface before returning result to user

As per PHP Documentation at https://www.php.net/manual/en/function.count.php
  
     7.2.0 | count() will now yield a warning on invalid countable types passed to the array_or_countable parameter.

**Comment by alcaeus** [comment]
You should not call `count()` on the result of `$collection->find()`, but rather call `$collection->countDocuments()`. The warning you are receiving is absolutely correct in that the `MongoDB\Driver\Cursor` instance is not countable (and thus shouldn't implement the `Countable` interface). This differs from the legacy driver where a cursor was indeed countable, and I encourage you to read the [explanation for this change](https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194).

I'm closing this issue as this is not a part of the API we are going to change.
