### ISSUE TITLE
deletemany is not function

### ISSUE THREAD

**Issue by rathipradha** [mongodb/mongo-php-library#745]
deletemany is not function(ERROR)

rest.deleteMany({'_id': {$in:[ObjectId("5ae4c2aa3bf923ae6cda6a67"),ObjectId("5b068e30b901e0547455fe60"),ObjectId("5b0bd3431f135383c812d0e5")]} }), function (err,doc) {

})

Iam usingmongod --->db version v4.2.3

Please help me to rectify the issue..for same db 'remove' is working properly

**Comment by jmikola** [comment]
@rathipradha: Your issue does not appear related to the PHP driver. If you're asking about the MongoDB shell, please consult the [`db.collection.deleteMany`](https://docs.mongodb.com/manual/reference/method/db.collection.deleteMany/) documentation and considering taking any outstanding question to the [MongoDB Community Forums](https://community.mongodb.com/).

If you do actually have a question about the PHP driver/library, please revise your original post and provide as much information as possible that we request in the "Bug Report" template for new issues (see [here](https://github.com/mongodb/mongo-php-library/issues/new/choose)).
