### ISSUE TITLE
findOne fails

### ISSUE THREAD

**Issue by eparlier** [mongodb/mongo-php-library#76]
PECL 1.1.1 + lib 1.0.0@beta
$collection->findOne(['name' => 'john']);
ext\mongodb\src\libmongoc\src\mongoc\mongoc-cursor.c:52 _mongoc_n_return(): precondition failed: remaining > 0

$collection->find(['name' => 'john']);
//works

**Comment by bjori** [comment]
See https://github.com/mongodb/mongo-php-driver/issues/177 and https://jira.mongodb.org/browse/PHPLIB-152
