### ISSUE TITLE
Feature request, collection showRecordId as boolean or string or objectid?

### ISSUE THREAD

**Issue by globules-io** [mongodb/mongo-php-library#784]
Would it be possible to add, for the options, **showRecordId** as boolean or string or objectid? Right now it is only boolean. 
The reason I'm asking is that, most of the time, for the front end, we have to convert the ObjectID back to a string to have a "flat" index key. Our API handles both responses from a SQL or NoSQL dbs, but for MongoDB we have to cycle through the documents just to convert the object id. I would be nice if the library could return the _id as string.

**Comment by jmikola** [comment]
> Would it be possible to add, for the options, showRecordId as boolean or string or objectid? Right now it is only boolean.

I think you're misunderstanding the purpose of the `showRecordId` option. This is a boolean option for the [`find`](https://docs.mongodb.com/manual/reference/command/find/) command that, if `true`, instructs the server to inject a `$recordId` field into each result document. The PHP driver/library does nothing with `showRecordId` other than allowing an application to specify it when executing a query (i.e. `find` command). The documentation for the `mongo` shell's [`cursor.showRecordId()`](https://docs.mongodb.com/manual/reference/method/cursor.showRecordId/) method demonstrates the effect of using this option. AFAIK, the record ID is an integer and has nothing to do with a document's `_id` field, which is typically an ObjectId. 

It sounds like your underlying request is for the driver to provide some functionality to automatically convert ObjectIDs in `_id` fields to a string. If so, I think this is better implemented in your application. Types other than ObjectId may legitimately be used in the `_id` field of a document, so I'd be hesitant to add a feature in the driver that makes the actual BSON type of the `_id` field ambiguous.

There are several ways to accomplish this in your application:

* Cast `_id` to a string when working with returned documents. This will invoke [`ObjectId::__toString()`](https://www.php.net/manual/en/mongodb-bson-objectid.tostring.php) as needed.
* Wrap the cursor returned by `find()` with an iterator/generator that performs the string cast behind the scenes when accessing the "current" element (i.e. document). [Wrapping a Normal Cursor](https://docs.mongodb.com/php-library/current/tutorial/tailable-cursor/#wrapping-a-normal-cursor) in the library documentation has an example of how to accomplish this using IteratorIterator. Your question suggests that your application is database-agnostic, so I would assume that you're not actually relying on iterating a `MongoDB\Driver\Cursor` object, so wrapping it with another iterable should not pose a problem.
* Leverage the driver's type map functionality to have BSON documents deserialized into a custom class. By default, the driver deserializes BSON documents as `stdClass` objects. The library specifies its own type map by default to return documents as `MongoDB\Model\BSONDocument` objects (see: [BSON classes](https://docs.mongodb.com/php-library/current/reference/bson/#bson-classes). You can specify your own class (optionally extending `BSONDocument` in the library) and convert ObjectIds in `bsonUnserialize()` when the document is first processed (or later through some other class method if you wish). The driver's API for type maps and deserialization is discussed in more detail in [Deserialization from BSON](https://www.php.net/manual/en/mongodb.persistence.deserialization.php).

**Comment by globules-io** [comment]
thanks I appreciate your answer. The thing is I was trying to not loop thought documents again just to convert _id.
