### ISSUE TITLE
Class 'MongoDB\Client' not found

### ISSUE THREAD

**Issue by TheLordDrake** [mongodb/mongo-php-library#798]
I'm attempting to follow along with the instructions provided [here](https://docs.mongodb.com/php-library/v1.2/tutorial/install-php-library/#installing-the-extension), however I'm unable to get it working. I have run into this error:
`Fatal error: Uncaught Error: Class 'MongoDB\Client' not found`
Googling leads me to [this answer on StackOverflow](https://stackoverflow.com/a/41032582/5924307). It is however four years old, and does not line up with the official documentation.

I'm trying to figure out if there is a problem with my installation or if the official documentation is inaccurate?

**Comment by alcaeus** [comment]
Hi @TheLordDrake,

the error message suggests that the class was not loaded, which could have multiple reasons. Without more information I can only guess what the problem might be. Please make sure that you followed all the instructions that you linked, including the "Installing the Library" chapter. Here are some steps that you can use to verify that the installation was successful:

1. Check if the PHP extension was installed successfully by running this command: `php --ri mongodb`. If successful, you'll see a block of info about the installed extension version. The error message "Extension 'mongodb' not present." will tell you if installation wasn't successful.
2. If the extension is installed, check if you've correctly installed this library. From the root directory in your project, run this command: `composer show mongodb/mongodb`. If successful, it will show you information about the installed version of the package. The error message "Package mongodb/mongodb not found" will tell you that the package is not installed.
3. If the package was installed successfully, make sure that your autoloader is configured correctly. Make sure that you've included the `vendor/autoload.php` script and that the autoloader was successfully generated after installing composer dependencies. For more about this, I'd refer you to the composer documentation and its support channels.

As for the StackOverflow link, this is not entirely correct: the extension provides a low-level API, including the `MongoDB\Driver\Manager` class. However, we suggest that people use this PHP library, which provides a high-level API that adheres to the MongoDB drivers specifications.

As this is a tracker for bugs and feature requests, I'd like to refer you to the [MongoDB Developer Community](https://developer.mongodb.com/community/forums/) for any further questions, as that is the appropriate place to ask support questions.

**Comment by Revilum** [comment]
I have a similar issue: I can only install die PHP MongoDB Driver because the instructions to install with with pecl are the same as with the PHP MongoDB Library. Because of that I only can use the PHP mongoDB Driver which I don't want to use.

**Comment by alcaeus** [comment]
Please don't resurrect old issues. I'd like to refer you to the [Installation Instructions](https://docs.mongodb.com/php-library/current/tutorial/install-php-library/), which detail installing the extension via pecl and the library via composer. You mentioned that the "instructions to install with pecl are the same as with the PHP MongoDB Library." Could you please point me to the documentation where you found this? Thanks!
