### ISSUE TITLE
Not working on new Apple ARM ?

### ISSUE THREAD

**Issue by pesseyjulien** [mongodb/mongo-php-library#799]
Hi,

Installed the extension mongodb using pecl -> installation went fine, no error.

Registered the extension on my php.ini, but no loaded by php -> no error as well.

Im running on Mac OS 11.1 with new M1 chipset.

Thanks in advance for your help,
Julien

**Comment by jmikola** [comment]
Note that you opened this issue on the [library](https://github.com/mongodb/mongo-php-library/) repository, although your problem appears to be with the [extension](https://github.com/mongodb/mongo-php-driver).

Although we don't have Apple M1 environments available in our [Evergreen CI matrix](https://evergreen.mongodb.com/waterfall/mongo-php-driver), we do test against other ARM platforms and I'm not aware of any build issues with them. If you were able to successfully build the extension via PECL, this sounds more like a configuration issue with your PHP environment.

Unless error reporting is being suppressed, PHP should report an error if an extension file (e.g. `mongodb.so`) cannot be loaded properly. Windows users typically encounter such errors when they attempt to load an incompatible DLL file.

In the event that you have multiple PHP environments on your machine, I suggest double-checking that the `pecl` command you used to build the driver is consistent with the PHP environment with which you're attempting to load the extension. From there, ensure that your PHP configuration references the correct `mongodb.so` file (consult [`extension_dir`](https://www.php.net/manual/en/ini.core.php#ini.extension-dir) and/or use an absolute path) and has enabled error reporting enabled.

Lastly, as this doesn't appear to be a bug with either the extension or library, I'd ask that you continue any conversation in the [MongoDB Community Forums](https://developer.mongodb.com/community/forums/c/drivers-odms/7). We'd like to consolidate all general usage/support inquiries there and limit GitHub and JIRA to actual bugs.
