### ISSUE TITLE
Can't insert data into collection

### ISSUE THREAD

**Issue by nucreativa** [mongodb/mongo-php-library#81]
Hi Team, i found an issue with insert data into collection both using insertOne() and insertMany(), but i can make it works if i change this line `$bulk = new BulkWrite($options["ordered"]);` to `$bulk = new BulkWrite();` on Collection.php:1024

the error message was like this 
```
\BulkWrite::__construct() must be of the type array, boolean given in /var/www/myapp/vendor/mongodb/mongodb/src/Collection.php:1024
```
i think it comes from this block Collection:973-980
```
public function getWriteOptions()
    {
        return array(
            "ordered" => false,
            "upsert"  => false,
            "limit"   => 1,
        );
    }
```
default value of `ordered` is false but `\BulkWrite::__construct()` expect an array or null instead false.

sorry if i'm wrong here, i'm newbie :),  but i just follow a simple tutorial but it doesn't work because this issue. and sorry if my english not good. thanks

**Comment by jmikola** [comment]
I believe you may be using an older version of this library, as it was updated to correct this issue in https://github.com/mongodb/mongo-php-library/commit/a033aca8781e1b8d86ff46bc1e3440c219538d51 (early November). Feel free to close this if you can verify things work with a newer release ([1.0.0-beta2](https://github.com/mongodb/mongo-php-library/releases/tag/1.0.0-beta2) is the latest, but beta1 also includes the necessary changes).

**Comment by nucreativa** [comment]
sorry, i just notice that. yeah... 1.0.0-beta2 works as expected. thanks
