### ISSUE TITLE
Minor documentation fix

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-library#845]
PHP 7.0 still listed as compatible on the page
https://docs.mongodb.com/drivers/php/#language-compatibility
for
ext 1.10 + lib 1.9
And the minimum required version is PHP 7.1

**Comment by jmikola** [comment]
I've submitted a PR to get that revised in https://github.com/mongodb/docs-ecosystem/pull/748. Thanks for letting us know we missed this!
