### ISSUE TITLE
Cannot access protected property ::$_id 

### ISSUE THREAD

**Issue by veego** [mongodb/mongo-php-library#85]
I have document with `protected $_id;` and `function getId()` but the error show in `Operation/InsertOne.php` in line 83:

    $insertedId = is_array($this->document) ? $this->document['_id'] : $this->document->_id;

When I remove that line, document is inserted with new id without problems.

`PHP 7.0.1`, `mongodb v2.6.11`, `mongodb driver 1.1.1`.
.

**Comment by jmikola** [comment]
Can you share your document class implementation? If the class is implementing our BSON Serializable interface, you've reached an edge case I allude to [here](https://github.com/mongodb/mongo-php-library/blob/80a0d523b61615a9532bbf62c0894dbb2a772c90/src/Operation/InsertOne.php#L82). This requires a change to the extension ([PHPC-382](https://jira.mongodb.org/browse/PHPC-382)), which I hope to implement in 1.2.0.

I believe this would only occur for a Serializable classes, as other objects would only get their public properties encoded (protected/private properties are ignored per [persistence documentation](http://php.net/manual/en/mongodb.persistence.php)). In that case, `BulkWrite::insert()` would have needed to generate an ID, which would then have been returned and you'd never reach the offending code.

As a temporary work-around, we should be able to invoke [`bsonSerialize()`](http://php.net/manual/en/mongodb-bson-serializable.bsonserialize.php) from userland and capture the ID.

**Comment by jmikola** [comment]
Opened [PHPLIB-157](https://jira.mongodb.org/browse/PHPLIB-157) to track this.

**Comment by veego** [comment]
My class implements `\MongoDB\BSON\Persistable` and I use [Transistor](https://github.com/bjori/mongo-php-transistor) at the moment (I added `\MongoDB` before `BSON\...` to all classes in `Transistor`.


    class Document implements \MongoDB\BSON\Persistable {
	
        use Transistor;
	
	protected $_id;

	...

	function __construct() {
    	    $this->_id  = new \MongoDB\BSON\ObjectID();
        }
	function getId() {
            return $this->_id;
        }

        ...
