### ISSUE TITLE
$manager->selectServer($readPreference) fail to return a Server

### ISSUE THREAD

**Issue by hesselprodigentia** [mongodb/mongo-php-library#863]
### Bug Report

Instability to retry a Server instance, sometimes return well and another nothing (none expected exception at least).
I found this https://jira.mongodb.org/browse/PHPLIB-729. 

### Environment

```
PHP 8.0.10

Nginx 
CosmosDB connection
Laravel/lumen-framework 8.2.1

------------
mongodb
libbson bundled version => 1.18.0
libmongoc bundled version => 1.18.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
libmongocrypt bundled version => 1.2.1
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value


DB_MONGO_CONNECTION => "mongodb"
DB_COSMOS_DSN => "mongodb://xxxxxxxx/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=xxxxxx"
DB_MONGO_DRIVER => "mongodb"
$_SERVER['DB_MONGO_CONNECTION'] => "mongodb"
$_SERVER['DB_COSMOS_DSN'] => "mongodb://xxxxxx/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=xxxxxx"
$_SERVER['DB_MONGO_DRIVER'] => "mongodb"
$_ENV['DB_MONGO_CONNECTION'] => "mongodb"
$_ENV['DB_COSMOS_DSN'] => "mongodb://xxxxxxx/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=xxxxxx"
$_ENV['DB_MONGO_DRIVER'] => "mongodb"
------------------
name     : mongodb/mongodb
descrip. : MongoDB driver library
keywords : database, driver, mongodb, persistence
versions : * 1.8.0
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : https://jira.mongodb.org/browse/PHPLIB
source   : [git] https://github.com/mongodb/mongo-php-library.git 953dbc19443aa9314c44b7217a16873347e6840d
dist     : [zip] https://api.github.com/repos/mongodb/mongo-php-library/zipball/953dbc19443aa9314c44b7217a16873347e6840d 953dbc19443aa9314c44b7217a16873347e6840d
path     : /var/www/code/vendor/mongodb/mongodb
names    : mongodb/mongodb

support
issues : https://github.com/mongodb/mongo-php-library/issues
source : https://github.com/mongodb/mongo-php-library/tree/1.8.0

autoload
psr-4
MongoDB\ => src/
files

requires
ext-hash *
ext-json *
ext-mongodb ^1.8.1
jean85/pretty-package-versions ^1.2
php ^7.0 || ^8.0
symfony/polyfill-php80 ^1.19

requires (dev)
squizlabs/php_codesniffer ^3.5, <3.5.5
symfony/phpunit-bridge 5.x-dev
```
---------------------------------

### Expected and Actual Behavior

Expected to retrieve a MongoDB\Driver\Server 
when  \MongoDB\select_server function is called and execute line 431 $manager->selectServer($readPreference)

Behavior 
Empty is returned

### Debug Log

```
string(0) ""
string(4002) "#0 /var/www/code/vendor/mongodb/mongodb/src/functions.php(432): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference))
#1 /var/www/code/vendor/mongodb/mongodb/src/Collection.php(651): MongoDB\select_server(Object(MongoDB\Driver\Manager), Array)
```

**Comment by jmikola** [comment]
[PHPLIB-729](https://jira.mongodb.org/browse/PHPLIB-729) is definitely unrelated to this issue. That is an internal ticket to track any PHP changes related to https://github.com/mongodb/specifications/pull/1076, which is a clarification to the cross-driver [Server Selection specification](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst). That issue does not actually pertain to how the driver selects a server (what you're doing here). Instead, it's talking about how the driver needs to forward the application's read preference on to the server by way of the `$readPreference` [global command argument](https://github.com/mongodb/specifications/blob/master/source/message/OP_MSG.rst#global-command-arguments). FWIW, I don't think PHP will actually require changes for that issue as it, by way of [libmongoc](https://github.com/mongodb/mongo-c-driver), should already be doing the correct thing.

Moving on: [`MongoDB\select_server`](https://github.com/mongodb/mongo-php-library/blob/1.9.0/src/functions.php#L420) is an internal function and is not intended to be called by applications. We cannot enforce that in PHP, but it is documented as such. That said, the function is most likely just calling [`MongoDB\Driver\Manager::selectServer()`](https://www.php.net/manual/en/mongodb-driver-manager.selectserver.php). I'm not sure what you mean by "empty is returned", but based on both the documentation and [implementation](https://github.com/mongodb/mongo-php-driver/blob/1.10.0/src/MongoDB/Manager.c#L724) of `selectServer`, the function either returns a `MongoDB\Driver\Server` instance or throws an exception. It's not clear to me how your "Debug Log" was produced, but it does look like it includes part of a stack trace so I assume there is actually an exception being thrown. If you're able to capture the complete exception and its stack trace, I can try and help you make sense of it.

Beyond that, you should note that the current stable versions of the PHP library and extension are [1.9.0](https://github.com/mongodb/mongo-php-library/releases/tag/1.9.0) and [1.10.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.10.0), respectively.

`maxIdleTimeMS` is not a supported connection string option for PHP. The cross-driver [URI Options specification](https://github.com/mongodb/specifications/blob/master/source/uri-options/uri-options.rst) notes that it only applies to drivers with connection pools, which does not include PHP. As such, you won't find it listed in the [`MongoDB\Driver\Manager::__construct()`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) documentation. I don't think this is relevant to your issue, as the option will just be ignored, but it seemed reasonable to point this out.

Lastly, CosmosDB is not officially supported by the MongoDB drivers. I'm happy to try and help you diagnose the exception (assuming you can share that), but if this is ultimately an issue involving CosmosDB you'll have to follow up with the Microsoft Azure folks for further support.

**Comment by hesselprodigentia** [comment]
Thank you for the entire comment <3

 It was not easy to debug on production, but after some effort, we finally "found" the issue.

Just to let anyone knows, the "empty" mentioned was about the $exception message; catching the entire $exception was type ConnectionTimeoutException.

Following the [official documentation](https://www.php.net/manual/en/mongodb-driver-manager.construct.php#mongodb-driver-manager.construct-urioptions), we let explicit the connection option connectTimeoutMS


My unique concern was about the method MongoDB\Driver\Manager->selectServer. It returns the driver response direct, and the lib doesn't allow to specify some retry on its point (or I'm not aware about, I'm sorry if it exists somehow, please let me know), none retry, fallback, "cache", or recursive ensure to check. And it's used on all methods, I understand that Cosmos isn't officially maintained, but in case of any connection intermittence with any provider, it could be quick beneficial. 



`object(MongoDB\Driver\Exception\ConnectionTimeoutException)#200 (8) {
  ["message":protected]=>
  string(0) ""
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(13053)
  ["file":protected]=>
  string(54) "/var/www/code/vendor/mongodb/mongodb/src/functions.php"
  ["line":protected]=>
  int(432)
  ["trace":"Exception":private]=>
  array(28) {
    [0]=>
    array(6) {
      ["file"]=>
      string(54) "/var/www/code/vendor/mongodb/mongodb/src/functions.php"
      ["line"]=>
      int(432)
      ["function"]=>
      string(12) "selectServer"
      ["class"]=>
      string(22) "MongoDB\Driver\Manager"
      ["type"]=>
      string(2) "->"`
