### ISSUE TITLE
Link to legacy driver in README returns 404

### ISSUE THREAD

**Issue by dbrumann** [mongodb/mongo-php-library#871]
### "Bug" Report

In the README you reference the legacy php driver:

> While the extension provides a limited API for executing commands, queries, and write operations, this library implements an API similar to that of the [legacy PHP driver](https://php.net/manual/en/book.mongo.php).

The provided link <https://php.net/manual/en/book.mongo.php> no longer works and returns a 404 instead.

### Expected and Actual Behavior

I would expect either the README to no longer have the link or the missing content to be restored in the php docs.

**Comment by jmikola** [comment]
Thanks for the report. I created [PHPLIB-765](https://jira.mongodb.org/browse/PHPLIB-765) to track this and it should be taken care of by https://github.com/mongodb/mongo-php-library/pull/872.
