### ISSUE TITLE
 Call to undefined function MongoDB\server_supports_feature

### ISSUE THREAD

**Issue by sshilko** [mongodb/mongo-php-library#89]
Call to undefined function MongoDB\server_supports_feature() in [/var/www/localhost/composer/mongodb/mongodb/src/Collection.php](https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php#L527) on line 527

Call to undefined function MongoDB\is_first_key_operator() in /var/www/localhost/composer/mongodb/mongodb/src/Operation/FindOneAndUpdate.php on line 68

```
PHP 5.6.16-2+deb.sury.org~precise+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

mongodb

mongodb support => enabled
mongodb version => 1.1.2
mongodb stability => stable
libmongoc version => 1.3.1-dev
libbson version => 1.3.0

Directive => Local Value => Master Value
mongodb.debug => no value => no value
```

**Comment by sshilko** [comment]
functions are not loaded w/o composer

**Comment by AlexGnatko** [comment]
Or just do this:

`require_once "mongo-php-library/src/functions.php";`

if "mongo-php-library" is on your script's include_path.
