### ISSUE TITLE
MongoId::getTimestamp — Gets the number of seconds since the epoch that this id was created

### ISSUE THREAD

**Issue by sshilko** [mongodb/mongo-php-library#90]
"legacy" mongo driver provided a method http://php.net/manual/en/class.mongoid.php 
```
getTimestamp 
```

to extract timestamp from mongoid's

i cant see analog in new driver
http://php.net/manual/en/class.mongodb-bson-objectid.php

is there a way to extract time from mongoId using new driver?

**Comment by jmikola** [comment]
There is not currently a method for this, but we can certainly consider adding it in a future `1.x` release (e.g. 1.2). I'll make a ticket on the [PHPC](https://jira.mongodb.org/browse/PHPC) project this week to track the request, and cross-reference it here.

In the meantime, you should be able to use [`hex2bin()`](http://php.net/manual/en/function.hex2bin.php) on the string representation of the ID (`__toString()` returns a 24-character hexadecimal string) and then use `unpack()` to extra the first four bytes. You may find the code from [mongofill's MongoId implementation](https://github.com/mongofill/mongofill/blob/c2a16b7cb6c8fa94aa4c286acd8b4a90c3a843f5/src/MongoId.php#L120) a helpful reference for that.

**Comment by sshilko** [comment]
thx i will use ```unpack```, just migrated from mongo to mongodb extension, looks good so far.

**Comment by jmikola** [comment]
Tracking ticket: [PHPC-552](https://jira.mongodb.org/browse/PHPC-552). Also, a more convenient solution may be to use `hexdec()` on the first 8 bytes of the ObjectID's hexadecimal representation. See: https://github.com/alcaeus/mongo-php-adapter/blob/ef2f253ba47e376ba220ba1cde753c99a51e2705/lib/Mongo/MongoId.php#L174
