### ISSUE TITLE
Installation w/o Composer

### ISSUE THREAD

**Issue by vLifeOfBrian** [mongodb/mongo-php-library#92]
How would you install this library without composer on Windows and PHP 7.1?

**Comment by jmikola** [comment]
You should be able to download tarballs from the [releases](https://github.com/mongodb/mongo-php-library/releases) and unpack those as you like; however, you'll need to configure autoloading for the `MongoDB\` namespace and require the `functions.php` file in your own boiler-plate code (i.e. the equivalent of Composer's `autoload` configuration in [`composer.json`](https://github.com/mongodb/mongo-php-library/blob/54b9605b080405d9efae26de6e2eafea38c02acc/composer.json#L16)).
