### ISSUE TITLE
Issue with Projections

### ISSUE THREAD

**Issue by gphargreaves** [mongodb/mongo-php-library#98]
mongodb driver version: 1.1.2
library version: 1.0.0-beta2

Projections don't appear to be having any affect on returned results from *findOne* or *find*

Using the following syntax to filter returned values:

**$collection->findOne(array("token" => $curr_token),array('desc' => true));**

This still returns the entire document for the specified query rather than just the 'desc' field.

The end goal was to use the following filter (which also wasn't having any effect):

**array('logs' => array('$elemMatch' => array('read' => false)))**

Apologies if this is user error but I have tested multiple filters and none changes the output.

**Comment by jacqueswaller** [comment]
the second parameter is now a generic "options" table, with everything you could use to manipulate the query (limit, sort, projection, readConcern, readPreference, typeMap, are there others?).

so you would do it something like
```
$collection->findOne(array("token" => $curr_token),array('projection' => array('desc' => true)));
```

I personally like the new syntax, though it does suck to migrate everything :\

**Comment by gphargreaves** [comment]
Great, thanks for that! I was using the php.net documentation of the library which still has it documented as its own parameter :-)
